"""Clustering and neighborhood preservation plotting utilities.

This module contains plotting functions for visualizing clustering quality,
neighborhood preservation, and cell-type classification results from
the evaluation pipeline.

Includes:
- UMAP visualization colored by clusters and cell types
- Neighborhood preservation scores across k values
- Clustering quality metrics (ARI, NMI)
- Cell-type classification metrics (F1 scores, confusion matrices)
"""

from __future__ import annotations

import gc
import logging
import os
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import seaborn as sns

# --- load THIS directory's _constants.py by path (sibling dirs share the name) ---
import importlib.util as _ilu, sys as _sys
from pathlib import Path as _cpath
_cspec = _ilu.spec_from_file_location("_constants", _cpath(__file__).resolve().parent / "_constants.py")
_sys.modules["_constants"] = _ilu.module_from_spec(_cspec)
_cspec.loader.exec_module(_sys.modules["_constants"])


from _constants import (
    COL_CELLTYPE,
    COL_DATASET,
    COL_F1_SCORE,
    COL_K,
    COL_PRESERVATION_SCORE,
    COL_REPRESENTATION,
    DEFAULT_PNG_DPI,
)

logger = logging.getLogger(__name__)

# Presentation-friendly defaults for all plots generated by this module.
plt.rcParams.update(
    {
        "font.size": 16,
        "axes.titlesize": 20,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 14,
        "figure.titlesize": 22,
    }
)


def _dataset_line_style(dataset_name: str) -> str:
    """Return a deterministic line style based on panel size encoded in dataset name."""
    match = re.search(r"_(\d+)(?:_|$)", str(dataset_name))
    if not match:
        return "-"
    size = int(match.group(1))
    if size == 100:
        return "-"
    if size == 200:
        return "--"
    if size == 500:
        return "-."
    return ":"

__all__ = [
    "extract_factor_number_from_dataset_name",
    "extract_strategy_from_dataset_name",
    "extract_display_name_from_dataset",
    "resolve_marker_strategy",
    "generate_panel_size_colors_and_strategy_markers",
    "generate_method_specific_colors_and_markers",
    "plot_umap_for_representation",
    "plot_neighborhood_preservation_by_k",
    "plot_neighborhood_preservation_celltype_heatmap",
    "plot_clustering_quality_ari",
    "plot_clustering_quality_nmi",
    "plot_celltype_f1_heatmap",
    "plot_celltype_classification_diagnostics_global",
    "plot_celltype_class_sizes",
    "plot_confusion_matrix",
    "create_feature_plots",
]

def extract_factor_number_from_dataset_name(dataset_name):
    """
    Extract the number of NMF factors from a dataset name.
    
    Examples:
        'Scanpy-Filter_All-Genes_RecoVar_RF_0.25_Dimred_0.75_2factors_100' → 2
        'Xenium-Filter_HVG-Subset_nmf_15factors_200' → 15
        'Scanpy-Filter_All-Genes_Random_100' → None
        
    Parameters:
    -----------
    dataset_name : str
        Full dataset name/path
        
    Returns:
    --------
    int or None
        Number of factors if found, None otherwise
    """
    import re
    
    # Remove path and file extension
    name = os.path.basename(dataset_name)
    if name.endswith('.h5ad'):
        name = name[:-5]
    
    # Look for pattern like _2factors_ or _15factors_
    factor_match = re.search(r'_(\d+)factors_', name)
    if factor_match:
        return int(factor_match.group(1))
    
    return None


def extract_strategy_from_dataset_name(dataset_name):
    """
    Extract the strategy name and gap-filling variant from a dataset filename.
    Factor numbers (_Nfactors_) are removed from the strategy to allow grouping.
    
    Dataset naming pattern:
        {Filter}_{Baseline}_{Strategy}_{N-genes}_{optional-addon}.h5ad
        
    Examples:
        'Scanpy-Filter_All-Genes_deg_only_100_5k-addon' → ('deg_only', None)
        'Scanpy-Filter_All-Genes_RecoVar_PCA_RF_0.5_Dimred_0.5_100' → ('RecoVar_PCA_RF_0.5_Dimred_0.5', None)
        'Scanpy-Filter_All-Genes_RecoVar_RF_0.25_Dimred_0.75_2factors_100' → ('RecoVar_RF_0.25_Dimred_0.75', None)
        'Scanpy-Filter_All-Genes_Random_100' → ('Random', None)
        '/path/to/Scanpy-Filter_All-Genes_deg_only_100_5k-addon_DEG-based-filling.h5ad' → ('deg_only', 'DEG-based-filling')

    Parameters:
    -----------
    dataset_name : str
        Full dataset name/path with optional gap-filling variant suffix

    Returns:
    --------
    tuple : (base_strategy, gap_filling_variant)
        base_strategy: The core strategy identifier (e.g., 'deg_only', 'RecoVar_RF_0.25_Dimred_0.75')
                      Factor numbers are removed from the strategy name.
        gap_filling_variant: One of 'DEG-based-filling', 'global-gene-filling',
                            'cell-type-specific-filling', or None
    """
    import re
    
    # Remove path and file extension
    name = os.path.basename(dataset_name)
    if name.endswith('.h5ad'):
        name = name[:-5]
    
    # Remove factor number from name if present (e.g., _2factors_, _15factors_)
    # This allows factor-range datasets to be grouped by strategy
    name = re.sub(r'_(\d+)factors_', '_', name)
    
    # Check for gap-filling variant - can be at end or before addon suffix
    gap_filling_variant = None
    for variant in ['DEG-based-filling', 'global-gene-filling', 'cell-type-specific-filling']:
        # Check if variant is at the end
        if name.endswith(f'_{variant}'):
            gap_filling_variant = variant
            # Remove variant from name for further parsing
            name = name[:-len(f'_{variant}')]
            break
        # Check if variant appears before an addon suffix (like _mMulti-addon, _5k-addon)
        elif f'_{variant}_' in name:
            gap_filling_variant = variant
            # Remove variant from name (but keep the addon suffix)
            name = name.replace(f'_{variant}_', '_')
            break
    
    # Split by underscores
    parts = name.split('_')
    
    # Strategy identification patterns
    # Format: {Filter}_{Baseline}_{Strategy}_{N-genes}_{optional-addon}
    
    # Common external panels - check these first (but be specific)
    # This function now uses a more generic approach to detect external panels
    # 
    # Strategy:
    # 1. Check for standalone panels (exact match)
    # 2. Check for known external panels that should return simplified names (Spapros, mMulti, 5k)
    # 3. Check if any part of the name matches the pattern of external panels that return full names
    #
    # External panels fall into two categories:
    # Category A: Simple external panels that return a simplified identifier (e.g., 'Spapros', '5k')
    # Category B: Complex external panels that return the full name to preserve filter/size info
    #             These are detected by checking if the name is NOT a standard pipeline pattern
    
    # === CATEGORY A: Simple standalone panels (exact match) ===
    if name == '5k':
        return '5k', gap_filling_variant
    if name == 'mMulti_v1' or name == 'mMulti':
        return 'mMulti_v1', gap_filling_variant
    if name == 'Spapros' or name == 'spapros':
        return 'Spapros', gap_filling_variant
    
    # === CATEGORY A: Known panels in compound names (simplified identifier) ===
    # Check for Spapros - only if it's the strategy, not part of addon
    if 'Spapros' in name and not name.endswith('Spapros-addon'):
        parts_check = name.split('_')
        if len(parts_check) > 2 and 'Spapros' in parts_check[1:3]:
            return 'Spapros', gap_filling_variant
    
    # Check for 5k in compound names (not '5k-addon')
    if '_5k_' in name and not name.endswith('5k-addon'):
        return '5k', gap_filling_variant
    
    # === CATEGORY B: Generic external panel detection ===
    # First check if this contains a known external panel name
    # Do this BEFORE checking pipeline patterns to ensure external panels are detected
    # even if they contain strings like "HVG" in the filter prefix
    known_external_panels = ['NSForest', 'scMER', 'Spapros', 'mMulti_v1', '5k']
    
    for panel_name in known_external_panels:
        # Check if panel name appears in the dataset name
        # Pattern: either as _PanelName_ or ending with _PanelName
        if f'_{panel_name}_' in name or name.endswith(f'_{panel_name}'):
            # Return the simplified panel name for color mapping
            # This allows "Scanpy-Filter_All-Genes_NSForest_100" → 'NSForest'
            # and "Xenium-Filter_HVG-Subset_NSForest_200" → 'NSForest'
            return panel_name, gap_filling_variant
    
    # If no known external panel found, check if this looks like an external panel
    # by checking if it does NOT match standard pipeline patterns
    parts_check = name.split('_')
    
    # Check if name does NOT match any known pipeline patterns
    pipeline_patterns = [
        'RecoVar_RF_', 'RecoVar_PCA_RF_',  # Hybrid RF + dimred strategies
        'RecoVar',  # Bare RecoVar / RecoVar_PCA
        'dimred_only', '_pca_', '_nmf_',  # Dimred-only
        'deg_only', 'rf_simple', 'rf_deg',  # Simple strategies
        'Random', 'HVG', 'random', 'hvg'  # Baselines
    ]

    is_pipeline_pattern = any(pattern in name for pattern in pipeline_patterns)
    is_addon_suffix = name.endswith('-addon')
    
    # If it's not a pipeline pattern and not an addon, and has multiple parts,
    # assume it's a complex external panel - return full name
    if not is_pipeline_pattern and not is_addon_suffix and len(parts_check) >= 3:
        # This catches panels like "Scanpy-Filter_HVG_UnknownTool_200" or any future external panels
        # Return the full name to preserve all context
        return name, gap_filling_variant
    
    # 1. Combination strategies: RF share + dimred share (RecoVar / RecoVar_PCA hybrids).
    # Checked before the simple-strategy string match below so the '_RecoVar_' substring
    # inside a hybrid name is not mistaken for the bare 'RecoVar' strategy.
    combo_pattern = r'RecoVar(_PCA)?_RF_([\d.]+)_Dimred_([\d.]+)'
    combo_match = re.search(combo_pattern, name)
    if combo_match:
        pca_flag, rf_ratio, dimred_ratio = combo_match.groups()
        prefix = 'RecoVar_PCA' if pca_flag else 'RecoVar'
        return f"{prefix}_RF_{rf_ratio}_Dimred_{dimred_ratio}", gap_filling_variant

    # 2. Simple strategies: deg_only, rf_simple, rf_deg, RecoVar(_PCA), hvg, random
    # (these contain underscores, so check as strings). RecoVar_PCA before RecoVar.
    # Also match a LEADING token (name.startswith(f'{strategy}_')) -- some naming
    # conventions (e.g. Analysis-scripts/orchestrators/run_recovar_audit3_validation.sbatch's
    # "RecoVar_raw_rf0.5_nmf0.5_LCA_500genes_seed42") put the strategy first with no
    # underscore before it, so the underscore-bounded check alone would never match.
    simple_strategies = ['deg_only', 'rf_simple', 'rf_deg',
                         'RecoVar_PCA', 'RecoVar', 'hvg', 'random']
    for strategy in simple_strategies:
        if f'_{strategy}_' in name or name.startswith(f'{strategy}_'):
            return strategy, gap_filling_variant

    # 3. Baselines: Random, HVG (check both uppercase and lowercase)
    if 'Random' in parts or 'random' in parts:
        return 'Random', gap_filling_variant
    if 'HVG' in parts or 'hvg' in parts:
        return 'HVG', gap_filling_variant

    # 4. Dimensionality-reduction-only panels. RecoVar emits
    # 'dimred_only_{nmf,pca}_per_celltype'; older Modules_v2 names were
    # '{nmf,pca}_{global,per_celltype}' with an optional trailing _method_a/_method_b.
    # Only the dimred token (nmf / pca) is meaningful now.
    dimred_pattern = r'_(?:dimred_only_)?(pca|nmf)_(?:global|per_celltype)(?:_method_[ab])?'
    dimred_match = re.search(dimred_pattern, name)
    if dimred_match:
        return dimred_match.group(1), gap_filling_variant

    # Fallback: return the dataset name itself if no pattern matches
    return name, gap_filling_variant


def extract_display_name_from_dataset(dataset_name, factor_range_mode=False, include_size=False):
    """
    Extract a clean display name (strategy + filling method) from full dataset name.
    
    This matches the behavior of extract_strategy_and_display_name from the
    variability plotting module - returns short, human-readable strategy names
    without filter/baseline/size/addon information, but INCLUDES the filling method suffix.
    
    Examples:
        'Scanpy-Filter_All-Genes_rf_deg_100_5k-addon' → 'rf_deg'
        'Scanpy-Filter_All-Genes_Random_100' → 'Random'
        'Scanpy-Filter_All-Genes_RecoVar_PCA_RF_0.5_Dimred_0.5_100' → 'RecoVar_PCA 50%'
        'Scanpy-Filter_All-Genes_RecoVar_PCA_RF_0.5_Dimred_0.5_200_DEG-based-filling' → 'RecoVar_PCA 50% (DEG-fill)'
        'Scanpy-Filter_All-Genes_RecoVar_RF_0.5_Dimred_0.5_200_cell-type-specific-filling' → 'RecoVar 50% (CT-fill)'
        'mMulti_v1' → 'mMulti_v1'

    Factor-range mode (factor_range_mode=True):
        'Scanpy-Filter_All-Genes_RecoVar_RF_0.25_Dimred_0.75_2factors_100' → '2-factors'
        'Xenium-Filter_HVG-Subset_dimred_only_nmf_per_celltype_15factors_200' → '15-factors'

    Panel-size mode (include_size=True):
        'Scanpy-Filter_All-Genes_RecoVar_RF_0.75_Dimred_0.25_100_CT-fill' → 'RecoVar 25% (100)'
        'Xenium-Filter_Spapros_200' → 'Spapros (200)'
        
    Parameters:
    -----------
    dataset_name : str
        Full dataset name with settings
    factor_range_mode : bool, optional
        If True, return only the factor number for factor-range plots
    include_size : bool, optional
        If True, include panel size in the display name (for panel-size comparison plots)
        
    Returns:
    --------
    str
        Clean display name for plot labels/legends (includes filling method if present)
    """
    import re
    
    # Extract panel size if requested
    panel_size_str = ""
    if include_size:
        size_match = re.search(r'_(\d+)(?:_|$)', dataset_name)
        if size_match:
            panel_size_str = f" ({size_match.group(1)})"
    
    # If in factor-range mode, return only the factor number
    if factor_range_mode:
        factor_num = extract_factor_number_from_dataset_name(dataset_name)
        if factor_num is not None:
            return f"{factor_num}-factors{panel_size_str}"
    
    # Extract the base strategy and filling variant
    base_strategy, gap_filling_variant = extract_strategy_from_dataset_name(dataset_name)
    
    # Define abbreviations for filling methods
    filling_abbrev = {
        'DEG-based-filling': 'DEG-fill',
        'cell-type-specific-filling': 'CT-fill',
        'global-gene-filling': 'Global-fill'
    }
    
    # For external panels and baselines, return as-is (no filling suffix expected)
    # Known simple external panels (these return simplified names from extract_strategy_from_dataset_name)
    simple_external_panels = ['5k', 'mMulti_v1', 'mMulti', 'Spapros', 'spapros', 'NSForest', 'scMER']
    baselines = ['Random', 'HVG']
    simple_strategies = ['deg_only', 'rf_simple', 'rf_deg', 'nmf', 'pca']
    
    # Check exact match for simple panels/baselines/strategies
    if base_strategy in simple_external_panels or base_strategy in baselines or base_strategy in simple_strategies:
        # For external panels, return just the panel name for clean display
        # This shows "NSForest" or "scMER" instead of the full filename
        return base_strategy + panel_size_str
    
    # Check if this is a complex external panel (full name returned from extract_strategy_from_dataset_name)
    # These panels don't match any pipeline patterns but have multiple components
    # Examples: "Scanpy-Filter_HVG_NSForest_200", "No-Filter_All-Genes_ExternalTool_100"
    pipeline_patterns = [
        'RecoVar_RF_', 'RecoVar_PCA_RF_',  # Hybrid RF + dimred strategies
    ]

    is_pipeline_pattern = any(pattern in base_strategy for pattern in pipeline_patterns)
    has_multiple_parts = len(base_strategy.split('_')) >= 3

    # If it's not a pipeline pattern and has multiple parts, it's likely a complex external panel
    if not is_pipeline_pattern and has_multiple_parts:
        # Return full name for complex external panels to preserve all context
        return base_strategy + panel_size_str

    # For hybrid strategies, extract the dimred percentage.
    # Pattern: RecoVar_RF_0.25_Dimred_0.75 → 'RecoVar 75%'
    #          RecoVar_PCA_RF_0.5_Dimred_0.5 → 'RecoVar_PCA 50%'
    hybrid_pattern = r'RecoVar(_PCA)?_RF_([\d.]+)_Dimred_([\d.]+)'
    hybrid_match = re.search(hybrid_pattern, base_strategy)
    if hybrid_match:
        pca_flag, rf_ratio, dimred_ratio = hybrid_match.groups()
        percentage = int(float(dimred_ratio) * 100)
        prefix = 'RecoVar_PCA' if pca_flag else 'RecoVar'
        display_name = f"{prefix} {percentage}%"

        # Add filling suffix if present
        if gap_filling_variant:
            filling_text = filling_abbrev.get(gap_filling_variant, gap_filling_variant)
            display_name = f"{display_name} ({filling_text})"
        return display_name + panel_size_str
    
    # Fallback: return the base strategy (with filling suffix if present)
    if gap_filling_variant:
        filling_text = filling_abbrev.get(gap_filling_variant, gap_filling_variant)
        return f"{base_strategy} ({filling_text})" + panel_size_str
    return base_strategy + panel_size_str


def resolve_marker_strategy(dataset_names):
    """
    Analyze datasets to determine whether to use gap-filling markers or ratio markers.
    
    Logic:
    - If 2+ gap-filling strategies present with same ratio → use gap-filling markers
    - If 2+ ratio combinations present with same gap-filling → use ratio markers
    - If both vary together → raise error (incompatible grouping)
    - If only one varies → use markers for the varying dimension
    
    Parameters:
    -----------
    dataset_names : list
        List of dataset names to analyze
        
    Returns:
    --------
    str
        One of: 'gap_filling', 'ratio', 'none', or raises ValueError if incompatible
    """
    # Extract info for each dataset
    gap_filling_variants = set()
    ratios = set()
    hybrid_datasets = []
    
    for name in dataset_names:
        base_strategy, gap_filling_variant = extract_strategy_from_dataset_name(name)
        
        # Only analyze hybrid strategies (RecoVar / RecoVar_PCA)
        if base_strategy.startswith('RecoVar_RF_') or base_strategy.startswith('RecoVar_PCA_RF_'):
            # Extract ratio
            import re
            pattern = r'Dimred_([\d.]+)'
            match = re.search(pattern, base_strategy)
            if match:
                ratio = float(match.group(1))
                ratios.add(ratio)
                gap_filling_variants.add(gap_filling_variant)
                hybrid_datasets.append(name)
    
    # If no hybrid strategies, markers don't matter for this distinction
    if not hybrid_datasets:
        return 'none'
    
    num_gap_variants = len(gap_filling_variants)
    num_ratios = len(ratios)
    
    logging.info(f"Marker strategy analysis: {num_gap_variants} gap-filling variants, {num_ratios} ratios")
    logging.info(f"  Gap-filling variants: {gap_filling_variants}")
    logging.info(f"  Ratios: {ratios}")
    
    # Decision logic - Priority: ratios > gap-filling
    if num_ratios >= 2:
        # Multiple ratios - use ratio markers (highest priority)
        logging.info("  → Using ratio markers (multiple ratio combinations - priority)")
        return 'ratio'
    elif num_gap_variants >= 2:
        # Multiple gap-filling strategies, same ratio
        logging.info("  → Using gap-filling markers (multiple gap-filling strategies)")
        return 'gap_filling'
    else:
        # Only one of each - doesn't matter, use ratio markers as default
        logging.info("  → Using ratio markers (default, only one gap-filling variant)")
        return 'ratio'


def generate_panel_size_colors_and_strategy_markers(dataset_names, external_names=None):
    """
    Generate colors based on panel size and markers based on strategy.
    Used when comparing the same strategies across different panel sizes (100, 200, 500).
    
    Color assignment by panel size:
    - 100 genes: Light blue (#87CEEB)
    - 200 genes: Light orange (#FFB366)
    - 500 genes: Dark green (#2E7D32)
    
    Marker assignment by strategy:
    - RecoVar: circle (o) - regardless of filling strategy
    - RecoVar_PCA: circle (o) - regardless of filling strategy
    - nmf: diamond (D)
    - pca: diamond (D)
    - rf_simple: triangle up (^)
    - rf_deg: triangle down (v)
    - deg_only: pentagon (p)
    - hvg: hexagon (h)
    - random: plus (+)
    - Spapros: square (s)
    - Other external panels: star (*)
    
    Parameters:
    -----------
    dataset_names : list
        List of dataset names
    external_names : list, optional
        List of external panel names (e.g., ['Spapros'])
    
    Returns:
    --------
    tuple
        Tuple containing (color_map, marker_map, uses_size_coloring) 
        where uses_size_coloring is True if multiple sizes detected
    """
    import re
    
    color_map = {}
    marker_map = {}
    
    # Define panel size colors
    size_colors = {
        100: "#1C8EBB",  # Blue
        200: "#E77E16",  # Orange
        500: '#2E7D32',  # Dark green (forest green)
    }
    
    # Define strategy markers
    strategy_markers = {
        'RecoVar': 'o',      # Circle
        'RecoVar_PCA': 'o',  # Circle
        'nmf': 'D',         # Diamond
        'pca': 'D',         # Diamond
        'rf_simple': '^',   # Triangle up
        'rf_deg': 'v',      # Triangle down
        'deg_only': 'p',    # Pentagon
        'hvg': 'h',         # Hexagon
        'random': '+',      # Plus
        'Random': '+',      # Plus (capitalized)
        'HVG': 'h',         # Hexagon (capitalized)
        'Spapros': 's',     # Square
        'spapros': 's',     # Square
    }
    
    # External panels not in the list above get a star marker
    external_names = external_names or []
    
    # Extract panel sizes from all datasets
    panel_sizes = {}
    for name in dataset_names:
        # Look for panel size pattern: _100, _200, _500, etc.
        size_match = re.search(r'_(\d+)(?:_|$)', name)
        if size_match:
            panel_size = int(size_match.group(1))
            panel_sizes[name] = panel_size
    
    # Check if we have multiple different panel sizes
    unique_sizes = set(panel_sizes.values())
    uses_size_coloring = len(unique_sizes) > 1
    
    if not uses_size_coloring:
        # Not a multi-size plot, return empty to signal fallback to default coloring
        logging.info("Single panel size detected - not using panel-size-based coloring")
        return {}, {}, False
    
    logging.info(f"Multiple panel sizes detected: {sorted(unique_sizes)}")
    logging.info("Using panel-size-based coloring: 100→light blue, 200→light orange, 500→dark green")
    
    # Assign colors and markers
    for name in dataset_names:
        # Get panel size for color
        panel_size = panel_sizes.get(name)
        if panel_size in size_colors:
            color_map[name] = size_colors[panel_size]
        else:
            # Default color for unknown sizes
            color_map[name] = '#808080'  # Gray
        
        # Get strategy for marker
        base_strategy, gap_filling_variant = extract_strategy_from_dataset_name(name)
        
        # Check if this is an external panel
        is_external = False
        for ext_name in external_names:
            if ext_name.lower() in base_strategy.lower() or base_strategy.lower() in ext_name.lower():
                is_external = True
                if ext_name in strategy_markers or base_strategy in strategy_markers:
                    marker_map[name] = strategy_markers.get(ext_name, strategy_markers.get(base_strategy, '*'))
                else:
                    marker_map[name] = '*'  # Star for unknown external panels
                break
        
        if not is_external:
            # For hybrid strategies (RecoVar, RecoVar_PCA), extract the base type
            if base_strategy.startswith('RecoVar_PCA'):
                marker_map[name] = strategy_markers['RecoVar_PCA']
            elif base_strategy.startswith('RecoVar'):
                marker_map[name] = strategy_markers['RecoVar']
            elif 'nmf' in base_strategy:
                marker_map[name] = strategy_markers['nmf']
            elif 'pca' in base_strategy:
                marker_map[name] = strategy_markers['pca']
            else:
                # Use strategy_markers lookup
                marker_map[name] = strategy_markers.get(base_strategy, 'o')  # Default to circle
        
        logging.info(f"  {name[:50]}... → size={panel_size}, color={color_map[name]}, marker={marker_map[name]}")
    
    return color_map, marker_map, uses_size_coloring


def generate_method_specific_colors_and_markers(dataset_names, external_names=None, group_name=None):
    """
    Generate colors and markers based ONLY on selection strategy (not on settings like filter/baseline/size/addon).
    
    Colors are assigned consistently across all plots based on the strategy used to generate the panel.
    Settings like filter method, baseline gene pool, panel size, and addon panels do NOT affect color.
    
    Marker assignment follows intelligent logic:
    - For hybrid strategies (RecoVar/RecoVar_PCA): Analyzes which dimension varies in the plot
    - If multiple gap-filling strategies → use gap-filling markers (square, diamond, triangle)
    - If multiple ratio combinations → use ratio markers (circle=25%, square=50%, triangle=75%)
    - If both vary → raises error (incompatible grouping)

    Strategy-based color families:
    - Baseline methods: Gray (Random), Yellow (HVG), Orange family (deg_only, rf_simple, rf_deg)
    - RecoVar (RF + NMF) hybrid: Purple family, shade by dimred share
    - RecoVar_PCA (RF + PCA) hybrid: Lime-green family, shade by dimred share
    - Dimred-only: Pink (nmf), Green (pca)
    - External panels: Green family (Spapros, mMulti, 5k)

    Parameters:
    -----------
    dataset_names : list
        List of dataset names (full names with settings)
    external_names : list, optional
        List of external panel names (e.g., ['Spapros', 'mMulti_v1', '5k'])
        These will be assigned custom colors from a gradient
    group_name : str, optional
        Plot group name (retained for signature compatibility; no longer used).

    Returns:
    --------
    tuple
        Tuple containing (color_map, marker_map) dictionaries mapping dataset names to color codes and markers
    """
    
    color_map = {}
    marker_map = {}
    
    # PRIORITY 1: Check if we should use panel-size-based coloring
    # This takes precedence when multiple panel sizes are compared
    size_color_map, size_marker_map, uses_size_coloring = generate_panel_size_colors_and_strategy_markers(
        dataset_names, external_names
    )
    if uses_size_coloring:
        logging.info("Using panel-size-based coloring scheme")
        return size_color_map, size_marker_map
    
    # Check if we're in factor-range mode by examining dataset names
    import re
    factor_range_mode = False
    if dataset_names:
        # Check if any dataset has factor numbers in the name
        factor_range_mode = any(re.search(r'_\d+factors_', name) for name in dataset_names)
    
    # If in factor-range mode, use factor-specific colors
    if factor_range_mode:
        logging.info("Factor-range mode detected: Using factor-specific colors")
        
        # Define a color palette for factors 2-15 (14 colors total)
        # Using a spectral/rainbow gradient that's visually distinct
        factor_colors = {
            2: '#d62728',   # Red
            3: '#ff7f0e',   # Orange
            4: '#ffbb00',   # Golden yellow
            5: '#bcbd22',   # Yellow-green
            6: '#2ca02c',   # Green
            7: '#17becf',   # Cyan
            8: '#1f77b4',   # Blue
            9: '#0000cd',   # Medium blue
            10: '#8b008b',  # Dark magenta
            11: '#9467bd',  # Purple
            12: '#e377c2',  # Pink
            13: '#ff1493',  # Deep pink
            14: '#8b4513',  # Saddle brown
            15: '#696969',  # Dim gray
        }
        
        # All datasets use the same marker (circle) in factor-range mode
        # Color differentiates the factors
        for name in dataset_names:
            factor_num = extract_factor_number_from_dataset_name(name)
            if factor_num is not None and factor_num in factor_colors:
                color_map[name] = factor_colors[factor_num]
                marker_map[name] = 'o'  # All use circle marker
                logging.info(f"  Assigned factor {factor_num} -> color {factor_colors[factor_num]}")
            else:
                # Fallback if factor number not found or out of range
                color_map[name] = '#808080'  # Gray
                marker_map[name] = 'o'
                logging.warning(f"  Could not extract factor number from '{name}'")
        
        return color_map, marker_map
    
    # Normal mode (not factor-range): Continue with strategy-based colors
    
    # Initialize external_names if not provided
    if external_names is None:
        external_names = []
    
    # Define base colors for different method categories - keep these distinct
    # IMPORTANT: Colors are assigned by STRATEGY only, not by dataset settings
    benchmark_colors = {
        # Baseline/control strategies (both uppercase and lowercase)
        'Random': '#808080',         # Gray
        'random': '#808080',         # Gray (lowercase variant)
        'HVG': '#f0dd0d',            # Yellow
        'hvg': '#f0dd0d',            # Yellow (lowercase variant)
        
        # Simple strategies
        'deg_only': "#fa9c4a",       # Orange
        'rf_simple': "#d56a0d",      # Dark orange
        'rf_deg': "#875223",         # Brown
    }

    # Define benchmark markers - all use circles for easy identification
    benchmark_markers = {
        'Random': 'o',           # Circle
        'random': 'o',           # Circle (lowercase variant)
        'HVG': 'o',              # Circle
        'hvg': 'o',              # Circle (lowercase variant)
        'deg_only': 'o',         # Circle
        'rf_simple': 'o',        # Circle
        'rf_deg': 'o',           # Circle
    }

    
    # Default external panel colors (if specific names match)
    # These are for known/common external panels
    # Unknown external panels will get colors from the gradient below
    default_external_colors = {
        'Spapros': "#957d06",
        'spapros': "#957d06",
        '10x_mMulti_v1': '#000000',  # Black - distinct from all other colors
        '10x_5k':'#000000',  # Black - distinct from all other colors
        'mMulti_v1': '#000000',      # Black - distinct from all other colors
        'mMulti': '#000000',  # Black - distinct from all other colors
        '5k': '#000000',  # Black - distinct from all other colors
    }

    # External panels use distinguishable markers
    external_markers = {
        'Spapros': 'o',          # Circle
        'spapros': 'o',          # Circle
        '10x_mMulti_v1': 'o',    # Circle
        '10x_5k': 'o',           # Circle
        'mMulti_v1': 'o',        # Circle
        'mMulti': 'o',
        '5k': 'o',               # Circle
    }

    # Generate gradient colors for additional external panels
    # Purple to teal gradient for external methods
    external_gradient = [
        "#76EFED",
        "#55AFAE",
        "#3E7C7B",
        "#203F3E",
        "#4C8098",
        "#1C4F66",
    ]
     
    # Build external color/marker maps
    external_color_map = {}
    external_marker_map = {}
    
    for idx, ext_name in enumerate(external_names):
        # Check if we have a default color for this external panel
        if ext_name in default_external_colors:
            external_color_map[ext_name] = default_external_colors[ext_name]
        else:
            # Assign from gradient (cycle if more external panels than gradient colors)
            external_color_map[ext_name] = external_gradient[idx % len(external_gradient)]
        
        # Assign marker
        if ext_name in external_markers:
            external_marker_map[ext_name] = external_markers[ext_name]
        else:
            # Alternate between circle and square for unknown external panels
            external_marker_map[ext_name] = 'o' if idx % 2 == 0 else 's'
    
    # Special handling for Spapros: Check if multiple panel sizes (100, 200, 500) are present
    # If so, assign different markers based on panel size to distinguish them
    spapros_datasets = [name for name in dataset_names if 'Spapros' in name or 'spapros' in name]
    spapros_panel_sizes = {}
    
    if len(spapros_datasets) > 1:
        # Extract panel sizes from Spapros dataset names
        import re
        for name in spapros_datasets:
            # Look for panel size pattern: _100, _200, _500, etc.
            size_match = re.search(r'_(\d+)(?:_|$)', name)
            if size_match:
                panel_size = int(size_match.group(1))
                spapros_panel_sizes[name] = panel_size
                logging.info(f"Detected Spapros dataset '{name}' with panel size {panel_size}")
        
        # If we found multiple Spapros with different sizes, assign size-specific markers
        unique_sizes = set(spapros_panel_sizes.values())
        if len(unique_sizes) > 1:
            logging.info(f"Multiple Spapros panel sizes detected: {sorted(unique_sizes)}")
            logging.info("Assigning size-specific markers: 100→circle, 200→square, 500→triangle")
            
            # Define size-to-marker mapping
            size_marker_map = {
                100: 'o',   # Circle for 100 genes
                200: 's',   # Square for 200 genes
                500: '^',   # Triangle for 500 genes
            }
            
            # Update external_marker_map for Spapros datasets based on size
            for name, size in spapros_panel_sizes.items():
                if size in size_marker_map:
                    # Find the external name that matches this dataset
                    for ext_name in external_names:
                        if ext_name in name or name in ext_name or ext_name.lower() == 'spapros':
                            # Store marker with dataset name key for later lookup
                            external_marker_map[name] = size_marker_map[size]
                            logging.info(f"  Assigned marker '{size_marker_map[size]}' to Spapros panel size {size}")
                            break
    
    # Systematic color scheme: Color family = Model type, Shade = dimred share.
    # Color families by model type:
    # - Purple family: RecoVar (hybrid RF + NMF)
    # - Lime-green family: RecoVar_PCA (hybrid RF + PCA)
    # - Pink/Magenta: nmf-only        - Green: pca-only
    # - Orange family: rf_deg and deg-only        - Gray family: baseline methods
    # Within a hybrid family the shade tracks the dimred (NMF/PCA) share: lighter = smaller
    # share, darker = larger share.

    # RecoVar hybrid (RF + NMF) color map, keyed by dimred (NMF) share percentage.
    RecoVar_colors = {
        10: '#DDAAFF',  # Very light purple - 10% NMF
        25: '#BB88FF',  # Light purple - 25% NMF
        50: '#9933FF',  # Vivid purple - 50% NMF
        75: '#7700CC',  # Deep purple - 75% NMF
        90: '#550099',  # Very deep purple - 90% NMF
    }

    # RecoVar_PCA hybrid (RF + PCA) color map, keyed by dimred (PCA) share percentage.
    RecoVar_PCA_colors = {
        10: '#CCFF88',  # Very light lime - 10% PCA
        25: '#AAFF55',  # Light lime - 25% PCA
        50: '#77DD22',  # Vivid lime - 50% PCA
        75: '#55AA00',  # Deep lime green - 75% PCA
        90: '#338800',  # Very deep lime green - 90% PCA
    }

    # Dimred-only color map: DISTINCT from hybrid strategies. One colour per dimred type.
    dimred_only_colors = {
        'nmf': '#cc0066',  # Dark pink
        'pca': '#006600',  # Dark forest green
    }

    # Gap-filling strategy markers
    gap_filling_markers = {
        'DEG-based-filling': 's',                    # Square
        'cell-type-specific-filling': 'D',           # Diamond
        'global-gene-filling': '^',                  # Triangle up
        None: 'o',                                   # Circle (no filling)
    }
    
    # Ratio-specific markers for hybrid strategies (RecoVar, RecoVar_PCA)
    # Based on dimred_ratio (NMF or PCA component share)
    ratio_markers = {
        0.25: 'o',      # Circle - 25% dimred (75% RF)
        0.50: 's',      # Square - 50% dimred (50% RF)
        0.75: '^',      # Triangle - 75% dimred (25% RF)
    }
    
    # Determine marker strategy based on what varies in this plot
    try:
        marker_strategy = resolve_marker_strategy(dataset_names)
        logging.info(f"Resolved marker strategy: {marker_strategy}")
    except ValueError as e:
        # Incompatible grouping detected
        logging.error(str(e))
        raise

        
    # Process each dataset name
    for name in dataset_names:
        # Extract strategy name and gap-filling variant
        base_strategy, gap_filling_variant = extract_strategy_from_dataset_name(name)
        logging.info(f"Processing dataset '{name}' -> base_strategy='{base_strategy}', gap_filling_variant={gap_filling_variant}")
        
        # First check if this is an external panel
        # Match by checking if base_strategy is in the external panel name or vice versa
        is_external = False
        
        # DEBUG: Log external_names list
        logging.info(f"  external_names list has {len(external_names)} items: {external_names}")
        
        for ext_name in external_names:
            # Check both directions: exact match or substring match
            # This handles cases like:
            # - base_strategy='Spapros', ext_name='Spapros'
            # - base_strategy='Spapros', ext_name='Xenium-Filter_Spapros_100_mMulti-addon'
            # - base_strategy='mMulti_v1', ext_name='mMulti_v1'
            logging.info(f"    Checking external_name '{ext_name}' against base_strategy '{base_strategy}'")
            logging.info(f"      base_strategy==ext_name: {base_strategy == ext_name}")
            logging.info(f"      base_strategy in ext_name: {base_strategy in ext_name}")
            logging.info(f"      ext_name in base_strategy: {ext_name in base_strategy}")
            
            if base_strategy == ext_name or base_strategy in ext_name or ext_name in base_strategy:
                color_map[name] = external_color_map.get(ext_name, external_color_map.get(base_strategy, '#808080'))
                # Check if we have a dataset-specific marker (e.g., for Spapros with different sizes)
                # Try: dataset name first, then ext_name, then base_strategy, finally default
                marker_map[name] = external_marker_map.get(name, 
                                   external_marker_map.get(ext_name, 
                                   external_marker_map.get(base_strategy, 'o')))
                is_external = True
                logging.info(f"  ✓ Matched as external via external_names: {ext_name} -> color={color_map[name]}, marker={marker_map[name]}")
                break
        
        # DEBUG: Log check result
        logging.info(f"  After external_names loop: is_external={is_external}")
        
        # Also check if base_strategy directly matches a default external panel
        logging.info(f"  Checking default_external_colors: '{base_strategy}' in dict = {base_strategy in default_external_colors}")
        logging.info(f"  default_external_colors keys: {list(default_external_colors.keys())}")
        
        if not is_external and base_strategy in default_external_colors:
            color_map[name] = default_external_colors[base_strategy]
            # Check if we have a dataset-specific marker (e.g., for Spapros with different sizes)
            marker_map[name] = external_marker_map.get(name, external_markers.get(base_strategy, 'o'))
            is_external = True
            logging.info(f"  ✓ Matched as external via default_external_colors: {base_strategy} -> color={default_external_colors[base_strategy]}, marker={marker_map[name]}")
        
        if is_external:
            logging.info(f"  Continuing (is_external=True, color assigned)")
            continue

        # Check for simple benchmark strategies first
        if base_strategy in benchmark_colors:
            color_map[name] = benchmark_colors[base_strategy]
            # Use gap-filling marker if present, otherwise use benchmark marker
            if gap_filling_variant:
                marker_map[name] = gap_filling_markers.get(gap_filling_variant, 'o')
            else:
                marker_map[name] = benchmark_markers.get(base_strategy, 'o')
            continue

        # Check for hybrid strategies (RecoVar_* or RecoVar_PCA_*)
        if base_strategy.startswith('RecoVar_RF_') or base_strategy.startswith('RecoVar_PCA_RF_'):
            # Pattern: RecoVar(_PCA)?_RF_{rf_ratio}_Dimred_{dimred_ratio}
            dimred_type = 'pca' if base_strategy.startswith('RecoVar_PCA_RF_') else 'nmf'

            dimred_ratio = None
            m = re.search(r'Dimred_([\d.]+)', base_strategy)
            if m:
                try:
                    dimred_ratio = float(m.group(1))
                except ValueError:
                    pass

            # Colour keyed by dimred share percentage only.
            percentage_key = int(round(dimred_ratio * 100)) if dimred_ratio is not None else 50
            color_dict = RecoVar_colors if dimred_type == 'nmf' else RecoVar_PCA_colors
            if percentage_key in color_dict:
                color_map[name] = color_dict[percentage_key]
            else:
                color_map[name] = '#9933FF' if dimred_type == 'nmf' else '#77DD22'
                logging.warning(f"No color defined for {dimred_type} hybrid at {percentage_key}% share")

            # Assign marker based on resolved strategy
            if marker_strategy == 'gap_filling':
                marker_map[name] = gap_filling_markers.get(gap_filling_variant, 'o')
                logging.info(f"  Using gap-filling marker for '{name}': {marker_map[name]}")
            elif marker_strategy == 'ratio':
                if dimred_ratio in ratio_markers:
                    marker_map[name] = ratio_markers[dimred_ratio]
                    logging.info(f"  Using ratio marker for '{name}' (ratio={dimred_ratio}): {marker_map[name]}")
                else:
                    marker_map[name] = 'o'  # Default circle
                    logging.warning(f"  No ratio marker defined for ratio={dimred_ratio}, using circle")
            else:
                # marker_strategy == 'none' or fallback
                if dimred_ratio in ratio_markers:
                    marker_map[name] = ratio_markers[dimred_ratio]
                else:
                    marker_map[name] = gap_filling_markers.get(gap_filling_variant, 'o')
            continue

        # Check for dimred-only strategies (base_strategy is exactly 'nmf' or 'pca')
        if base_strategy in dimred_only_colors:
            color_map[name] = dimred_only_colors[base_strategy]
            # Assign marker based on gap-filling variant
            marker_map[name] = gap_filling_markers.get(gap_filling_variant, 'o')
            continue
            
        # Fallback: check if any benchmark color key is a substring
        matched = False
        for benchmark_key in benchmark_colors.keys():
            if benchmark_key in base_strategy:
                color_map[name] = benchmark_colors[benchmark_key]
                if gap_filling_variant:
                    marker_map[name] = gap_filling_markers.get(gap_filling_variant, 'o')
                else:
                    marker_map[name] = benchmark_markers.get(benchmark_key, 'o')
                matched = True
                break
        
        if matched:
            continue
            
        # Final fallback for unknown patterns - use gray and warn
        logging.warning(f"Unknown strategy pattern: '{base_strategy}' from dataset '{name}' - using default gray")
        logging.warning(f"  Debug: is_external={is_external}, in default_external_colors={base_strategy in default_external_colors}")
        logging.warning(f"  Debug: default_external_colors keys={list(default_external_colors.keys())}")
        color_map[name] = '#808080'  # Gray for unknown
        marker_map[name] = gap_filling_markers.get(gap_filling_variant, 'x')  # X marker for unknown
    
    return color_map, marker_map


##############################################################################
# UMAP representation
##############################################################################


def plot_umap_for_representation(adata, rep_name, dataset_name, output_dir, 
                                 dimensionality_reduction="pca", PNG_DPI=DEFAULT_PNG_DPI,
                                 celltype_col=None):
    """
    Generate and save UMAP plots for a given representation.
    
    Parameters:
    -----------
    adata : AnnData
        Processed AnnData object with UMAP coordinates
    rep_name : str
        Representation name ('pca' or 'nmf')
    dataset_name : str
        Name of the dataset for labeling
    output_dir : str
        Directory to save plots
    dimensionality_reduction : str
        Which dimensionality reduction was used: "pca", "nmf", or "both"
    PNG_DPI : int
        Resolution for saved figures
    celltype_col : str, optional
        Column name for cell type annotations

    Returns:
    --------
    list[str]
        Paths to the saved figures (one per colouring: Leiden clusters and, when
        ``celltype_col`` is present, cell-type annotations are saved as SEPARATE
        files). Empty list if plotting failed.
    """
    logging.info(f"Generating UMAP for {rep_name.upper()} representation")

    # Determine neighbor key
    if dimensionality_reduction == "both":
        neighbors_key = f"neighbors_{rep_name}"
    else:
        neighbors_key = None  # Use default

    # Compute UMAP for this representation
    try:
        sc.tl.umap(adata, neighbors_key=neighbors_key)

        # Store UMAP with representation-specific key if using "both" mode
        if dimensionality_reduction == "both":
            adata.obsm[f'X_umap_{rep_name}'] = adata.obsm['X_umap'].copy()

        if not (output_dir and os.path.exists(output_dir)):
            return []
        umap_dir = os.path.join(output_dir, 'umap_plots')
        os.makedirs(umap_dir, exist_ok=True)
        safe_name = dataset_name.replace('/', '_').replace(' ', '_') if dataset_name else 'dataset'

        # One separate figure per colouring.
        colourings = []
        if 'leiden' in adata.obs:
            colourings.append(('leiden', f'Leiden Clusters ({rep_name.upper()})', 'leiden'))
        if celltype_col and celltype_col in adata.obs:
            colourings.append((celltype_col, f'Cell Types ({rep_name.upper()})', celltype_col))
        elif celltype_col:
            logging.warning(f"celltype_col '{celltype_col}' not in adata.obs — skipping cell-type UMAP")

        saved = []
        for color_key, title, suffix in colourings:
            n_cat = 0
            try:
                n_cat = int(adata.obs[color_key].astype("category").cat.categories.size)
            except Exception:
                pass
            # Keep the scatter panel a fixed square; the legend gets its own space
            # to the right so a long cell-type list can't crush the embedding.
            fig, ax = plt.subplots(figsize=(8, 8))
            legend_fs = max(6, 11 - 0.28 * max(0, n_cat - 8))
            sc.pl.umap(
                adata, color=color_key, ax=ax, show=False, title=title,
                legend_loc="right margin", legend_fontsize=legend_fs, frameon=True,
            )
            # scanpy sets equal aspect on embeddings -> an elongated UMAP becomes a
            # thin strip. Let it fill its box instead.
            ax.set_aspect("auto")
            # Rebuild the legend as a single outside column (scanpy's multi-column
            # 'right margin' block is what eats the width).
            leg = ax.get_legend()
            if leg is not None:
                handles = list(leg.legend_handles if hasattr(leg, "legend_handles")
                               else leg.legendHandles)
                labels = [t.get_text() for t in leg.get_texts()]
                leg.remove()
                ncol = 1 if n_cat <= 30 else 2
                ax.legend(
                    handles, labels, loc="center left", bbox_to_anchor=(1.02, 0.5),
                    frameon=False, fontsize=legend_fs, ncol=ncol, markerscale=1.4,
                    handletextpad=0.4, columnspacing=0.8, borderaxespad=0.0,
                )
            fig.tight_layout()
            safe_suffix = str(suffix).replace('/', '_').replace(' ', '_')
            filepath = os.path.join(umap_dir, f'umap_{safe_name}_{rep_name}_{safe_suffix}.png')
            fig.savefig(filepath, dpi=PNG_DPI, bbox_inches='tight')
            plt.close(fig)
            logging.info(f"Saved UMAP plot to: {filepath}")
            saved.append(filepath)
        return saved

    except Exception as e:
        logging.error(f"Could not generate UMAP for {rep_name}: {e}")
        import traceback
        traceback.print_exc()
        return []


##############################################################################
# NEIGHBORHOOD PRESERVATION PLOTTING FUNCTIONS
##############################################################################

def plot_neighborhood_preservation_by_k(results_df, output_dir, PNG_DPI=DEFAULT_PNG_DPI, 
                                        color_map=None, marker_map=None, group_name=None):
    """
    Create line plot showing preservation scores across k values.
    Creates separate plots for PCA and NMF when both are present.
    
    Parameters:
    -----------
    results_df : DataFrame
        Results from evaluate_neighborhood_preservation()
    output_dir : str
        Directory to save plot
    PNG_DPI : int
        Resolution for saved figure
    color_map : dict, optional
        Dictionary mapping dataset names to colors
    marker_map : dict, optional
        Dictionary mapping dataset names to markers
    group_name : str, optional
        Plot group name for special color schemes (e.g., Category 9)
        
    Returns:
    --------
    list
        List of paths to saved figures
    """
    # Filter numeric k values for line plot
    numeric_results = results_df[results_df[COL_K] != 'optimal'].copy()

    # Keep only the dataset-level (global) rows. The neighborhood CSV also carries
    # per-cell-type rows (celltype populated) with the same (dataset, k) keys;
    # without this filter each dataset's line is strung through all ~N points per
    # k (global + one per cell type) as a single zig-zag polyline.
    if COL_CELLTYPE in numeric_results.columns:
        _ct = numeric_results[COL_CELLTYPE]
        numeric_results = numeric_results[
            _ct.isna() | _ct.astype(str).str.lower().isin(['', 'nan', 'none', 'global'])
        ].copy()

    if numeric_results.empty:
        logging.warning("No numeric k values found for plotting")
        return []

    # Draw each line in ascending-k order regardless of CSV row order.
    numeric_results = numeric_results.sort_values(
        COL_K, key=lambda s: pd.to_numeric(s, errors='coerce')
    )
    
    # Generate default color and marker maps if not provided
    if color_map is None or marker_map is None:
        dataset_names = list(numeric_results['dataset'].unique())
        default_color_map, default_marker_map = generate_method_specific_colors_and_markers(dataset_names, group_name=group_name)
        color_map = color_map or default_color_map
        marker_map = marker_map or default_marker_map
    
    # Check if we're using panel-size-based coloring by detecting multiple panel sizes
    import re
    panel_sizes = set()
    for dataset in numeric_results['dataset'].unique():
        size_match = re.search(r'_(\d+)(?:_|$)', dataset)
        if size_match:
            panel_sizes.add(int(size_match.group(1)))
    uses_size_coloring = len(panel_sizes) > 1
    
    # Check if we have multiple representations
    has_multiple_reps = 'representation' in numeric_results.columns and numeric_results['representation'].nunique() > 1
    
    saved_paths = []
    
    if has_multiple_reps:
        # Create separate plots for each representation (PCA and NMF)
        representations = sorted(numeric_results['representation'].unique())
        # Filter out 'both' - we only want to plot pca and nmf separately
        representations = [r for r in representations if r in ['pca', 'nmf']]
        
        for rep in representations:
            plt.figure(figsize=(14, 8))
            
            # Filter data for this representation
            rep_results = numeric_results[numeric_results['representation'] == rep]
            
            # Plot each dataset
            for dataset in rep_results['dataset'].unique():
                dataset_results = rep_results[rep_results['dataset'] == dataset]
                
                if not dataset_results.empty:
                    color = color_map.get(dataset, '#333333')
                    marker = marker_map.get(dataset, 'o')
                    line_style = _dataset_line_style(dataset)
                    # Extract display name for legend
                    import re
                    factor_range_mode = bool(re.search(r'_\d+factors_', dataset))
                    # Include panel size in label if using panel-size-based coloring
                    display_name = extract_display_name_from_dataset(
                        dataset,
                        factor_range_mode=factor_range_mode,
                        include_size=uses_size_coloring
                    )
                    plt.plot(
                        dataset_results['k'].astype(int), 
                        dataset_results['preservation_score'],
                        marker=marker,
                        linestyle=line_style,
                        linewidth=2.4,
                        markersize=8,
                        markeredgecolor='white',
                        markeredgewidth=1.0,
                        label=display_name,  # Use display name instead of full dataset name
                        color=color
                    )
            
            plt.xlabel('Number of Neighbors (k)', fontsize=14)
            plt.ylabel('Neighborhood Preservation Score', fontsize=14)
            plt.title(f'Jaccard similarity by k-value: Probe set vs full transcriptome (based on {rep.upper()}-embedding)', fontsize=16)
            plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
            plt.grid(True, alpha=0.3)
            
            # Save figure with representation suffix
            fig_path = os.path.join(output_dir, f'neighborhood_preservation_by_k_{rep}.png')
            plt.savefig(fig_path, dpi=PNG_DPI, bbox_inches='tight')
            plt.close()
            
            logging.info(f"Saved neighborhood preservation plot ({rep.upper()}) to: {fig_path}")
            saved_paths.append(fig_path)
            
    else:
        # Single representation - single plot
        plt.figure(figsize=(14, 8))
        
        for dataset in numeric_results['dataset'].unique():
            dataset_results = numeric_results[numeric_results['dataset'] == dataset]
            
            if not dataset_results.empty:
                color = color_map.get(dataset, '#333333')
                marker = marker_map.get(dataset, 'o')
                line_style = _dataset_line_style(dataset)
                # Extract display name for legend
                display_name = extract_display_name_from_dataset(dataset, include_size=uses_size_coloring)
                plt.plot(
                    dataset_results['k'].astype(int), 
                    dataset_results['preservation_score'],
                    marker=marker,
                    linestyle=line_style,
                    linewidth=2.4,
                    markersize=8,
                    markeredgecolor='white',
                    markeredgewidth=1.0,
                    label=display_name,  # Use display name instead of full dataset name
                    color=color
                )
        
        plt.xlabel('Number of Neighbors (k)', fontsize=14)
        plt.ylabel('Neighborhood Preservation Score', fontsize=14)
        single_rep = numeric_results['representation'].iloc[0].upper() if 'representation' in numeric_results.columns else 'PCA'
        plt.title(f'Jaccard similarity by k-value: Probe set vs full transcriptome (based on {single_rep}-embedding)', fontsize=16)
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.grid(True, alpha=0.3)
        
        # Save figure
        fig_path = os.path.join(output_dir, 'neighborhood_preservation_by_k.png')
        plt.savefig(fig_path, dpi=PNG_DPI, bbox_inches='tight')
        plt.close()
        
        logging.info(f"Saved neighborhood preservation line plot to: {fig_path}")
        saved_paths.append(fig_path)
    
    return saved_paths


def plot_neighborhood_preservation_celltype_heatmap(results_df, output_dir, PNG_DPI=DEFAULT_PNG_DPI):
    """Heatmap of per-cell-type kNN Jaccard preservation (cell types x k).

    ``evaluate_neighborhood_preservation`` writes, alongside the dataset-level
    rows, one row per (cell type, k) holding that cell type's mean kNN Jaccard
    between the probe-set and full-transcriptome embeddings. Those rows feed no
    other plot. This produces one heatmap per (geneset, representation): rows =
    cell types (sorted by mean Jaccard, descending), columns = k, colour =
    preservation score.

    Parameters
    ----------
    results_df : DataFrame
        Results from ``evaluate_neighborhood_preservation`` (needs a populated
        ``celltype`` column).
    output_dir : str
        Directory to save the heatmap(s).
    PNG_DPI : int
        Resolution for saved figures.

    Returns
    -------
    list
        Paths of the saved figures (empty if no per-cell-type rows are present).
    """
    if COL_CELLTYPE not in results_df.columns:
        logging.info("No 'celltype' column in neighborhood results -- skipping per-cell-type heatmap")
        return []

    df = results_df[results_df[COL_K] != 'optimal'].copy()
    _ct = df[COL_CELLTYPE]
    df = df[_ct.notna() & ~_ct.astype(str).str.lower().isin(['', 'nan', 'none', 'global'])].copy()
    if df.empty:
        logging.info("No per-cell-type neighborhood rows found -- skipping per-cell-type heatmap")
        return []

    df['_k_int'] = pd.to_numeric(df[COL_K], errors='coerce')
    df = df.dropna(subset=['_k_int'])
    if df.empty:
        logging.warning("No numeric k values in per-cell-type neighborhood rows")
        return []

    reps = sorted(df[COL_REPRESENTATION].unique()) if COL_REPRESENTATION in df.columns else [None]
    reps = [r for r in reps if r in ('pca', 'nmf')] or [None]
    datasets = list(df[COL_DATASET].unique()) if COL_DATASET in df.columns else [None]
    multi_ds = len(datasets) > 1

    saved_paths = []
    for rep in reps:
        rep_df = df if rep is None else df[df[COL_REPRESENTATION] == rep]
        rep_tag = f"_{rep}" if rep is not None else ""
        for ds in datasets:
            sub = rep_df if ds is None else rep_df[rep_df[COL_DATASET] == ds]
            if sub.empty:
                continue

            pivot = sub.pivot_table(
                index=COL_CELLTYPE, columns='_k_int',
                values=COL_PRESERVATION_SCORE, aggfunc='mean',
            )
            pivot = pivot.reindex(sorted(pivot.columns), axis=1)
            pivot = pivot.loc[pivot.mean(axis=1).sort_values(ascending=False).index]
            pivot.columns = [int(c) for c in pivot.columns]

            n_ct = pivot.shape[0]
            plt.figure(figsize=(10, max(6, n_ct * 0.42)))
            sns.heatmap(pivot, annot=True, cmap='viridis', fmt='.2f',
                        cbar_kws={'label': 'kNN Jaccard'})
            rep_title = rep.upper() if rep else 'PCA'
            ds_title = ""
            if ds is not None and multi_ds:
                ds_title = f" — {extract_display_name_from_dataset(ds)}"
            plt.title(f'Per-cell-type kNN Jaccard across k ({rep_title}){ds_title}', fontsize=15)
            plt.xlabel('Number of Neighbors (k)', fontsize=13)
            plt.ylabel('Cell type', fontsize=13)
            plt.tight_layout()

            ds_tag = ""
            if ds is not None and multi_ds:
                _safe = str(extract_display_name_from_dataset(ds)).replace('/', '_').replace(' ', '_')
                ds_tag = f"_{_safe}"
            out_path = os.path.join(
                output_dir, f'neighborhood_jaccard_by_celltype{ds_tag}{rep_tag}.png'
            )
            plt.savefig(out_path, dpi=PNG_DPI, bbox_inches='tight')
            plt.close()
            logging.info(f"Saved per-cell-type neighborhood Jaccard heatmap to: {out_path}")
            saved_paths.append(out_path)

    return saved_paths


##############################################################################
# CLUSTERING QUALITY PLOTTING FUNCTIONS
##############################################################################

def plot_clustering_quality_ari(results_df, output_dir, PNG_DPI=DEFAULT_PNG_DPI, 
                                 color_map=None, marker_map=None, 
                                 batch='', gene_set='', with_filter=False,
                                 dimensionality_reduction='pca', group_name=None):
    """
    Create enhanced line plots of ARI scores vs number of clusters with method-specific colors.
    This is the enhanced version that supports custom colors/markers and handles the format
    with 'metric', 'dim_reduction', 'n_clusters', 'score' columns.
    
    Parameters:
    -----------
    results_df : DataFrame
        Results from evaluate_clustering_quality() with columns:
        ['dataset', 'metric', 'dim_reduction', 'n_clusters', 'score'] OR
        ['dataset', 'n_clusters', 'ARI', 'representation'] (legacy format)
    output_dir : str
        Directory to save plot
    PNG_DPI : int, optional
        Resolution for saved figure
    color_map : dict, optional
        Dictionary mapping dataset names to colors
    marker_map : dict, optional
        Dictionary mapping dataset names to markers
    batch : str, optional
        Batch identifier for plot title
    gene_set : str, optional
        Gene set type for plot title
    with_filter : bool, optional
        Whether Xenium filter was applied
    dimensionality_reduction : str, optional
        Dimensionality reduction method used ('pca', 'nmf', or 'both')
        
    Returns:
    --------
    str
        Path to saved figure
    """
    if results_df.empty:
        logging.warning("No clustering quality results to plot")
        return None
    
    # Check data format - detect if we have new format (metric column) or legacy format (ARI column)
    has_metric_column = 'metric' in results_df.columns
    
    if has_metric_column:
        # New format: filter for ARI metric
        ari_df = results_df[results_df['metric'] == 'ARI'].copy()
    else:
        # Legacy format: assume 'ARI' column exists
        ari_df = results_df.copy()
        # Rename columns to match new format
        if 'ARI' in ari_df.columns:
            ari_df = ari_df.rename(columns={'ARI': 'score', 'representation': 'dim_reduction'})
        else:
            logging.error("Cannot find ARI or metric column in results_df")
            return None
    
    if ari_df.empty:
        logging.warning("No ARI results found to plot")
        return None
    
    # Generate default color and marker maps if not provided
    if color_map is None or marker_map is None:
        dataset_names = list(ari_df['dataset'].unique())
        default_color_map, default_marker_map = generate_method_specific_colors_and_markers(dataset_names, group_name=group_name)
        color_map = color_map or default_color_map
        marker_map = marker_map or default_marker_map
    
    # Get unique datasets
    dataset_names = list(ari_df['dataset'].unique())
    
    # Check if we have dim_reduction column with multiple dimensionality reduction methods
    has_dim_reduction = 'dim_reduction' in ari_df.columns
    if has_dim_reduction:
        dim_reduction_methods = sorted(ari_df['dim_reduction'].unique())
        # Filter out 'both' and any other non-standard values - we only want to plot pca and nmf separately
        dim_reduction_methods = [r for r in dim_reduction_methods if r in ['pca', 'nmf']]
    else:
        dim_reduction_methods = [dimensionality_reduction]
    
    # Create separate plot for each dimensionality reduction method
    saved_paths = []
    for dim_method in dim_reduction_methods:
        plt.figure(figsize=(14, 8))
        
        # Filter data for this dimensionality reduction method
        if has_dim_reduction:
            df_to_plot = ari_df[ari_df['dim_reduction'] == dim_method]
            rep_label = str(dim_method).upper()
        else:
            df_to_plot = ari_df
            rep_label = dimensionality_reduction.upper()
        
        # Check if we have multiple panel sizes - if so, include size in display names
        import re
        panel_sizes = set()
        for dataset in dataset_names:
            size_match = re.search(r'_(\d+)(?:_|$)', dataset)
            if size_match:
                panel_sizes.add(int(size_match.group(1)))
        
        include_size = len(panel_sizes) > 1
        if include_size:
            logging.info(f"Multiple panel sizes detected: {sorted(panel_sizes)} - including size in labels")
        
        # Plot every dataset
        for dataset in dataset_names:
            dataset_results = df_to_plot[df_to_plot['dataset'] == dataset]
            # Filter out NaN values
            numeric_clusters = dataset_results[dataset_results['n_clusters'].notna()]

            if not numeric_clusters.empty:
                color = color_map.get(dataset, '#333333')
                marker = marker_map.get(dataset, 'o')
                # Extract display name for legend
                factor_range_mode = bool(re.search(r'_\d+factors_', dataset))
                display_name = extract_display_name_from_dataset(dataset, factor_range_mode=factor_range_mode, include_size=include_size)
                plt.plot(
                    numeric_clusters['n_clusters'],
                    numeric_clusters['score'],
                    marker=marker,
                    linestyle='-',
                    label=display_name,  # Use display name instead of full dataset name
                    color=color,
                    linewidth=2,
                    markersize=6
                )

        plt.xlabel('Number of Clusters', fontsize=14)
        plt.ylabel('Adjusted Rand Index (ARI)', fontsize=14)
        plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
        
        # Create title with batch and gene_set info if provided
        title_parts = [f'Probe set vs full transcriptome (based on {rep_label}-embedding)']
        if batch:
            title_parts.append(f'Batch {batch}')
        if gene_set:
            filter_text = "(Xenium Filter)" if with_filter else "(No Filter)"
            title_parts.append(f'{gene_set} {filter_text}')
        plt.title(' - '.join(title_parts), fontsize=16)

        plt.grid(True, linestyle='--', alpha=0.7)

        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)
        plt.subplots_adjust(right=0.65)

        # Save figure
        filename_parts = ['clustering_quality_ari']
        if batch:
            filename_parts.append(batch)
        if gene_set:
            filename_parts.append(gene_set)
        if batch or gene_set:
            filename_parts.append("filter" if with_filter else "nofilter")
        filename_parts.append(dim_method)
        filename = '_'.join(filename_parts) + '.png'
        
        fig_path = os.path.join(output_dir, filename)
        plt.savefig(fig_path, dpi=PNG_DPI, bbox_inches='tight')
        plt.close()
        gc.collect()
        
        logging.info(f"Saved clustering quality ARI plot ({rep_label}) to {fig_path}")
        saved_paths.append(fig_path)
    
    return saved_paths[0] if len(saved_paths) == 1 else saved_paths


def plot_clustering_quality_nmi(results_df, output_dir, PNG_DPI=DEFAULT_PNG_DPI,
                                 color_map=None, marker_map=None,
                                 batch='', gene_set='', with_filter=False,
                                 dimensionality_reduction='pca', group_name=None):
    """
    Create enhanced line plots of NMI scores vs number of clusters with method-specific colors.
    This is the enhanced version that supports custom colors/markers and handles the format
    with 'metric', 'dim_reduction', 'n_clusters', 'score' columns.
    
    Parameters:
    -----------
    results_df : DataFrame
        Results from evaluate_clustering_quality() with columns:
        ['dataset', 'metric', 'dim_reduction', 'n_clusters', 'score'] OR
        ['dataset', 'n_clusters', 'NMI', 'representation'] (legacy format)
    output_dir : str
        Directory to save plot
    PNG_DPI : int, optional
        Resolution for saved figure
    color_map : dict, optional
        Dictionary mapping dataset names to colors
    marker_map : dict, optional
        Dictionary mapping dataset names to markers
    group_name : str, optional
        Plot group name for special color schemes (e.g., Category 9)
    batch : str, optional
        Batch identifier for plot title
    gene_set : str, optional
        Gene set type for plot title
    with_filter : bool, optional
        Whether Xenium filter was applied
    dimensionality_reduction : str, optional
        Dimensionality reduction method used ('pca', 'nmf', or 'both')
        
    Returns:
    --------
    str or list
        Path(s) to saved figure(s)
    """
    if results_df.empty:
        logging.warning("No clustering quality results to plot for NMI")
        return None
    
    # Check data format - detect if we have new format (metric column) or legacy format (NMI column)
    has_metric_column = 'metric' in results_df.columns
    
    if has_metric_column:
        # New format: filter for NMI metric
        nmi_df = results_df[results_df['metric'] == 'NMI'].copy()
    else:
        # Legacy format: assume 'NMI' column exists
        nmi_df = results_df.copy()
        # Rename columns to match new format
        if 'NMI' in nmi_df.columns:
            nmi_df = nmi_df.rename(columns={'NMI': 'score', 'representation': 'dim_reduction'})
        else:
            logging.error("Cannot find NMI or metric column in results_df")
            return None
    
    if nmi_df.empty:
        logging.warning("No NMI results found to plot")
        return None
    
    # Generate default color and marker maps if not provided
    if color_map is None or marker_map is None:
        dataset_names = list(nmi_df['dataset'].unique())
        default_color_map, default_marker_map = generate_method_specific_colors_and_markers(dataset_names, group_name=group_name)
        color_map = color_map or default_color_map
        marker_map = marker_map or default_marker_map
    
    # Get unique datasets
    dataset_names = list(nmi_df['dataset'].unique())
    
    # Check if we have dim_reduction column with multiple dimensionality reduction methods
    has_dim_reduction = 'dim_reduction' in nmi_df.columns
    if has_dim_reduction:
        dim_reduction_methods = sorted(nmi_df['dim_reduction'].unique())
        # Filter out 'both' and any other non-standard values - we only want to plot pca and nmf separately
        dim_reduction_methods = [r for r in dim_reduction_methods if r in ['pca', 'nmf']]
    else:
        dim_reduction_methods = [dimensionality_reduction]
    
    # Create separate plot for each dimensionality reduction method
    saved_paths = []
    for dim_method in dim_reduction_methods:
        plt.figure(figsize=(14, 8))
        
        # Filter data for this dimensionality reduction method
        if has_dim_reduction:
            df_to_plot = nmi_df[nmi_df['dim_reduction'] == dim_method]
            rep_label = str(dim_method).upper()
        else:
            df_to_plot = nmi_df
            rep_label = dimensionality_reduction.upper()
        
        # Check if we have multiple panel sizes - if so, include size in display names
        import re
        panel_sizes = set()
        for dataset in dataset_names:
            size_match = re.search(r'_(\d+)(?:_|$)', dataset)
            if size_match:
                panel_sizes.add(int(size_match.group(1)))
        
        include_size = len(panel_sizes) > 1
        if include_size:
            logging.info(f"Multiple panel sizes detected: {sorted(panel_sizes)} - including size in labels")
        
        # Plot every dataset
        for dataset in dataset_names:
            dataset_results = df_to_plot[df_to_plot['dataset'] == dataset]
            numeric_clusters = dataset_results[dataset_results['n_clusters'].notna()]

            if not numeric_clusters.empty:
                color = color_map.get(dataset, '#333333')
                marker = marker_map.get(dataset, 'o')
                line_style = _dataset_line_style(dataset)
                # Extract display name for legend
                factor_range_mode = bool(re.search(r'_\d+factors_', dataset))
                display_name = extract_display_name_from_dataset(dataset, factor_range_mode=factor_range_mode, include_size=include_size)
                plt.plot(
                    numeric_clusters['n_clusters'],
                    numeric_clusters['score'],
                    marker=marker,
                    linestyle=line_style,
                    label=display_name,  # Use display name instead of full dataset name
                    color=color,
                    linewidth=2.4,
                    markersize=8,
                    markeredgecolor='white',
                    markeredgewidth=1.0,
                )

        plt.xlabel('Number of Clusters', fontsize=14)
        plt.ylabel('Normalized Mutual Information (NMI)', fontsize=14)
        plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
        
        # Create title with batch and gene_set info if provided
        title_parts = [f'Probe set vs full transcriptome (based on {rep_label}-embedding)']
        if batch:
            title_parts.append(f'Batch {batch}')
        if gene_set:
            filter_text = "(Xenium Filter)" if with_filter else "(No Filter)"
            title_parts.append(f'{gene_set} {filter_text}')
        plt.title(' - '.join(title_parts), fontsize=16)

        plt.grid(True, linestyle='--', alpha=0.7)

        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)
        plt.subplots_adjust(right=0.65)

        # Save figure
        filename_parts = ['clustering_quality_nmi']
        if batch:
            filename_parts.append(batch)
        if gene_set:
            filename_parts.append(gene_set)
        if batch or gene_set:
            filename_parts.append("filter" if with_filter else "nofilter")
        filename_parts.append(dim_method)
        filename = '_'.join(filename_parts) + '.png'
        
        fig_path = os.path.join(output_dir, filename)
        plt.savefig(fig_path, dpi=PNG_DPI, bbox_inches='tight')
        plt.close()
        gc.collect()
        
        logging.info(f"Saved clustering quality NMI plot ({rep_label}) to {fig_path}")
        saved_paths.append(fig_path)
    
    return saved_paths[0] if len(saved_paths) == 1 else saved_paths


##############################################################################
# CELLTYPE IDENTIFICATION PLOTTING FUNCTIONS
##############################################################################

def plot_celltype_f1_heatmap(results_df, output_dir, PNG_DPI=DEFAULT_PNG_DPI):
    """
    Create a heatmap with celltypes as rows and probe panels (datasets) as columns
    showing F1-scores from the evaluation results.
    
    Parameters:
    -----------
    results_df : DataFrame
        Results from evaluate_celltype_identification() with columns:
        ['dataset', 'celltype', 'precision', 'recall', 'f1-score', 'support', 'accuracy']
    output_dir : str
        Directory to save plot
    PNG_DPI : int
        Resolution for saved figure
        
    Returns:
    --------
    str
        Path to saved figure
    """
    # Filter for rows that have celltype data (not the summary rows where celltype is NaN)
    celltype_data = results_df[results_df[COL_CELLTYPE].notna() & results_df[COL_F1_SCORE].notna()].copy()
    
    if celltype_data.empty:
        logging.warning("No celltype-specific F1-score data found!")
        return None
    
    logging.info(f"Datasets found: {sorted(celltype_data['dataset'].unique())}")
    logging.info(f"Celltypes found: {sorted(celltype_data['celltype'].unique())}")
    
    # Create mapping of original dataset names to display names for axis labels
    # Use extract_display_name_from_dataset to include ratio information
    import re
    
    # Check if we have multiple panel sizes - if so, include size in display names
    panel_sizes = set()
    for dataset in celltype_data['dataset'].unique():
        size_match = re.search(r'_(\d+)(?:_|$)', dataset)
        if size_match:
            panel_sizes.add(int(size_match.group(1)))
    
    include_size = len(panel_sizes) > 1
    if include_size:
        logging.info(f"Multiple panel sizes detected: {sorted(panel_sizes)} - including size in labels")
    
    dataset_display_names = {}
    for dataset in celltype_data['dataset'].unique():
        factor_range_mode = bool(re.search(r'_\d+factors_', dataset))
        display_name = extract_display_name_from_dataset(dataset, factor_range_mode=factor_range_mode, include_size=include_size)
        dataset_display_names[dataset] = display_name
    
    # Create pivot table: celltypes as rows (index), datasets as columns, f1-score as values
    heatmap_data = celltype_data.pivot_table(
        index='celltype',
        columns='dataset', 
        values='f1-score',
        aggfunc='first'  # Use first value if duplicates exist
    )
    
    # Rename columns to use display names
    heatmap_data = heatmap_data.rename(columns=dataset_display_names)
    
    # Sort celltypes by mean F1-score across all datasets (descending)
    # This puts the best-performing celltypes at the top
    heatmap_data['mean_f1'] = heatmap_data.mean(axis=1)
    heatmap_data = heatmap_data.sort_values('mean_f1', ascending=False)
    heatmap_data = heatmap_data.drop('mean_f1', axis=1)  # Remove helper column
    
    # Create the heatmap with appropriate figure size based on data dimensions
    n_celltypes = len(heatmap_data)
    n_datasets = len(heatmap_data.columns)
    
    # Scale figure size based on number of items
    fig_width = max(10, n_datasets * 0.8)
    fig_height = max(8, n_celltypes * 0.4)
    
    plt.figure(figsize=(fig_width, fig_height))
    
    # Create heatmap
    ax = sns.heatmap(
        heatmap_data,
        annot=True,           # Show F1-score values in cells
        fmt='.3f',            # Format to 3 decimal places
        cmap='viridis',       # Color scheme
        linewidths=0.5,       # Cell borders
        vmin=0,               # Minimum value for color scale
        vmax=1.0,             # Maximum value for color scale
        cbar_kws={'label': 'F1-Score'}
    )
    
    # Customize the plot
    plt.title('F1-Score per cell type', fontsize=14, pad=20)
    plt.xlabel('Probe Panel (Dataset)', fontsize=12, labelpad=10)
    plt.ylabel('Cell Type', fontsize=12, labelpad=10)
    
    # Rotate x-axis labels for better readability
    plt.xticks(rotation=45, ha='right', fontsize=9)
    plt.yticks(rotation=0, fontsize=9)
    
    # Adjust layout
    plt.tight_layout()
    
    # Save the heatmap
    heatmap_path = os.path.join(output_dir, 'celltype_f1score_heatmap.png')
    plt.savefig(heatmap_path, dpi=PNG_DPI, bbox_inches='tight')

    # Save the pivot table as CSV
    csv_output_path = os.path.join(output_dir, 'celltype_f1score_matrix.csv')
    heatmap_data.to_csv(csv_output_path)
    
    plt.close()
    
    logging.info(f"Heatmap saved to: {heatmap_path}")
    logging.info(f"Data matrix saved to: {csv_output_path}")
    logging.info(f"Heatmap dimensions: {n_celltypes} celltypes × {n_datasets} probe panels")
    
    return heatmap_path


# Palette matched to Benchmark_seed-analysis/aggregated/.../seedvar_clustering_*_ari.svg
_CELLTYPE_DIAG_MACRO_COLOR = '#42a5f5'     # blue      (ref plot's "RecoVar" series)
_CELLTYPE_DIAG_WEIGHTED_COLOR = '#00838f'  # teal      (ref plot's "Spapros" series)
_CELLTYPE_DIAG_ACCURACY_COLOR = '#1565c0'  # dark blue (ref plot's "NSForest" series)
_CELLTYPE_DIAG_REFLINE_COLOR = '#ad1457'   # magenta   (ref plot's "geneBasis" series)


def plot_celltype_classification_diagnostics_global(results_df, output_dir, PNG_DPI=DEFAULT_PNG_DPI):
    """
    Combined global (dataset-level, non-per-celltype) classification diagnostics:
    three side-by-side bar-chart panels -- Macro F1, Weighted F1, and Accuracy, one
    bar per geneset each -- as a single figure. Replaces the separate
    ``plot_celltype_accuracy_barchart()`` / ``plot_celltype_macro_weighted_f1_barchart()``.

    Parameters:
    -----------
    results_df : DataFrame
        Results from evaluate_celltype_identification(); dataset-level rows carry
        ``accuracy``, ``macro_f1``, ``weighted_f1``.
    output_dir : str
        Directory to save plot
    PNG_DPI : int
        Resolution for saved figure

    Returns:
    --------
    str
        Path to saved figure, or None if no dataset-level rows are found.
    """
    # Get dataset-level results (summary rows without celltype)
    dataset_results = results_df[results_df[COL_CELLTYPE].isna()].copy()

    if dataset_results.empty or 'weighted_f1' not in dataset_results.columns:
        logging.warning("No dataset-level celltype-classification results found for diagnostics plot")
        return None

    # Check if we have multiple panel sizes - if so, include size in display names
    import re
    panel_sizes = set()
    for dataset in dataset_results['dataset'].unique():
        size_match = re.search(r'_(\d+)(?:_|$)', dataset)
        if size_match:
            panel_sizes.add(int(size_match.group(1)))

    include_size = len(panel_sizes) > 1
    if include_size:
        logging.info(f"Multiple panel sizes detected: {sorted(panel_sizes)} - including size in labels")

    dataset_results['display_name'] = dataset_results['dataset'].apply(
        lambda x: extract_display_name_from_dataset(x, include_size=include_size)
    )
    # Single shared ordering (by macro_f1) so all three panels' bars line up per geneset.
    dataset_results_sorted = dataset_results.sort_values('macro_f1', ascending=False)

    x = np.arange(len(dataset_results_sorted))
    n = len(dataset_results_sorted)
    fig, axes = plt.subplots(1, 3, figsize=(max(10, n * 1.2) * 3, 8))

    panel_specs = [
        (axes[0], 'macro_f1', 'Macro F1', 'F1 Score', _CELLTYPE_DIAG_MACRO_COLOR, False),
        (axes[1], 'weighted_f1', 'Weighted F1', 'F1 Score', _CELLTYPE_DIAG_WEIGHTED_COLOR, False),
        (axes[2], 'accuracy', 'Accuracy', 'Classification Accuracy', _CELLTYPE_DIAG_ACCURACY_COLOR, True),
    ]
    for ax, col, title, ylabel, color, show_max_line in panel_specs:
        values = dataset_results_sorted[col]
        bars = ax.bar(x, values, color=color)
        for bar, v in zip(bars, values):
            ax.text(bar.get_x() + bar.get_width() / 2, v + 0.01, f'{v:.3f}', ha='center')

        if show_max_line:
            max_val = values.max()
            ax.axhline(
                y=max_val, linestyle='--', color=_CELLTYPE_DIAG_REFLINE_COLOR, alpha=0.7,
                label=f'Max Accuracy: {max_val:.3f}'
            )
            ax.legend()

        ax.set_xlabel('Geneset')
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.set_xticks(x)
        ax.set_xticklabels(dataset_results_sorted['display_name'], rotation=45, ha='right')
        ax.set_ylim(0, 1.05)

    fig.suptitle('Celltype Classification Diagnostics by Geneset', fontsize=13, fontweight='bold')
    fig.tight_layout()

    bar_path = os.path.join(output_dir, 'celltype_classification_diagnostics_global.png')
    fig.savefig(bar_path, dpi=PNG_DPI, bbox_inches='tight')
    plt.close(fig)

    logging.info(f"Saved combined celltype classification diagnostics to: {bar_path}")
    return bar_path


def plot_confusion_matrix(y_test, y_pred, class_names, dataset_name, accuracy, macro_f1,
                          output_dir, PNG_DPI=DEFAULT_PNG_DPI, normalize=None):
    """
    Create a confusion-matrix heatmap for celltype classification results.

    Parameters:
    -----------
    y_test, y_pred : array-like
        True and predicted celltype labels.
    class_names : list
        Class names (celltypes), in the order to display.
    dataset_name : str
        Name of the dataset (shortened to its method name via
        ``extract_display_name_from_dataset`` for the title; settings/seed/size stay
        in the output folder path, not the filename).
    accuracy, macro_f1 : float
        Overall accuracy and macro F1 (shown in the title).
    output_dir : str
        Directory to save the plot.
    PNG_DPI : int
        Resolution for the saved figure.
    normalize : {None, 'true'}, optional
        None  -> raw counts, integer annotations, file ``confusion_matrix.png``.
        'true' -> each row divided by its sum (recall / row-stochastic), 2-decimal
                  annotations, file ``confusion_matrix_normalized.png``.
                  Best for spotting *which* type a class is confused with, since
                  raw counts are dominated by the large classes.

    Returns:
    --------
    str
        Path to the saved figure.
    """
    from sklearn.metrics import confusion_matrix

    cm = confusion_matrix(y_test, y_pred, labels=class_names)
    if normalize == 'true':
        with np.errstate(all='ignore'):
            cm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
        cm = np.nan_to_num(cm)
        fmt, cbar_lbl, suffix = '.2f', 'fraction of true class', '_normalized'
    else:
        fmt, cbar_lbl, suffix = 'd', 'cells', ''
    cm_df = pd.DataFrame(cm, index=class_names, columns=class_names)

    n = len(class_names)
    plt.figure(figsize=(max(10, 0.7 * n + 3), max(8, 0.6 * n + 2)))
    sns.heatmap(cm_df, annot=True, fmt=fmt, cmap='Blues',
                cbar_kws={'label': cbar_lbl},
                vmin=0, vmax=(1.0 if normalize == 'true' else None))
    method_name = extract_display_name_from_dataset(dataset_name)
    plt.title(f'Confusion Matrix{" (row-normalised)" if normalize == "true" else ""} - {method_name}\n'
              f'Accuracy: {accuracy:.4f} | Macro F1: {macro_f1:.4f}')
    plt.ylabel('True Celltype')
    plt.xlabel('Predicted Celltype')
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    plt.tight_layout()

    # Settings/strategy info stays in the output folder path, not the filename.
    cm_path = os.path.join(output_dir, f'confusion_matrix{suffix}.png')
    plt.savefig(cm_path, dpi=PNG_DPI, bbox_inches='tight')
    plt.close()
    logging.info(f"Saved confusion matrix to: {cm_path}")
    return cm_path


def plot_celltype_class_sizes(class_counts, output_dir, dataset_name=None,
                              PNG_DPI=DEFAULT_PNG_DPI, log_scale=False):
    """
    Horizontal bar chart of the number of cells per class in a cell-type
    annotation column.

    Parameters:
    -----------
    class_counts : pandas.Series or dict
        celltype -> n_cells.
    output_dir : str
        Directory to save the plot (+ a matching ``.csv``).
    dataset_name : str, optional
        Shown in the title and prefixed to the filenames.
    PNG_DPI : int
        Resolution for the saved figure.
    log_scale : bool
        Log-scale the count axis (useful for very skewed class sizes).

    Returns:
    --------
    str
        Path to the saved figure.
    """
    s = pd.Series(class_counts).sort_values(ascending=True)
    total = int(s.sum())
    prefix = f'{dataset_name}_' if dataset_name else ''

    fig, ax = plt.subplots(figsize=(10, max(4, 0.45 * len(s) + 1.5)))
    bars = ax.barh(s.index.astype(str), s.values, color='#4C72B0', edgecolor='black', linewidth=0.5)
    for b, v in zip(bars, s.values):
        ax.text(b.get_width(), b.get_y() + b.get_height() / 2,
                f' {int(v):,} ({v / total * 100:.1f}%)', va='center', fontsize=9)
    if log_scale:
        ax.set_xscale('log')
    ax.set_xlabel('number of cells' + (' (log scale)' if log_scale else ''))
    ax.set_ylabel('cell type')
    ax.set_title(f'Cells per class{" - " + dataset_name if dataset_name else ""}  (n = {total:,})')
    ax.margins(x=0.15)
    fig.tight_layout()

    png = os.path.join(output_dir, f'{prefix}celltype_class_sizes.png')
    fig.savefig(png, dpi=PNG_DPI, bbox_inches='tight')
    plt.close(fig)
    s.sort_values(ascending=False).rename('n_cells').to_csv(
        os.path.join(output_dir, f'{prefix}celltype_class_sizes.csv'))
    logging.info(f"Saved cells-per-class bar chart to: {png}")
    return png


##############################################################################
# SIMPLY PLOT UMAP WITH GENE EXPRESSION OF EACH PROBE
##############################################################################

def create_feature_plots(ref_data, gene_lists, output_dir, logger, PNG_DPI=DEFAULT_PNG_DPI):
    """
    Create feature plots for each gene in each probeset to visualize expression patterns.
    
    Parameters:
    -----------
    ref_data : AnnData
        Reference dataset with all genes
    gene_lists : dict
        Dictionary of gene lists to visualize
    output_dir : str
        Base directory to save the feature plots
    logger : logging.Logger
        Logger instance
    PNG_DPI : int
        Resolution for saved PNG images (default: 300)
    """
    # Create directory for feature plots
    os.makedirs(output_dir, exist_ok=True)
    featureplots_dir = output_dir
    
    logging.info(f"Creating feature plots for genes in each probeset...")
    
    # Prepare UMAP embedding if not already computed
    if 'X_umap' not in ref_data.obsm:
        logging.info("Computing UMAP embedding for reference data...")
        try:
            sc.pp.neighbors(ref_data)
            sc.tl.umap(ref_data)
            logging.info("UMAP embedding computed successfully")
        except Exception as e:
            logging.error(f"Error computing UMAP embedding: {e}")
            return
    
    # Process only DT-NMF and XGB-NMF gene lists
    # Look for probeset names that contain decision tree or XGBoost methods with NMF ratios
    target_probesets = []
    for name in gene_lists.keys():
        # Target DT probesets with NMF ratios (e.g., "DT_Method_A_25-NMF_75-DEG_100")
        if name.startswith('DT_Method_') and ('NMF' in name):
            target_probesets.append(name)
        # Target XGB probesets with NMF ratios (if available)
        elif name.startswith('XGB_') and ('NMF' in name):
            target_probesets.append(name)
        # Also include legacy naming conventions
        elif name in ['dt_genes', 'xgb_genes']:
            target_probesets.append(name)
    
    if not target_probesets:
        logging.warning("No DT-NMF or XGB-NMF probesets found for feature plots")
        return
    
    logging.info(f"Found {len(target_probesets)} DT/XGB-NMF probesets for feature plots: {target_probesets}")
    
    # Process each target gene list
    for name in target_probesets:
        gene_list = gene_lists[name]
        logging.info(f"Creating feature plots for {name}...")
        
        # Create directory for this gene list
        geneset_dir = os.path.join(featureplots_dir, name)
        os.makedirs(geneset_dir, exist_ok=True)
        
        # Check if genes is an iterable and not a string
        if not hasattr(gene_list, '__iter__') or isinstance(gene_list, str) or isinstance(gene_list, sc.AnnData):
            logging.warning(f"Skipping {name} - not an iterable gene list: {type(gene_list)}")
            continue
        
        # Filter for genes that exist in the reference data
        valid_genes = [g for g in gene_list if g in ref_data.var_names]
        
        if len(valid_genes) != len(gene_list):
            logging.warning(f"Only {len(valid_genes)} out of {len(gene_list)} genes from {name} found in reference data")
        
        if not valid_genes:
            logging.warning(f"No valid genes found for {name}, skipping")
            continue
        
        # Cap the number of genes to plot to avoid memory issues (max 20 genes for feature plots)
        plot_genes = valid_genes[:100]
        if len(valid_genes) > 100:
            logging.warning(f"Limiting to first 100 genes for {name} to avoid memory issues and reduce processing time")
                
        # Create individual plots for each gene
        for i, gene in enumerate(plot_genes):
            try:
                plt.figure(figsize=(8, 6))
                sc.pl.umap(ref_data, color=gene, show=False, title=f"{gene} expression", size=40, color_map='viridis')
                plt.tight_layout()
                
                gene_path = os.path.join(geneset_dir, f"{name}_{gene}_featureplot.png")
                plt.savefig(gene_path, dpi=PNG_DPI, bbox_inches='tight')
                plt.close()
                
                # Log progress periodically
                if (i + 1) % 5 == 0 or i == len(plot_genes) - 1:
                    logging.info(f"Created feature plots for {i+1}/{len(plot_genes)} genes in {name}")
                    
            except Exception as e:
                logging.error(f"Error creating feature plot for gene {gene}: {e}")
                plt.close()  # Close the current figure
                continue
            
            # Force garbage collection every 5 plots
            if (i + 1) % 5 == 0:
                gc.collect()
    
    logging.info(f"Feature plots creation completed. Results saved to: {featureplots_dir}")


##############################################################################
# END OF PLOTTING MODULE
##############################################################################

if __name__ == '__main__':
    print("\n" + "="*80)
    print("ERROR: This is a plotting library module and cannot be run directly.")
    print("="*80)
    print("\nThis file contains plotting functions for assessment evaluation.")
    print("It must be imported by an evaluation script, not executed directly.\n")
    print("USAGE:")
    print("  1. Import this module in your evaluation script")
    print("  2. Call the plotting functions you need\n")
    print("Exported functions:")
    for func_name in __all__:
        print(f"  - {func_name}")
    print("\n" + "="*80 + "\n")
    import sys
    sys.exit(1)