"""NMF variability metrics plotting utilities.

This module contains plotting functions for visualizing NMF evaluation
metrics and variability across cell types and methods.

Includes:
- Aggregated celltype metrics (weighted vs macro comparison)
- Individual celltype evaluation results
- Combined plots with comprehensive method comparisons
"""

from __future__ import annotations

import logging
import os
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from _clustering_plots import extract_factor_number_from_dataset_name
# --- load THIS directory's _constants.py by path (sibling dirs share the name) ---
import importlib.util as _ilu, sys as _sys
from pathlib import Path as _cpath
_cspec = _ilu.spec_from_file_location("_constants", _cpath(__file__).resolve().parent / "_constants.py")
_sys.modules["_constants"] = _ilu.module_from_spec(_cspec)
_cspec.loader.exec_module(_sys.modules["_constants"])


from _constants import (
    COL_EXPVAR_TEST_PROBE,
    COL_MACRO_EXPVAR,
    COL_MACRO_MSE,
    COL_MSE_TEST_PROBE,
    COL_N_CELLS,
    COL_SKIPPED,
    COL_WEIGHTED_EXPVAR,
    COL_WEIGHTED_MSE,
    DEFAULT_PNG_DPI,
    METHOD_DISPLAY_NAMES,
    COL_EXPVAR_TEST_PROBE_RAW,
    COL_EXPVAR_TEST_PROBE_LOGNORM,
    COL_MSE_TEST_PROBE_RAW,
    COL_MSE_TEST_PROBE_LOGNORM,
    COL_WEIGHTED_MSE_RAW,
    COL_WEIGHTED_MSE_LOGNORM,
    COL_WEIGHTED_EXPVAR_RAW,
    COL_WEIGHTED_EXPVAR_LOGNORM,
    COL_MACRO_MSE_RAW,
    COL_MACRO_MSE_LOGNORM,
    COL_MACRO_EXPVAR_RAW,
    COL_MACRO_EXPVAR_LOGNORM,
    COL_WEIGHTED_MSE_BASELINE_RAW,
    COL_WEIGHTED_MSE_BASELINE_LOGNORM,
    COL_MACRO_MSE_BASELINE_RAW,
    COL_MACRO_MSE_BASELINE_LOGNORM,
    COL_WEIGHTED_EXPVAR_BASELINE_RAW,
    COL_WEIGHTED_EXPVAR_BASELINE_LOGNORM,
    COL_MACRO_EXPVAR_BASELINE_RAW,
    COL_MACRO_EXPVAR_BASELINE_LOGNORM,
)


def _method_display(method: str) -> str:
    """Display name for a variability method (e.g. 'PCA' -> 'PCA', 'ica' -> 'ICA'),
    for plot titles. Case-insensitive lookup, since the ``method`` string doubles as
    both a results-dict key / on-disk folder name (which may be any case, e.g. 'PCA'
    to match a user-requested output-folder convention) and this display purpose."""
    return METHOD_DISPLAY_NAMES.get(method.lower(), method.title())

logger = logging.getLogger(__name__)

# Presentation-friendly defaults for all plots generated by this module.
plt.rcParams.update(
    {
        "font.size": 16,
        "axes.titlesize": 20,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 14,
        "figure.titlesize": 22,
    }
)

__all__ = [
    "is_factor_range_mode",
    "get_factor_specific_colors",
    "extract_display_name_for_factor_range",
    "extract_strategy_and_display_name",
    "get_category_colors",
    "plot_aggregated_celltype_metrics",
    "plot_celltype_evaluation_results",
    "plot_ridge_aggregated_celltype_metrics",
    "create_combined_plot_with_info",
    "plot_expvar_gene_subset_breakdown",
    "plot_expvar_gene_subset_breakdown_by_celltype",
]

def is_factor_range_mode(evaluation_results):
    """
    Detect if evaluation results are from a factor-range analysis.
    Factor-range mode is identified by dataset names containing the pattern _Nfactors_
    
    Parameters:
    -----------
    evaluation_results : dict
        Dictionary containing evaluation results
        
    Returns:
    --------
    bool
        True if factor-range pattern is detected in any dataset name
    """
    if not evaluation_results:
        return False
    
    factor_pattern = re.compile(r'_(\d+)factors_')
    for probeset_name in evaluation_results.keys():
        if factor_pattern.search(probeset_name):
            return True
    return False


def get_factor_specific_colors():
    """
    Get factor-specific color palette for factor-range plots (factors 2-15).
    Returns the same 14-color gradient used in baseline plotting module.
    
    Returns:
    --------
    dict
        Dictionary mapping factor numbers (int) to color codes (str)
    """
    return {
        2: '#FF0000',      # Red
        3: '#FF8C00',      # Orange
        4: '#FFD700',      # Golden yellow
        5: '#9ACD32',      # Yellow-green
        6: '#00FF00',      # Green
        7: '#00FFFF',      # Cyan
        8: '#0000FF',      # Blue
        9: '#4169E1',      # Medium blue
        10: '#8B008B',     # Dark magenta
        11: '#800080',     # Purple
        12: '#FFC0CB',     # Pink
        13: '#FF1493',     # Deep pink
        14: '#8B4513',     # Saddle brown
        15: '#696969'      # Dim gray
    }


def extract_display_name_for_factor_range(probeset_name):
    """
    Extract display name for factor-range plots.
    Returns "N-factors" format when factor number is found, otherwise returns full strategy name.
    
    Parameters:
    -----------
    probeset_name : str
        Full probeset name
        
    Returns:
    --------
    str
        Display name ("N-factors" for factor-range, or strategy name)
    """
    # Try to extract factor number
    factor_num = extract_factor_number_from_dataset_name(probeset_name)
    if factor_num is not None:
        return f"{factor_num}-factors"
    
    # Fallback: use regular strategy extraction
    _, display_name = extract_strategy_and_display_name(probeset_name)
    return display_name


def extract_strategy_and_display_name(probeset_name, include_size=False):
    """
    Extract strategy category and display name from probeset name.
    
    Handles various naming patterns including fill-up strategies:
    - Simple external panels: Spapros, mMulti_v1, 5k (return simplified identifier)
    - Complex external panels: Any non-pipeline pattern (return full name)
    - Baselines: Random, HVG
    - Simple strategies: deg_only, rf_simple, rf_deg
    - Dimred-only: dimred_only_nmf_per_celltype (older Modules_v2: pca_global, nmf_per_celltype)
    - Hybrid: RecoVar_RF_0.5_Dimred_0.5, RecoVar_PCA_RF_0.25_Dimred_0.75
    - Fill-up variants: ..._DEG-based-filling, ..._cell-type-specific-filling, ..._global-gene-filling
    
    This function uses a generic approach to detect external panels:
    - Known panels (Spapros, 5k, mMulti) return simplified names
    - Unknown external panels (anything not matching pipeline patterns) return full names
    
    Parameters:
    -----------
    probeset_name : str
        Full probeset name (e.g., "Scanpy-Filter_All-Genes_nmf_per_celltype_100_5k-addon")
    include_size : bool, optional (default=False)
        If True, append panel size (e.g., " (100)") to display name
    
    Returns:
    --------
    tuple : (category, display_name)
        category: Strategy identifier for color mapping
        display_name: Human-readable display name for plots (includes filling suffix and size if requested)
    """
    import re
    
    # Helper function to add panel size to display name
    def add_panel_size(display_name, probeset_name):
        if include_size:
            panel_size_match = re.search(r'_(\d+)(?:_|$)', probeset_name)
            if panel_size_match:
                panel_size = panel_size_match.group(1)
                return f"{display_name} ({panel_size})"
        return display_name
    
    # Check for fill-up strategy suffix first
    filling_suffix = None
    filling_abbrev = {
        'DEG-based-filling': 'DEG-fill',
        'cell-type-specific-filling': 'CT-fill',
        'global-gene-filling': 'Global-fill'
    }
    
    # Store original probeset name for size extraction
    original_probeset_name = probeset_name
    
    for full_suffix, abbrev in filling_abbrev.items():
        if probeset_name.endswith(f"_{full_suffix}") or f"_{full_suffix}_" in probeset_name:
            filling_suffix = abbrev
            # Strip suffix for strategy detection
            probeset_name = probeset_name.replace(f"_{full_suffix}", "")
            break
    
    # === CATEGORY A: Simple standalone external panels (exact match) ===
    if probeset_name == '5k':
        return '5k', add_panel_size('5k', original_probeset_name)
    if probeset_name == 'mMulti_v1' or probeset_name == 'mMulti':
        return 'mMulti_v1', add_panel_size('mMulti_v1', original_probeset_name)
    if probeset_name == 'Spapros' or probeset_name == 'spapros':
        return 'Spapros', add_panel_size('Spapros', original_probeset_name)
    
    # === CATEGORY A: Known panels in compound names (simplified identifier) ===
    # Check for Spapros - only if it's the strategy, not part of addon
    if ('Spapros' in probeset_name or 'spapros' in probeset_name) and not probeset_name.endswith('Spapros-addon') and not probeset_name.endswith('spapros-addon'):
        # Check if Spapros is in the strategy position (index 2 when split by '_')
        parts_check = probeset_name.split('_')
        if len(parts_check) > 2 and ('Spapros' in parts_check[1:3] or 'spapros' in parts_check[1:3]):
            return 'Spapros', add_panel_size('Spapros', original_probeset_name)
    
    # Don't match '5k-addon' or 'mMulti-addon' suffixes as strategies
    # Only match if they appear in the middle of the name
    if '_5k_' in probeset_name and not probeset_name.endswith('5k-addon'):
        return '5k', add_panel_size('5k', original_probeset_name)
    
    # Check for baselines (both uppercase and lowercase). Both a leading-underscore
    # substring match and a bare leading-token match are needed: pipeline naming
    # conventions differ on whether the strategy is the first path/name segment
    # (e.g. "RecoVar_raw_rf0.5_..." from audit3_validation-style runs, no leading
    # underscore) or an interior one (e.g. "Scanpy-Filter_All-Genes_rf_deg_100").
    if ('_Random_' in probeset_name or '_random_' in probeset_name
            or probeset_name.startswith('Random_') or probeset_name.startswith('random_')
            or probeset_name == 'Random' or probeset_name == 'random'):
        return 'Random', add_panel_size('Random', original_probeset_name)
    if ('_HVG_' in probeset_name or '_hvg_' in probeset_name
            or probeset_name.startswith('HVG_') or probeset_name.startswith('hvg_')
            or probeset_name == 'HVG' or probeset_name == 'hvg'):
        return 'HVG', add_panel_size('HVG', original_probeset_name)

    # Check for simple strategies
    if '_deg_only_' in probeset_name or probeset_name.startswith('deg_only_') or probeset_name == 'deg_only':
        display_name = 'DEG Only'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'deg_only', add_panel_size(display_name, original_probeset_name)
    if '_rf_simple_' in probeset_name or probeset_name.startswith('rf_simple_') or probeset_name == 'rf_simple':
        display_name = 'RF Simple'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'rf_simple', add_panel_size(display_name, original_probeset_name)
    if '_rf_deg_' in probeset_name or probeset_name.startswith('rf_deg_') or probeset_name == 'rf_deg':
        display_name = 'RF+DEG'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'rf_deg', add_panel_size(display_name, original_probeset_name)

    # Check for hybrid strategies (RecoVar / RecoVar_PCA): RF share + dimred share.
    # Checked before the dimred-only / simple-literal matches so the '_RecoVar_'
    # substring inside a hybrid name is not mistaken for the bare 'RecoVar' strategy.
    hybrid_pattern = r'RecoVar(_PCA)?_RF_([\d.]+)_Dimred_([\d.]+)'
    hybrid_match = re.search(hybrid_pattern, probeset_name)
    if hybrid_match:
        pca_flag, rf_ratio, dimred_ratio = hybrid_match.groups()
        percentage = int(round(float(dimred_ratio) * 100))
        prefix = 'RecoVar_PCA' if pca_flag else 'RecoVar'
        # Category (colour-dict key) and display name are both keyed by dimred share.
        category = f"{prefix}_{percentage}"
        display_name = f"{prefix} {percentage}%"
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return category, add_panel_size(display_name, original_probeset_name)

    # Bare RecoVar / RecoVar_PCA (no ratio segment) — checked after the hybrid pattern.
    # Leading-token match (startswith/exact) covers names where RecoVar is the first
    # segment (e.g. "RecoVar_raw_rf0.5_nmf0.5_LCA_500genes_seed42"), not just where
    # it's bounded by underscores on both sides.
    if ('_RecoVar_PCA_' in probeset_name or probeset_name.startswith('RecoVar_PCA_')
            or probeset_name == 'RecoVar_PCA'):
        display_name = 'RecoVar_PCA'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'RecoVar_PCA', add_panel_size(display_name, original_probeset_name)
    if ('_RecoVar_' in probeset_name or probeset_name.startswith('RecoVar_')
            or probeset_name == 'RecoVar'):
        display_name = 'RecoVar'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'RecoVar', add_panel_size(display_name, original_probeset_name)

    # Check for dimred-only strategies. RecoVar emits 'dimred_only_{nmf,pca}_per_celltype';
    # older Modules_v2 names were '{nmf,pca}_{global,per_celltype}' with an optional
    # trailing _method_a/_method_b. Only the dimred token (nmf / pca) is meaningful now.
    dimred_only_pattern = r'_(?:dimred_only_)?(pca|nmf)_(?:global|per_celltype)(?:_method_[ab])?_'
    dimred_only_match = re.search(dimred_only_pattern, probeset_name)
    if dimred_only_match:
        dimred_type = dimred_only_match.group(1)
        display_name = dimred_type
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return dimred_type, add_panel_size(display_name, original_probeset_name)
    
    # === CATEGORY B: Generic external panel detection ===
    # If we reached here, check if this is an unknown external panel
    # External panels are anything that:
    # 1. Does NOT match any pipeline patterns
    # 2. Has multiple components (contains underscores)
    # 3. Is NOT an addon suffix
    
    pipeline_patterns = [
        'RecoVar_RF_', 'RecoVar_PCA_RF_',  # Hybrid strategies (checked above but included for clarity)
        'RecoVar',  # Bare RecoVar / RecoVar_PCA (checked above)
        'dimred_only', '_pca_', '_nmf_',  # Dimred-only (checked above)
    ]
    
    is_pipeline_pattern = any(pattern in probeset_name for pattern in pipeline_patterns)
    is_addon_suffix = probeset_name.endswith('-addon')
    has_multiple_parts = len(probeset_name.split('_')) >= 3
    
    # If it's not a pipeline pattern, not an addon, and has structure, it's likely an external panel
    if not is_pipeline_pattern and not is_addon_suffix and has_multiple_parts:
        # Check if probeset name contains any known external panel names
        # Extract the panel name as category for proper color mapping
        known_external_panels = ['NSForest', 'scMER', 'Spapros', 'mMulti_v1', '5k']
        
        for panel_name in known_external_panels:
            if f'_{panel_name}_' in probeset_name or probeset_name.endswith(f'_{panel_name}'):
                # Found a known external panel - use just the panel name for both category and display
                # This shows "NSForest" or "scMER" instead of the full filename
                display_name = panel_name
                if filling_suffix:
                    display_name = f"{display_name} ({filling_suffix})"
                return panel_name, add_panel_size(display_name, original_probeset_name)
        
        # If no known external panel found, return full probeset name as both category and display name
        # This preserves all information (filter, size, etc.) for unknown external panels
        # Examples: "Scanpy-Filter_HVG_UnknownTool_200", "No-Filter_All-Genes_CustomTool_100"
        display_name = probeset_name
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return probeset_name, add_panel_size(display_name, original_probeset_name)
    
    # Fallback for anything else
    display_name = probeset_name
    if filling_suffix:
        display_name = f"{display_name} ({filling_suffix})"
    
    return 'Other', add_panel_size(display_name, original_probeset_name)


def get_category_colors(external_names=None):
    """
    Get color mapping for different probe panel categories.
    Uses the same comprehensive color scheme as the baseline plotting module.
    UPDATED: Matches the new systematic color encoding from 20251009_Plotting-module_Clustering-knn-ct-class_HH.py
    
    Parameters:
    -----------
    external_names : list, optional
        List of external panel names (e.g., ['Spapros', 'mMulti_v1', '5k'])
        These will be assigned custom colors
    
    Returns:
    --------
    dict
        Dictionary mapping category names to color codes
    """
    # Initialize external_names if not provided
    if external_names is None:
        external_names = []
    
    # Base category colors - aligned with Clustering plotting module
    category_colors = {
        # Baseline/control strategies (both uppercase and lowercase)
        'Random': '#808080',         # Gray
        'random': '#808080',         # Gray (lowercase variant)
        'HVG': '#f0dd0d',            # Yellow
        'hvg': '#f0dd0d',            # Yellow (lowercase variant)
        
        # Simple strategies
        'deg_only': "#fa9c4a",       # Orange
        'rf_simple': "#d56a0d",      # Dark orange
        'rf_deg': "#875223",         # Brown

        # === DIMRED-ONLY STRATEGIES ===  one colour per dimred type
        'nmf': '#cc0066',            # Dark pink
        'pca': '#006600',            # Dark forest green

        # === RecoVar HYBRID (RF + NMF) ===  keyed by dimred (NMF) share, PURPLE family
        'RecoVar_10': '#DDAAFF',  # Very light purple
        'RecoVar_25': '#BB88FF',  # Light purple
        'RecoVar_50': '#9933FF',  # Vivid purple
        'RecoVar_75': '#7700CC',  # Deep purple
        'RecoVar_90': '#550099',  # Very deep purple

        # === RecoVar_PCA HYBRID (RF + PCA) ===  keyed by dimred (PCA) share, LIME-GREEN family
        'RecoVar_PCA_10': '#CCFF88',  # Very light lime
        'RecoVar_PCA_25': '#AAFF55',  # Light lime
        'RecoVar_PCA_50': '#77DD22',  # Vivid lime
        'RecoVar_PCA_75': '#55AA00',  # Deep lime green
        'RecoVar_PCA_90': '#338800',  # Very deep lime green

        'Other': '#7f7f7f'    # Gray
    }
    
    # Default colors for known external panels - aligned with Clustering plotting module
    default_external_colors = {
        'Spapros': "#957d06",
        'spapros': "#957d06",
        '10x_mMulti_v1': '#000000',  # Black - distinct from all other colors
        '10x_5k': '#000000',  # Black - distinct from all other colors
        'mMulti_v1': '#000000',      # Black - distinct from all other colors
        'mMulti': '#000000',
        '5k': '#000000',  # Black - distinct from all other colors
    }
    
    # Gradient for additional external panels - aligned with Clustering plotting module
    external_gradient = [
        "#76EFED",
        "#55AFAE",
        "#3E7C7B",
        "#203F3E",
        "#4C8098",
        "#1C4F66",
    ]
    
    # First, add all default external panel colors to category_colors
    # These are always available regardless of external_names parameter
    category_colors.update(default_external_colors)
    
    # Then, add colors for any additional external panels specified in external_names
    # that are not already in default_external_colors
    if external_names:
        logging.info(f"get_category_colors: external_names={external_names}")
        for idx, ext_name in enumerate(external_names):
            if ext_name not in category_colors:  # Only add if not already defined
                # Assign from gradient
                color = external_gradient[idx % len(external_gradient)]
                category_colors[ext_name] = color
                logging.info(f"  Added external color: {ext_name} → {color} (gradient index {idx})")
            else:
                logging.info(f"  Skipped {ext_name} (already in dict with color {category_colors[ext_name]})")
    
    logging.info(f"get_category_colors: returning {len(category_colors)} colors")
    logging.info(f"  External panel colors in result: {[(k, v) for k, v in category_colors.items() if k in (external_names or [])]}")
    
    return category_colors


def plot_aggregated_celltype_metrics(evaluation_results, plots_dir, title_suffix="", PNG_DPI=DEFAULT_PNG_DPI, external_names=None, group_name=None, methods=('nmf', 'mapping')):
    """
    Create plots showing weighted and macro aggregated evaluation metrics across all cell types.
    
    Plots the weighted and unweighted (macro) averages for MSE and explained variance
    across different probeset methods with baseline reference lines.
    
    Creates two plots per method:
    - Weighted and Macro MSE comparison
    - Weighted and Macro Explained Variance comparison
    
    FACTOR-RANGE MODE: When dataset names contain _Nfactors_, plots individual factors
    with factor-specific colors instead of aggregating by strategy.
    
    MULTI-SIZE MODE: When multiple panel sizes are detected (100, 200, 500), includes
    panel sizes in labels to plot them separately (e.g., "RecoVar 75% (100)").
    
    Parameters:
    -----------
    evaluation_results: dict
        Dictionary containing evaluation results with summary statistics
    plots_dir: str
        Directory to save plots
    title_suffix: str, optional (default="")
        Suffix to add to plot title
    PNG_DPI: int, optional
        DPI resolution for saved plots
    external_names: list, optional
        List of external panel names for custom coloring
    group_name: str, optional
        Plot group name (e.g., 'category-2') for special formatting
    methods: tuple of str, optional (default=('nmf', 'mapping'))
        Which methods' summary keys (``f'{method}_celltype_summary'`` /
        ``f'{method}_global_summary'``) to extract and plot, e.g. ``('nmf', 'pca', 'ica')``.
        Each name must match the key convention ``load_variability_results()`` /
        ``convert_variability_df_to_dict()`` use (the ``group_type`` string).

    Returns:
    --------
    plot_df: pandas.DataFrame or None
        DataFrame containing the aggregated data used for plotting, or None if no data available
    """
    if not evaluation_results:
        logging.warning("No evaluation results to plot")
        return None
    
    # Check if any results contain summary statistics
    has_summary_data = False
    for probeset_name, results in evaluation_results.items():
        if any(key.endswith('_summary') for key in results.keys()):
            has_summary_data = True
            break
    
    if not has_summary_data:
        logging.warning("No summary statistics found in evaluation data")
        return None
    
    # Detect factor-range mode
    factor_range_mode = is_factor_range_mode(evaluation_results)
    if factor_range_mode:
        logging.info("FACTOR-RANGE MODE DETECTED: Will plot individual factors with factor-specific colors")
    
    # Detect multiple panel sizes - if found, include size in labels to distinguish them
    panel_sizes_detected = set()
    size_pattern = re.compile(r'_(\d+)(?:_|$)')
    for probeset_name in evaluation_results.keys():
        size_match = size_pattern.search(probeset_name)
        if size_match:
            panel_sizes_detected.add(int(size_match.group(1)))
    include_size_in_labels = len(panel_sizes_detected) > 1
    if include_size_in_labels:
        logging.info(f"Multiple panel sizes detected: {sorted(panel_sizes_detected)} - including size in labels for separate plotting")
    
    # Extract summary statistics for plotting
    aggregated_data = []
    
    # DEBUG: Log what we're processing
    logging.info(f"Processing {len(evaluation_results)} probeset(s) for aggregated plots")
    
    for probeset_name, results in evaluation_results.items():
        # DEBUG: Log keys available for this probeset
        logging.debug(f"  {probeset_name}: keys = {list(results.keys())}")
        
        # Extract display name based on mode
        if factor_range_mode:
            display_name = extract_display_name_for_factor_range(probeset_name)
            # Extract factor number for color mapping
            factor_num = extract_factor_number_from_dataset_name(probeset_name)
            category = f"factor_{factor_num}" if factor_num else "unknown"
        else:
            # Use helper function to extract strategy and display name
            category, display_name = extract_strategy_and_display_name(probeset_name, include_size=include_size_in_labels)

        # Log the category assignment for debugging
        logging.info(f"  Probeset '{probeset_name}' → category='{category}', display='{display_name}'")
        
        # Per-method summary results (both celltype and global), e.g. nmf/pca/ica/mapping
        for method in methods:
            celltype_key = f'{method}_celltype_summary'
            global_key = f'{method}_global_summary'
            if celltype_key in results or global_key in results:
                summary_key = celltype_key if celltype_key in results else global_key
                summary = results[summary_key]
                logging.debug(f"    Found {summary_key}, type={type(summary)}, keys={list(summary.keys()) if isinstance(summary, dict) else 'N/A'}")
                if isinstance(summary, dict):
                    # Store factor number if in factor-range mode
                    factor_num = extract_factor_number_from_dataset_name(probeset_name) if factor_range_mode else None

                    for aggregation, mse_col, expvar_col in (
                        ('weighted', COL_WEIGHTED_MSE, COL_WEIGHTED_EXPVAR),
                        ('macro', COL_MACRO_MSE, COL_MACRO_EXPVAR),
                    ):
                        aggregated_data.append({
                            'probeset': probeset_name,
                            'probeset_display': display_name,
                            'category': category,
                            'method': method,
                            'aggregation': aggregation,
                            'mse': summary.get(mse_col, np.nan),
                            'mse_std': summary.get(f'{mse_col}_std', np.nan),
                            'expvar': summary.get(expvar_col, np.nan),
                            'expvar_std': summary.get(f'{expvar_col}_std', np.nan),
                            'mse_baseline': summary.get(f'{aggregation}_mse_test_baseline', np.nan),
                            'expvar_baseline': summary.get(f'{aggregation}_expvar_test_baseline', np.nan),
                            'factor_num': factor_num  # Add factor number for factor-range mode
                        })
            else:
                logging.debug(f"    No {method} summary found (has {list(results.keys())})")
    
    if not aggregated_data:
        logging.warning("No valid summary data found for plotting")
        return None
    
    # Convert to DataFrame
    plot_df = pd.DataFrame(aggregated_data)
    
    # DEBUG: Log what data we have
    logging.info(f"Aggregated data shape: {plot_df.shape}")
    logging.info(f"Methods: {plot_df['method'].unique()}")
    logging.info(f"Aggregation types: {plot_df['aggregation'].unique()}")
    logging.info(f"MSE values - NaN count: {plot_df['mse'].isna().sum()} / {len(plot_df)}")
    logging.info(f"ExpVar values - NaN count: {plot_df['expvar'].isna().sum()} / {len(plot_df)}")
    if not plot_df['mse'].isna().all():
        logging.info(f"MSE range: {plot_df['mse'].min():.2e} to {plot_df['mse'].max():.2e}")
    if not plot_df['expvar'].isna().all():
        logging.info(f"ExpVar range: {plot_df['expvar'].min():.4f} to {plot_df['expvar'].max():.4f}")
    
    # Get colors based on mode
    if factor_range_mode:
        logging.info("Using factor-specific colors for plotting")
        category_colors = get_factor_specific_colors()
        # Map factor_num to colors
        def get_color_for_row(row):
            if pd.notna(row['factor_num']):
                return category_colors.get(int(row['factor_num']), '#7f7f7f')
            return '#7f7f7f'
    else:
        logging.info(f"Calling get_category_colors with external_names={external_names}")
        category_colors = get_category_colors(external_names)
        logging.info(f"Received {len(category_colors)} category colors")
        logging.info(f"  Sample external colors: NSForest={category_colors.get('NSForest', 'NOT FOUND')}, scMER={category_colors.get('scMER', 'NOT FOUND')}")
        # Map category to colors
        def get_color_for_row(row):
            return category_colors.get(row['category'], '#7f7f7f')
    
    # Create combined plots for each requested method
    for method in methods:
        method_data = plot_df[plot_df['method'] == method].copy()

        if method_data.empty:
            continue

        # Create MSE plot - comparing weighted vs macro
        if not method_data['mse'].isna().all():
            logging.info(f"  Creating aggregated MSE plot for {method} ({len(method_data)} rows)")
            fig, axes = plt.subplots(1, 2, figsize=(20, max(8, len(method_data['probeset_display'].unique()) * 0.5)))
            
            for idx, aggregation_type in enumerate(['weighted', 'macro']):
                ax = axes[idx]
                agg_data = method_data[method_data['aggregation'] == aggregation_type].copy()
                
                if agg_data.empty:
                    continue
                
                # Sort by MSE (lower is better)
                agg_data = agg_data.sort_values('mse', ascending=True)

                y_pos = np.arange(len(agg_data))
                mse_vals = agg_data['mse'].to_numpy(dtype=float)
                mse_std = np.nan_to_num(agg_data.get('mse_std', np.nan).to_numpy(dtype=float), nan=0.0)
                ax.barh(
                    y=y_pos,
                    width=mse_vals,
                    xerr=mse_std,
                    color='lightblue',
                    edgecolor='#00008B',
                    linewidth=2,
                    ecolor='#1f2a44',
                    capsize=3,
                )
                ax.set_yticks(y_pos)
                ax.set_yticklabels(agg_data['probeset_display'].tolist())
                ax.invert_yaxis()
                
                # Add baseline reference line
                baseline_mse = agg_data['mse_baseline'].dropna().iloc[0] if not agg_data['mse_baseline'].dropna().empty else None
                if baseline_mse is not None and not np.isnan(baseline_mse):
                    ax.axvline(x=baseline_mse, color='red', linestyle='--',
                              label=f'Full NMF Baseline ({baseline_mse:.2e})', alpha=0.7)
                ax.legend(loc='lower right', fontsize=14)

                # Set title and labels
                ax.set_title(f'{_method_display(method)} MSE - {aggregation_type.title()} Average (lower is better)')
                ax.set_xlabel('MSE (lower is better)')
                ax.set_ylabel('Geneset')

            plt.suptitle(f'{_method_display(method)} MSE - Weighted vs Macro Comparison{title_suffix}', fontsize=20, y=1.00)
            plt.tight_layout()
            
            # Save MSE plot
            plot_filename = f"aggregated_{method}_mse_weighted_macro_comparison{title_suffix.replace(' ', '_').replace('/', '_')}.png"
            plot_path = os.path.join(plots_dir, plot_filename)
            plt.savefig(plot_path, dpi=PNG_DPI, bbox_inches='tight')
            plt.close()
            
            logging.info(f"Created aggregated MSE plot: {plot_filename}")
        else:
            logging.warning(f"  Skipping aggregated MSE plot for {method}: all MSE values are NaN")
        
        # Create Explained Variance plot - comparing weighted vs macro
        if not method_data['expvar'].isna().all():
            logging.info(f"  Creating aggregated ExpVar plot for {method} ({len(method_data)} rows)")
            fig, axes = plt.subplots(1, 2, figsize=(20, max(8, len(method_data['probeset_display'].unique()) * 0.5)))
            
            for idx, aggregation_type in enumerate(['weighted', 'macro']):
                ax = axes[idx]
                agg_data = method_data[method_data['aggregation'] == aggregation_type].copy()
                
                if agg_data.empty:
                    continue
                
                # Sort by explained variance (higher is better)
                agg_data = agg_data.sort_values('expvar', ascending=False)

                y_pos = np.arange(len(agg_data))
                exp_vals = agg_data['expvar'].to_numpy(dtype=float)
                exp_std = np.nan_to_num(agg_data.get('expvar_std', np.nan).to_numpy(dtype=float), nan=0.0)
                ax.barh(
                    y=y_pos,
                    width=exp_vals,
                    xerr=exp_std,
                    color='lightblue',
                    edgecolor='#00008B',
                    linewidth=2,
                    ecolor='#1f2a44',
                    capsize=3,
                )
                ax.set_yticks(y_pos)
                ax.set_yticklabels(agg_data['probeset_display'].tolist())
                ax.invert_yaxis()
                
                # Add baseline reference line
                baseline_expvar = agg_data['expvar_baseline'].dropna().iloc[0] if not agg_data['expvar_baseline'].dropna().empty else None
                if baseline_expvar is not None and not np.isnan(baseline_expvar):
                    ax.axvline(x=baseline_expvar, color='red', linestyle='--',
                              label=f'Full NMF Baseline ({baseline_expvar:.3f})', alpha=0.7)
                ax.legend(loc='lower right', fontsize=14)

                # Set title and labels
                ax.set_title(f'{_method_display(method)} Explained Variance - {aggregation_type.title()} Average (higher is better)')
                ax.set_xlabel('Explained Variance (higher is better)')
                ax.set_ylabel('Geneset')

            plt.suptitle(f'{_method_display(method)} Explained Variance - Weighted vs Macro Comparison{title_suffix}', fontsize=20, y=1.00)
            plt.tight_layout()
            
            # Save Explained Variance plot
            plot_filename = f"aggregated_{method}_expvar_weighted_macro_comparison{title_suffix.replace(' ', '_').replace('/', '_')}.png"
            plot_path = os.path.join(plots_dir, plot_filename)
            plt.savefig(plot_path, dpi=PNG_DPI, bbox_inches='tight')
            plt.close()
            
            logging.info(f"Created aggregated Explained Variance plot: {plot_filename}")
        else:
            logging.warning(f"  Skipping aggregated ExpVar plot for {method}: all ExpVar values are NaN")
    
    return plot_df


def plot_celltype_evaluation_results(evaluation_results, plots_dir, title_suffix="", PNG_DPI=DEFAULT_PNG_DPI, external_names=None, group_name=None, plot_celltype=True, methods=('nmf', 'mapping')):
    """
    Create combined plots showing celltype-specific evaluation results with all NMF:DEG ratios 
    and baseline methods in single plots with reference lines.
    
    Creates exactly one plot for MSE and one for explained variance per celltype per method.
    
    FACTOR-RANGE MODE: When dataset names contain _Nfactors_, plots individual factors
    with factor-specific colors instead of aggregating by strategy.
    
    MULTI-SIZE MODE: When multiple panel sizes are detected (100, 200, 500), includes
    panel sizes in labels to plot them separately (e.g., "RecoVar 75% (100)").
    
    Parameters:
    -----------
    evaluation_results: dict
        Dictionary containing evaluation results with celltype data
    plots_dir: str
        Directory to save plots
    title_suffix: str, optional (default="")
        Suffix to add to plot title
    PNG_DPI: int, optional
        DPI resolution for saved plots
    external_names: list, optional
        List of external panel names for custom coloring
    group_name: str, optional
        Plot group name (e.g., 'category-2') for special formatting
    plot_celltype: bool, optional (default=True)
        If False, skip creating individual celltype plots
    methods: tuple of str, optional (default=('nmf', 'mapping'))
        Which methods' celltype-results keys (``f'{method}_celltype_celltype_results'``)
        to extract and plot, e.g. ``('nmf', 'pca', 'ica')``.

    Returns:
    --------
    plot_df: pandas.DataFrame or None
        DataFrame containing the celltype data used for plotting, or None if no data available
    """
    if not evaluation_results:
        logging.warning("No evaluation results to plot")
        return None

    # Skip celltype plots if requested
    if not plot_celltype:
        logging.info("Skipping celltype-specific plots (plot_celltype=False)")
        return None

    # Check if any results contain celltype data
    has_celltype_data = False
    for probeset_name, results in evaluation_results.items():
        if any(
            key.startswith(f'{m}_celltype_celltype_results')
            for m in methods
            for key in results.keys()
        ):
            has_celltype_data = True
            break
    
    if not has_celltype_data:
        logging.warning("No celltype-specific results found in evaluation data")
        return None
    
    # Detect factor-range mode
    factor_range_mode = is_factor_range_mode(evaluation_results)
    if factor_range_mode:
        logging.info("FACTOR-RANGE MODE DETECTED: Will plot individual factors with factor-specific colors")
    
    # Detect multiple panel sizes - if found, include size in labels to distinguish them
    panel_sizes_detected = set()
    size_pattern = re.compile(r'_(\d+)(?:_|$)')
    for probeset_name in evaluation_results.keys():
        size_match = size_pattern.search(probeset_name)
        if size_match:
            panel_sizes_detected.add(int(size_match.group(1)))
    include_size_in_labels = len(panel_sizes_detected) > 1
    if include_size_in_labels:
        logging.info(f"Multiple panel sizes detected (celltype): {sorted(panel_sizes_detected)} - including size in labels for separate plotting")
    
    # Extract celltype results for plotting
    celltype_data = []
    
    for probeset_name, results in evaluation_results.items():
        # Extract display name based on mode
        if factor_range_mode:
            display_name = extract_display_name_for_factor_range(probeset_name)
            # Extract factor number for color mapping
            factor_num = extract_factor_number_from_dataset_name(probeset_name)
            category = f"factor_{factor_num}" if factor_num else "unknown"
        else:
            # Use helper function to extract strategy and display name
            category, display_name = extract_strategy_and_display_name(probeset_name, include_size=include_size_in_labels)

        # Per-method celltype results, e.g. nmf/pca/ica/mapping
        for method in methods:
            key = f'{method}_celltype_celltype_results'
            if key in results:
                celltype_results = results[key]
                if isinstance(celltype_results, dict):
                    for celltype, celltype_metrics in celltype_results.items():
                        if not celltype_metrics.get(COL_SKIPPED, False):
                            # Store factor number if in factor-range mode
                            factor_num = extract_factor_number_from_dataset_name(probeset_name) if factor_range_mode else None

                            celltype_data.append({
                                'probeset': probeset_name,
                                'probeset_display': display_name,
                                'category': category,
                                'celltype': celltype,
                                'method': method,
                                # Use absolute values
                                'mse': celltype_metrics.get(COL_MSE_TEST_PROBE, np.nan),
                                'expvar': celltype_metrics.get(COL_EXPVAR_TEST_PROBE, np.nan),
                                'mse_baseline': celltype_metrics.get('mse_test_baseline', np.nan),
                                'expvar_baseline': celltype_metrics.get('expvar_test_baseline', np.nan),
                                COL_N_CELLS: celltype_metrics.get(COL_N_CELLS, 0),
                                'factor_num': factor_num  # Add factor number for factor-range mode
                            })
    
    if not celltype_data:
        logging.warning("No valid celltype data found for plotting")
        return None
    
    # Convert to DataFrame
    plot_df = pd.DataFrame(celltype_data)
    
    # Get colors based on mode
    if factor_range_mode:
        logging.info("Using factor-specific colors for celltype plotting")
        category_colors = get_factor_specific_colors()
        # Map factor_num to colors
        def get_color_for_row(row):
            if pd.notna(row['factor_num']):
                return category_colors.get(int(row['factor_num']), '#7f7f7f')
            return '#7f7f7f'
    else:
        category_colors = get_category_colors(external_names)
        # Map category to colors
        def get_color_for_row(row):
            return category_colors.get(row['category'], '#7f7f7f')
    
    # Create combined plots for each requested method and celltype combination (2 plots total per celltype per method)
    for method in methods:
        method_data = plot_df[plot_df['method'] == method].copy()
        
        if method_data.empty:
            continue
        
        # Get unique celltypes
        celltypes = sorted(method_data['celltype'].unique())
        
        # Create plots for each celltype - MSE and Explained Variance combined
        for celltype in celltypes:
            celltype_data = method_data[method_data['celltype'] == celltype].copy()
            
            if celltype_data.empty:
                continue
            
            # Get baseline values (should be the same across all methods for this celltype)
            baseline_mse = celltype_data['mse_baseline'].dropna().iloc[0] if not celltype_data['mse_baseline'].dropna().empty else None
            baseline_expvar = celltype_data['expvar_baseline'].dropna().iloc[0] if not celltype_data['expvar_baseline'].dropna().empty else None
            
            # Create MSE plot
            if not celltype_data['mse'].isna().all():
                # Include factor_num column if in factor-range mode
                cols_to_select = ['probeset_display', 'category', 'mse']
                if factor_range_mode and 'factor_num' in celltype_data.columns:
                    cols_to_select.append('factor_num')
                mse_data = celltype_data[cols_to_select].copy()
                mse_data = mse_data.sort_values('mse', ascending=True)  # Lower is better for MSE
                
                plt.figure(figsize=(12, max(6, len(mse_data) * 0.4)))
                
                # Create barplot with lightblue fill and dark blue outline
                ax = sns.barplot(x='mse', y='probeset_display', data=mse_data, 
                                color='lightblue', edgecolor='#00008B', linewidth=2, dodge=False)

                
                # Add baseline reference line
                if baseline_mse is not None and not np.isnan(baseline_mse):
                    plt.axvline(x=baseline_mse, color='red', linestyle='--', 
                               label=f'Full NMF Baseline ({baseline_mse:.2e})', alpha=0.7)
                
                # Set title and labels
                ax.set_title(f'{_method_display(method)} MSE - {celltype} (lower is better){title_suffix}')
                ax.set_xlabel('MSE (lower is better)')
                ax.set_ylabel('Geneset')
                
                plt.tight_layout()
                
                # Save MSE plot
                safe_celltype = celltype.replace('/', '_').replace(' ', '_')
                plot_filename = f"celltype_{method}_mse_{safe_celltype}_combined{title_suffix.replace(' ', '_').replace('/', '_')}.png"
                plot_path = os.path.join(plots_dir, plot_filename)
                plt.savefig(plot_path, dpi=PNG_DPI, bbox_inches='tight')
                plt.close()
                
                logging.info(f"Created combined celltype MSE plot: {plot_filename}")
            
            # Create Explained Variance plot
            if not celltype_data['expvar'].isna().all():
                # Include factor_num column if in factor-range mode
                cols_to_select = ['probeset_display', 'category', 'expvar']
                if factor_range_mode and 'factor_num' in celltype_data.columns:
                    cols_to_select.append('factor_num')
                expvar_data = celltype_data[cols_to_select].copy()
                expvar_data = expvar_data.sort_values('expvar', ascending=False)  # Higher is better for explained variance
                
                plt.figure(figsize=(12, max(6, len(expvar_data) * 0.4)))
                
                # Create barplot with lightblue fill and dark blue outline
                ax = sns.barplot(x='expvar', y='probeset_display', data=expvar_data, 
                                color='lightblue', edgecolor='#00008B', linewidth=2, dodge=False)

                
                # Add baseline reference line
                if baseline_expvar is not None and not np.isnan(baseline_expvar):
                    plt.axvline(x=baseline_expvar, color='red', linestyle='--', 
                               label=f'Full NMF Baseline ({baseline_expvar:.3f})', alpha=0.7)
                
                # Set title and labels
                ax.set_title(f'{_method_display(method)} Explained Variance - {celltype} (higher is better){title_suffix}')
                ax.set_xlabel('Explained Variance (higher is better)')
                ax.set_ylabel('Geneset')
                
                plt.tight_layout()
                
                # Save Explained Variance plot
                safe_celltype = celltype.replace('/', '_').replace(' ', '_')
                plot_filename = f"celltype_{method}_expvar_{safe_celltype}_combined{title_suffix.replace(' ', '_').replace('/', '_')}.png"
                plot_path = os.path.join(plots_dir, plot_filename)
                plt.savefig(plot_path, dpi=PNG_DPI, bbox_inches='tight')
                plt.close()
                
                logging.info(f"Created combined celltype Explained Variance plot: {plot_filename}")
    
    return plot_df


def plot_ridge_aggregated_celltype_metrics(
    ridge_df,
    plots_dir,
    space,
    title_suffix="",
    PNG_DPI=DEFAULT_PNG_DPI,
    external_names=None,
    group_name=None,
):
    """Ridge aggregated weighted/macro MSE + ExpVar bar comparison for one space.

    Mirrors ``plot_aggregated_celltype_metrics``'s weighted|macro grouped-bar-chart
    layout, but reads Ridge's flat per-panel DataFrame directly (``celltype ==
    "summary"``, ``analysis_type == "per_celltype"`` rows) instead of the
    nmf/pca/ica-style nested ``"{method}_celltype_summary"`` dict, since Ridge's
    column-naming convention (``_raw``/``_lognorm`` suffix, ``mean_baseline`` not
    ``test_baseline``) doesn't fit that shape.

    v1 scope: only this aggregated weighted/macro comparison ships for Ridge —
    per-celltype bars, the global combined plot, and the gene-subset/expvar-mode
    grid are deferred.

    Args:
        ridge_df: Concatenated per-panel Ridge variability DataFrame (typically
            ``results['ridge']`` from ``load_variability_results()``). Column
            names may be either bare (per-fold CSVs) or ``_mean``/``_std``-suffixed
            (fold-aggregated CSVs); both are handled via a fallback lookup.
        plots_dir: Output directory (created if missing).
        space: ``"raw"`` or ``"lognorm"`` — which of Ridge's two spaces to plot.
        title_suffix: Appended to plot titles / filenames.
        PNG_DPI: Save resolution.
        external_names: Passed to ``extract_strategy_and_display_name`` for labels.
        group_name: Unused; accepted for call-site symmetry with the NMF/PCA/ICA
            plotting functions.

    Returns:
        plot_df: pandas.DataFrame with one row per (panel, aggregation) used for
            plotting, or ``None`` if no usable data was found.
    """
    if space not in ("raw", "lognorm"):
        raise ValueError(f"space must be 'raw' or 'lognorm', got {space!r}")
    if ridge_df is None or len(ridge_df) == 0:
        logging.warning("plot_ridge_aggregated_celltype_metrics: empty ridge_df — skipping")
        return None

    col_map = {
        "weighted_mse": COL_WEIGHTED_MSE_RAW if space == "raw" else COL_WEIGHTED_MSE_LOGNORM,
        "macro_mse": COL_MACRO_MSE_RAW if space == "raw" else COL_MACRO_MSE_LOGNORM,
        "weighted_expvar": COL_WEIGHTED_EXPVAR_RAW if space == "raw" else COL_WEIGHTED_EXPVAR_LOGNORM,
        "macro_expvar": COL_MACRO_EXPVAR_RAW if space == "raw" else COL_MACRO_EXPVAR_LOGNORM,
        "weighted_mse_baseline": COL_WEIGHTED_MSE_BASELINE_RAW if space == "raw" else COL_WEIGHTED_MSE_BASELINE_LOGNORM,
        "macro_mse_baseline": COL_MACRO_MSE_BASELINE_RAW if space == "raw" else COL_MACRO_MSE_BASELINE_LOGNORM,
        "weighted_expvar_baseline": COL_WEIGHTED_EXPVAR_BASELINE_RAW if space == "raw" else COL_WEIGHTED_EXPVAR_BASELINE_LOGNORM,
        "macro_expvar_baseline": COL_MACRO_EXPVAR_BASELINE_RAW if space == "raw" else COL_MACRO_EXPVAR_BASELINE_LOGNORM,
    }

    def _val(row, base_col):
        # Bare column first (per-fold CSVs), then _mean (fold-aggregated CSVs).
        for candidate in (base_col, f"{base_col}_mean"):
            if candidate in row.index and pd.notna(row[candidate]):
                try:
                    return float(row[candidate])
                except (TypeError, ValueError):
                    continue
        return np.nan

    def _std(row, base_col):
        candidate = f"{base_col}_std"
        if candidate in row.index and pd.notna(row[candidate]):
            try:
                return float(row[candidate])
            except (TypeError, ValueError):
                return np.nan
        return np.nan

    if "celltype" not in ridge_df.columns or "analysis_type" not in ridge_df.columns:
        logging.warning(
            "plot_ridge_aggregated_celltype_metrics: ridge_df missing 'celltype'/'analysis_type' — skipping"
        )
        return None
    summary_rows = ridge_df[
        (ridge_df["celltype"] == "summary") & (ridge_df["analysis_type"] == "per_celltype")
    ]
    if summary_rows.empty:
        logging.warning(
            "plot_ridge_aggregated_celltype_metrics: no celltype=='summary' rows found — skipping"
        )
        return None

    panel_col = "gene_list" if "gene_list" in summary_rows.columns else "dataset"

    rows = []
    for _, row in summary_rows.iterrows():
        panel_name = row.get(panel_col, row.get("dataset", "unknown"))
        _, display_name = extract_strategy_and_display_name(panel_name)
        for aggregation in ("weighted", "macro"):
            rows.append({
                "panel": panel_name,
                "probeset_display": display_name,
                "aggregation": aggregation,
                "mse": _val(row, col_map[f"{aggregation}_mse"]),
                "mse_std": _std(row, col_map[f"{aggregation}_mse"]),
                "expvar": _val(row, col_map[f"{aggregation}_expvar"]),
                "expvar_std": _std(row, col_map[f"{aggregation}_expvar"]),
                "mse_baseline": _val(row, col_map[f"{aggregation}_mse_baseline"]),
                "expvar_baseline": _val(row, col_map[f"{aggregation}_expvar_baseline"]),
            })

    plot_df = pd.DataFrame(rows)
    if plot_df.empty or (plot_df["mse"].isna().all() and plot_df["expvar"].isna().all()):
        logging.warning(f"plot_ridge_aggregated_celltype_metrics [{space}]: no usable data — skipping")
        return None

    os.makedirs(plots_dir, exist_ok=True)
    space_label = "Raw" if space == "raw" else "Lognorm"

    def _safe_filename_suffix():
        return (
            f"{title_suffix}_-_Ridge_{space_label}"
            .replace(" ", "_").replace("/", "_").replace("(", "").replace(")", "")
        )

    # MSE plot
    if not plot_df['mse'].isna().all():
        fig, axes = plt.subplots(1, 2, figsize=(20, max(8, len(plot_df['probeset_display'].unique()) * 0.5)))
        for idx, aggregation_type in enumerate(['weighted', 'macro']):
            ax = axes[idx]
            agg_data = plot_df[plot_df['aggregation'] == aggregation_type].copy()
            if agg_data.empty:
                continue
            agg_data = agg_data.sort_values('mse', ascending=True)
            y_pos = np.arange(len(agg_data))
            mse_vals = agg_data['mse'].to_numpy(dtype=float)
            mse_std = np.nan_to_num(agg_data['mse_std'].to_numpy(dtype=float), nan=0.0)
            ax.barh(y=y_pos, width=mse_vals, xerr=mse_std, color='lightblue',
                    edgecolor='#00008B', linewidth=2, ecolor='#1f2a44', capsize=3)
            ax.set_yticks(y_pos)
            ax.set_yticklabels(agg_data['probeset_display'].tolist())
            ax.invert_yaxis()
            baseline_mse = agg_data['mse_baseline'].dropna().iloc[0] if not agg_data['mse_baseline'].dropna().empty else None
            if baseline_mse is not None and not np.isnan(baseline_mse):
                ax.axvline(x=baseline_mse, color='red', linestyle='--',
                           label=f'Mean-Predictor Baseline ({baseline_mse:.2e})', alpha=0.7)
            ax.legend(loc='lower right', fontsize=14)
            ax.set_title(f'Ridge ({space_label}) MSE - {aggregation_type.title()} Average (lower is better)')
            ax.set_xlabel('MSE (lower is better)')
            ax.set_ylabel('Geneset')
        plt.suptitle(f'Ridge ({space_label}) MSE - Weighted vs Macro Comparison{title_suffix}', fontsize=20, y=1.00)
        plt.tight_layout()
        plot_filename = f"aggregated_ridge_mse_weighted_macro_comparison_{_safe_filename_suffix()}.png"
        plt.savefig(os.path.join(plots_dir, plot_filename), dpi=PNG_DPI, bbox_inches='tight')
        plt.close()
        logging.info(f"Created aggregated Ridge ({space}) MSE plot: {plot_filename}")
    else:
        logging.warning(f"  Skipping aggregated Ridge ({space}) MSE plot: all MSE values are NaN")

    # Explained Variance plot
    if not plot_df['expvar'].isna().all():
        fig, axes = plt.subplots(1, 2, figsize=(20, max(8, len(plot_df['probeset_display'].unique()) * 0.5)))
        for idx, aggregation_type in enumerate(['weighted', 'macro']):
            ax = axes[idx]
            agg_data = plot_df[plot_df['aggregation'] == aggregation_type].copy()
            if agg_data.empty:
                continue
            agg_data = agg_data.sort_values('expvar', ascending=False)
            y_pos = np.arange(len(agg_data))
            exp_vals = agg_data['expvar'].to_numpy(dtype=float)
            exp_std = np.nan_to_num(agg_data['expvar_std'].to_numpy(dtype=float), nan=0.0)
            ax.barh(y=y_pos, width=exp_vals, xerr=exp_std, color='lightblue',
                    edgecolor='#00008B', linewidth=2, ecolor='#1f2a44', capsize=3)
            ax.set_yticks(y_pos)
            ax.set_yticklabels(agg_data['probeset_display'].tolist())
            ax.invert_yaxis()
            baseline_expvar = agg_data['expvar_baseline'].dropna().iloc[0] if not agg_data['expvar_baseline'].dropna().empty else None
            if baseline_expvar is not None and not np.isnan(baseline_expvar):
                ax.axvline(x=baseline_expvar, color='red', linestyle='--',
                           label=f'Mean-Predictor Baseline ({baseline_expvar:.3f})', alpha=0.7)
            ax.legend(loc='lower right', fontsize=14)
            ax.set_title(f'Ridge ({space_label}) Explained Variance - {aggregation_type.title()} Average (higher is better)')
            ax.set_xlabel('Explained Variance (higher is better)')
            ax.set_ylabel('Geneset')
        plt.suptitle(f'Ridge ({space_label}) Explained Variance - Weighted vs Macro Comparison{title_suffix}', fontsize=20, y=1.00)
        plt.tight_layout()
        plot_filename = f"aggregated_ridge_expvar_weighted_macro_comparison_{_safe_filename_suffix()}.png"
        plt.savefig(os.path.join(plots_dir, plot_filename), dpi=PNG_DPI, bbox_inches='tight')
        plt.close()
        logging.info(f"Created aggregated Ridge ({space}) ExpVar plot: {plot_filename}")
    else:
        logging.warning(f"  Skipping aggregated Ridge ({space}) ExpVar plot: all ExpVar values are NaN")

    return plot_df


def create_combined_plot_with_info(classifier_type, gene_count, metric, results, output_dir,
                                   filter_type, gene_sel, PNG_DPI=DEFAULT_PNG_DPI, external_names=None, group_name=None):
    """
    Create a plot for a specific metric that includes all methods (HVG, Random, Spapros, and all NMF/DEG ratios).
    Plots are saved with evaluation method prefix to prevent overwriting between NMF and mapping strategies.
    
    MULTI-SIZE MODE: When multiple panel sizes are detected (100, 200, 500), includes
    panel sizes in labels to plot them separately (e.g., "RecoVar 75% (100)").
    
    Parameters:
    -----------
    classifier_type: str
        The classifier type (Basic-DT-classifier; XGBoost-classifier currently disabled)
    gene_count: int
        The gene count (100, 200, or 500)
    metric: str
        The metric to plot (nmf_mse, nmf_expvar, mapping_mse, mapping_expvar)
    results: dict
        Dictionary with metric data for different methods
    output_dir: str
        Directory to save the plot
    filter_type: str
        The filter type (With-Xenium-Filter or No-Xenium-Filter)
    gene_sel: str
        The gene selection method (all-genes or hvg)
    PNG_DPI: int, optional
        DPI resolution for saved plots
    external_names: list, optional
        List of external panel names for custom coloring
    group_name: str, optional
        Plot group name (e.g., 'category-2') for special formatting
        
    Note:
    -----
    Filename format: EvaluationMethod_metric_classifier_genecount_filter_geneselection.png
    Example: NMF_nmf_mse_Decision-tree_100genes_NoFilter_allgenes_25-NMF_75-DEG.png
    """
    # Skip if no data for this metric
    if not results or metric not in results or not results[metric]:
        logging.warning(f"No data for metric {metric} in {classifier_type} for gene count {gene_count}")
        return
    
    # Extract baseline values from the first available result (same for all probesets)
    baseline_value = None
    for method_data in results.values():
        if isinstance(method_data, dict):
            # Search for baseline values in any method's results
            for method_name, method_result in method_data.items():
                if isinstance(method_result, dict):
                    if metric == "nmf_mse" and "nmf_mse_test_baseline" in method_result:
                        baseline_value = method_result["nmf_mse_test_baseline"]
                        break
                    elif metric == "nmf_expvar" and "nmf_expvar_test_baseline" in method_result:
                        baseline_value = method_result["nmf_expvar_test_baseline"]
                        break
                    elif metric == "mapping_mse" and "mapping_mse_test_baseline" in method_result:
                        baseline_value = method_result["mapping_mse_test_baseline"]
                        break
                    elif metric == "mapping_expvar" and "mapping_expvar_test_baseline" in method_result:
                        baseline_value = method_result["mapping_expvar_test_baseline"]
                        break
            if baseline_value is not None:
                break
    
    # Prepare data for plotting
    plot_data = []
    
    # Detect factor-range mode by checking if any method name contains _Nfactors_
    factor_range_mode = any(re.search(r'_(\d+)factors_', method) for method in results[metric].keys())
    if factor_range_mode:
        logging.info("FACTOR-RANGE MODE DETECTED in global plots: Will plot individual factors")
    
    # Detect multiple panel sizes - if found, include size in labels to distinguish them
    panel_sizes_detected = set()
    size_pattern = re.compile(r'_(\d+)(?:_|$)')
    for method in results[metric].keys():
        size_match = size_pattern.search(method)
        if size_match:
            panel_sizes_detected.add(int(size_match.group(1)))
    include_size_in_labels = len(panel_sizes_detected) > 1
    if include_size_in_labels:
        logging.info(f"Multiple panel sizes detected (global): {sorted(panel_sizes_detected)} - including size in labels for separate plotting")
    
    for method, value in results[metric].items():
        # Extract display name based on mode
        if factor_range_mode:
            display_name = extract_display_name_for_factor_range(method)
            # Extract factor number for sorting
            factor_num = extract_factor_number_from_dataset_name(method)
            category = f"factor_{factor_num}" if factor_num else "unknown"
        else:
            # Use helper function to extract strategy and display name
            category, display_name = extract_strategy_and_display_name(method, include_size=include_size_in_labels)

        plot_data.append({
            'Method': method,
            'DisplayName': display_name,
            'Category': category,
            'Value': value,
            'FactorNum': extract_factor_number_from_dataset_name(method) if factor_range_mode else None
        })
    
    # Convert to DataFrame
    plot_df = pd.DataFrame(plot_data)
    
    # Skip if DataFrame is empty
    if plot_df.empty:
        logging.warning(f"No data to plot for {metric} in {classifier_type} for gene count {gene_count}")
        return
    
    # For MSE metrics, lower is better, so sort ascending
    # For explained variance metrics, higher is better, so sort descending
    # In factor-range mode, sort by factor number instead
    if factor_range_mode:
        plot_df = plot_df.sort_values('FactorNum', ascending=True)
    elif metric in ["mse", "nmf_mse", "mapping_mse"]:
        plot_df = plot_df.sort_values('Value', ascending=True)
    else:
        plot_df = plot_df.sort_values('Value', ascending=False)
    
    # Create barplot
    plt.figure(figsize=(12, max(6, len(plot_df) * 0.5)))
    
    # Create barplot with white fill and dark blue outline (no colored bars)
    ax = sns.barplot(x='Value', y='DisplayName', data=plot_df, 
                    color='lightblue', edgecolor='#00008B', linewidth=2, dodge=False)

    
    # Set title and labels based on metric type
    if metric == "nmf_mse":
        title = f"NMF MSE - {gene_count} genes"
        xlabel = "MSE (lower is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--',
                       label=f'Full NMF Baseline ({baseline_value:.2e})', alpha=0.7)
    elif metric == "nmf_expvar":
        title = f"NMF Explained Variance - {gene_count} genes"
        xlabel = "Explained Variance (higher is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--',
                       label=f'Full NMF Baseline ({baseline_value:.3f})', alpha=0.7)
    elif metric == "mapping_mse":
        title = f"Mapping MSE - {gene_count} genes"
        xlabel = "MSE (lower is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--', 
                       label=f'Full NMF Baseline ({baseline_value:.2e})', alpha=0.7)
    elif metric == "mapping_expvar":
        title = f"Mapping Explained Variance - {gene_count} genes"
        xlabel = "Explained Variance (higher is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--', 
                       label=f'Full NMF Baseline ({baseline_value:.3f})', alpha=0.7)
    # Legacy metrics
    elif metric == "mse":
        title = f"Mean Squared Error - {gene_count} genes"
        xlabel = "MSE (lower is better)"
    elif metric == "explained_variance":
        title = f"Explained Variance - {gene_count} genes"
        xlabel = "Explained Variance (higher is better)"
    else:
        title = f"{metric} - {gene_count} genes"
        xlabel = metric
    
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Geneset")
    plt.tight_layout()
    
    # Only show legend if baseline reference line exists (not for category colors)
    # For bar plots, we don't want to show category color legends - only the baseline reference line
    handles, labels = ax.get_legend_handles_labels()
    
    # Filter to only keep the baseline reference line in legend (if it exists)
    # Baseline lines have labels like 'Full NMF Baseline', 'Baseline', 'Ideal (No Gap)'
    baseline_labels = ['Full NMF Baseline', 'Baseline', 'Ideal (No Gap)']
    baseline_handles = []
    baseline_label_texts = []
    
    for handle, label in zip(handles, labels):
        # Check if this is a baseline line (contains these keywords)
        if any(bl in label for bl in baseline_labels):
            baseline_handles.append(handle)
            baseline_label_texts.append(label)
    
    # Only add legend if we have baseline reference lines
    if baseline_handles:
        plt.legend(handles=baseline_handles, labels=baseline_label_texts)
    
    # Create descriptive filename with all parameters
    # Format: evaluationmethod_metric_classifier_genecount_filter_geneselection.png
    classifier_name = "Decision-tree" if classifier_type == "Basic-DT-classifier" else "Unknown"
    filter_short = "WithFilter" if "With" in filter_type else "NoFilter"
    gene_sel_short = gene_sel.replace("-", "")
    
    # Determine evaluation method from metric name to avoid overwriting plots.
    # Generic split on the first "_" + _method_display() lookup, rather than a
    # hardcoded nmf_/mapping_ check -- the latter silently mis-routed PCA/ICA's
    # "PCA_mse"/"ICA_mse" metrics (capitalised, no underscore-prefix match) to
    # "Unknown_...png" instead of "PCA_...png"/"ICA_...png".
    metric_prefix, sep, metric_short = metric.partition("_")
    if sep:
        eval_method_prefix = _method_display(metric_prefix)
    else:
        eval_method_prefix = "Unknown"
        metric_short = metric
    
    # Create combined plot filename
    filename = f"{eval_method_prefix}_{metric_short}_{classifier_name}_{gene_count}genes_{filter_short}_{gene_sel_short}.png"
    plt.savefig(os.path.join(output_dir, filename), dpi=PNG_DPI)
    plt.close()
    
    logging.info(f"Created combined plot for {metric} with {gene_count} genes (all NMF:DEG ratios) in {output_dir}/{filename}")


# ---------------------------------------------------------------------------
# Gene-subset explained-variance breakdown (all-genes / panel-only / non-panel)
# ---------------------------------------------------------------------------

# scoring-time gene subsets emitted by Evaluation-module/nmf.py's expvar grid
_GENE_SUBSETS = ["all_genes", "panel_genes_only", "non_panel_genes_only"]
_GENE_SUBSET_LABEL = {
    "all_genes": "all genes",
    "panel_genes_only": "panel genes only",
    "non_panel_genes_only": "non-panel genes only",
}
_GENE_SUBSET_COLOR = {
    "all_genes": "#00008B",             # dark blue   — the blended number
    "panel_genes_only": "#FFFFFF",      # white       — genes the panel measures
    "non_panel_genes_only": "#D3D3D3",  # light grey  — the true generalization
}
# explained-variance aggregation modes (mirrors Evaluation-module/metrics.EXPVAR_MODES)
_EXPVAR_MODES = ["global_mean", "variance_weighted_sum", "mean", "median",
                 "expression_weighted_sum"]


def _gs_agg_prefix(agg):
    return "" if agg == "global" else f"{agg}_"


def _gs_probe_col(agg, subset, mode, suffix="mean"):
    return f"{_gs_agg_prefix(agg)}expvar_test_probe_{subset}_{mode}_{suffix}"


def _gs_baseline_col(agg, mode):
    # baseline is subset-agnostic (full-gene NMF oracle)
    return f"{_gs_agg_prefix(agg)}expvar_test_baseline_{mode}_mean"


def _gs_pick_row(panel_df, agg):
    if agg == "global":
        rows = panel_df[panel_df.get("analysis_type") == "global"]
    else:
        rows = panel_df[(panel_df.get("analysis_type") == "per_celltype")
                        & (panel_df.get("celltype") == "summary")]
    return rows.iloc[0] if not rows.empty else None


def _gs_val(row, col):
    if row is None or col not in row.index:
        return np.nan
    try:
        return float(row.get(col))
    except (TypeError, ValueError):
        return np.nan


def _gs_resolve_modes(nmf_df, expvar_modes):
    """Normalise the requested modes.

    ``expvar_modes=None`` -> auto-detect: only the modes whose columns are
    actually present in the CSV (i.e. only those the evaluation computed).
    An explicit list is honoured but still filtered to known mode names;
    modes requested but absent from the CSV are simply skipped later.
    """
    if expvar_modes:
        req = [expvar_modes] if isinstance(expvar_modes, str) else list(expvar_modes)
        return [m for m in req if m in _EXPVAR_MODES] or ["global_mean"]
    cols = set(getattr(nmf_df, "columns", []))
    present = [m for m in _EXPVAR_MODES
               if f"expvar_test_probe_all_genes_{m}_mean" in cols]
    if present:
        return present
    return ["global_mean"] if "expvar_test_probe" in cols else []


def plot_expvar_gene_subset_breakdown(
    nmf_df,
    plots_dir,
    title_suffix="",
    PNG_DPI=DEFAULT_PNG_DPI,
    expvar_modes=None,
    external_names=None,
    group_name=None,
):
    """Diagnostic: probe-reconstruction explained variance split by gene subset.

    For every panel it draws a grouped bar chart of ``expvar_test_probe`` for
    ``all_genes`` / ``panel_genes_only`` / ``non_panel_genes_only`` (a scoring-time
    column mask on the same reconstruction — no separate NMF fit), with the
    full-gene NMF oracle baseline as a red dashed reference. The
    ``non_panel_genes_only`` bar is the real generalization number: how much of
    the variance of genes the panel does *not* measure it can still recover.

    One figure per (aggregation level x explained-variance mode) is written:
      ``expvar_gene_subset_breakdown_{agg}_{mode}{suffix}.png``
    ``agg`` in ``global`` (``analysis_type == "global"`` row) and ``macro``
    (per-cell-type ``summary`` row, ``macro_expvar_test_probe_*``, when present).
    A ``mode`` is only plotted if the evaluation actually computed it (i.e. its
    ``expvar_test_probe_all_genes_<mode>_mean`` column exists) — with
    ``expvar_modes=None`` that set is auto-detected, so a default single-mode
    run yields just ``global_mean`` and a multi-mode run yields one figure each.

    Args:
        nmf_df: The concatenated per-panel NMF variability DataFrame
            (``results['nmf']`` in ``plot_evaluation.py``). Needs the raw
            ``expvar_test_probe_{subset}_{mode}_mean`` columns; degrades to a
            warning + skip when they are absent (e.g. an evaluation run that
            predates the ``--gene_subsets`` default).
        plots_dir: Output directory (created if missing).
        title_suffix: Appended to plot titles / filenames.
        PNG_DPI: Save resolution.
        expvar_modes: str or list from ``global_mean`` / ``variance_weighted_sum``
            / ``mean`` / ``median`` / ``expression_weighted_sum``. ``None``
            (default) auto-detects every mode the CSV contains.
        external_names: Passed to ``extract_strategy_and_display_name`` for
            labels (unused for colour here — colour encodes the gene subset).
        group_name: Unused; accepted for call-site symmetry.
    """
    if nmf_df is None or len(nmf_df) == 0 or "gene_list" not in getattr(nmf_df, "columns", []):
        logging.warning("plot_expvar_gene_subset_breakdown: empty / malformed nmf_df — skipping")
        return None

    modes = _gs_resolve_modes(nmf_df, expvar_modes)
    if not modes:
        logging.warning(
            "plot_expvar_gene_subset_breakdown: no explained-variance columns found — "
            "re-run run_evaluation.py (its --gene_subsets default now emits the subsets)"
        )
        return None

    os.makedirs(plots_dir, exist_ok=True)
    panels = list(dict.fromkeys(nmf_df["gene_list"].tolist()))
    include_size = len({m.group(1) for p in panels
                        for m in [re.search(r'_(\d+)(?:_|$)', p)] if m}) > 1
    safe_suffix = title_suffix.replace(" ", "_").replace("/", "_")

    any_drawn = False
    for mode in modes:
        for agg in ["global", "macro"]:
            rows = []
            for panel in panels:
                panel_df = nmf_df[nmf_df["gene_list"] == panel]
                row = _gs_pick_row(panel_df, agg)
                _, disp = extract_strategy_and_display_name(panel, include_size=include_size)
                baseline = _gs_val(row, _gs_baseline_col(agg, mode))
                if np.isnan(baseline) and agg == "global":
                    baseline = _gs_val(row, "expvar_test_baseline")  # legacy unsuffixed
                for subset in _GENE_SUBSETS:
                    val = _gs_val(row, _gs_probe_col(agg, subset, mode))
                    std = _gs_val(row, _gs_probe_col(agg, subset, mode, suffix="std"))
                    if np.isnan(val) and agg == "global" and subset == "all_genes" \
                            and mode == "global_mean":
                        val = _gs_val(row, "expvar_test_probe")       # legacy unsuffixed
                        std = _gs_val(row, "expvar_test_probe_std")
                    rows.append({"panel": panel, "display": disp, "subset": subset,
                                 "expvar": val, "std": std, "baseline": baseline})

            plot_df = pd.DataFrame(rows)
            good_panels = [p for p in panels
                           if not plot_df.loc[plot_df["panel"] == p, "expvar"].isna().all()]
            plot_df = plot_df[plot_df["panel"].isin(good_panels)]
            dropped = [p for p in panels if p not in good_panels]
            if dropped:
                logging.warning(
                    f"plot_expvar_gene_subset_breakdown [{agg}/{mode}]: no gene-subset "
                    f"expvar columns for {len(dropped)} panel(s) — skipped: {dropped[:3]}"
                )
            if plot_df.empty:
                logging.info(
                    f"plot_expvar_gene_subset_breakdown [{agg}/{mode}]: nothing to plot"
                )
                continue
            # the whole point is the breakdown — skip if only all_genes has data
            subset_only = plot_df[plot_df["subset"].isin(
                ["panel_genes_only", "non_panel_genes_only"])]
            if subset_only["expvar"].isna().all():
                logging.info(
                    f"plot_expvar_gene_subset_breakdown [{agg}/{mode}]: only all_genes "
                    "present (run evaluation with all 3 --gene_subsets — now default) — skipping"
                )
                continue

            def _short(s, n=24):
                return s if len(s) <= n else s[: n - 1] + "…"

            disp_names = [_short(plot_df.loc[plot_df["panel"] == p, "display"].iloc[0])
                          for p in good_panels]
            n_panels = len(good_panels)
            x = np.arange(n_panels)
            width = 0.8 / len(_GENE_SUBSETS)

            fig, ax = plt.subplots(figsize=(max(9, n_panels * 2.6 + 3.5), 6.5))
            for si, subset in enumerate(_GENE_SUBSETS):
                sub = (plot_df[plot_df["subset"] == subset]
                       .set_index("panel").reindex(good_panels))
                offs = x + (si - (len(_GENE_SUBSETS) - 1) / 2) * width
                vals = sub["expvar"].to_numpy(dtype=float)
                errs = np.nan_to_num(sub["std"].to_numpy(dtype=float), nan=0.0)
                ax.bar(offs, vals, width=width, yerr=errs, capsize=3,
                       color=_GENE_SUBSET_COLOR[subset], edgecolor="#333333",
                       linewidth=1.5, label=_GENE_SUBSET_LABEL[subset])
                for xi, v in zip(offs, vals):
                    if not np.isnan(v):
                        ax.annotate(f"{v:.2f}", (xi, v), textcoords="offset points",
                                    xytext=(0, 3), ha="center", va="bottom", fontsize=10)

            # per-panel full-NMF baseline (all genes) as a short dashed segment
            base_by_panel = (plot_df.groupby("panel")["baseline"].first()
                             .reindex(good_panels))
            for xi, b in zip(x, base_by_panel.to_numpy(dtype=float)):
                if not np.isnan(b):
                    ax.hlines(b, xi - 0.45, xi + 0.45, colors="red", linestyles="--",
                              linewidth=2, alpha=0.8,
                              label="full-NMF baseline (all genes)" if xi == 0 else None)

            ax.set_xticks(x)
            ax.set_xticklabels(disp_names, rotation=25, ha="right", fontsize=10)
            ax.set_xlim(-0.6, n_panels - 0.4)
            ax.set_ylabel(f"Explained variance ({mode})")
            ax.set_ylim(0, 1)
            agg_txt = "global" if agg == "global" else "macro (per-celltype avg)"
            ax.set_title(
                f"Explained variance by gene subset — {agg_txt} / {mode}{title_suffix}",
                fontsize=14,
            )
            ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.18),
                      ncol=len(_GENE_SUBSETS) + 1, fontsize=10, framealpha=0.9)
            ax.grid(axis="y", alpha=0.3)
            ax.text(0.015, 0.985,
                    "non-panel bar = variance recovered for genes the panel does NOT\n"
                    "measure (the true generalization)",
                    transform=ax.transAxes, ha="left", va="top",
                    fontsize=9, style="italic", color="#555555")

            out_path = os.path.join(
                plots_dir,
                f"expvar_gene_subset_breakdown_{agg}_{mode}{safe_suffix}.png",
            )
            fig.savefig(out_path, dpi=PNG_DPI, bbox_inches="tight")
            plt.close(fig)
            any_drawn = True
            logging.info(f"Created gene-subset expvar breakdown [{agg}/{mode}]: {out_path}")

    if not any_drawn:
        logging.warning(
            "plot_expvar_gene_subset_breakdown: no panel had panel/non-panel expvar "
            "columns — re-run run_evaluation.py (its --gene_subsets default now emits them)"
        )
    return None


def plot_expvar_gene_subset_breakdown_by_celltype(
    nmf_df,
    plots_dir,
    title_suffix="",
    PNG_DPI=DEFAULT_PNG_DPI,
    expvar_modes=None,
    external_names=None,
    group_name=None,
):
    """Per-cell-type version of :func:`plot_expvar_gene_subset_breakdown`.

    For each panel and each explained-variance mode present in the CSV, draws one
    figure: x-axis = cell types, three grouped bars per cell type
    (``all_genes`` / ``panel_genes_only`` / ``non_panel_genes_only``) of
    ``expvar_test_probe``, with each cell type's full-gene NMF oracle baseline as a
    short red dashed segment. Reads the ``analysis_type == "per_celltype"`` rows
    (excluding the ``summary`` row).

    Explained variance only — per-cell-type MSE for ``panel_genes_only`` runs
    ~50-60x the other subsets (panel genes are high-magnitude markers), so a
    shared-axis MSE bar chart is not informative; expvar (``1 - MSE/Var``)
    normalises that out.

    Args:
        nmf_df: ``results['nmf']`` DataFrame from
            ``plot_evaluation.py::load_variability_results``.
        plots_dir: Output directory (created if missing).
        title_suffix: Appended to titles / filenames.
        PNG_DPI: Save resolution.
        expvar_modes: str/list of modes, or ``None`` (default) to auto-detect
            every mode the CSV contains (see
            :func:`plot_expvar_gene_subset_breakdown`).
        external_names: Passed to ``extract_strategy_and_display_name`` for the
            panel title.
        group_name: Unused; accepted for call-site symmetry.
    """
    if nmf_df is None or len(nmf_df) == 0 or "gene_list" not in getattr(nmf_df, "columns", []):
        logging.warning(
            "plot_expvar_gene_subset_breakdown_by_celltype: empty / malformed nmf_df — skipping"
        )
        return None
    if "analysis_type" not in nmf_df.columns or "celltype" not in nmf_df.columns:
        logging.warning(
            "plot_expvar_gene_subset_breakdown_by_celltype: no analysis_type/celltype "
            "columns — skipping"
        )
        return None

    modes = _gs_resolve_modes(nmf_df, expvar_modes)
    if not modes:
        logging.warning(
            "plot_expvar_gene_subset_breakdown_by_celltype: no explained-variance "
            "columns found — re-run run_evaluation.py"
        )
        return None

    os.makedirs(plots_dir, exist_ok=True)
    ct_df = nmf_df[(nmf_df["analysis_type"] == "per_celltype")
                   & (nmf_df["celltype"] != "summary")]
    if ct_df.empty:
        logging.info(
            "plot_expvar_gene_subset_breakdown_by_celltype: no per-celltype rows — skipping"
        )
        return None

    panels = list(dict.fromkeys(ct_df["gene_list"].tolist()))
    include_size = len({m.group(1) for p in panels
                        for m in [re.search(r'_(\d+)(?:_|$)', p)] if m}) > 1
    safe_suffix = title_suffix.replace(" ", "_").replace("/", "_")

    any_drawn = False
    for mode in modes:
        for panel in panels:
            panel_df = ct_df[ct_df["gene_list"] == panel]
            _, disp = extract_strategy_and_display_name(panel, include_size=include_size)
            celltypes = sorted(panel_df["celltype"].dropna().unique().tolist())

            rows = []
            for ct in celltypes:
                row = panel_df[panel_df["celltype"] == ct].iloc[0]
                baseline = _gs_val(row, _gs_baseline_col("global", mode))
                if np.isnan(baseline):
                    baseline = _gs_val(row, "expvar_test_baseline_mean")  # global_mean fallback
                for subset in _GENE_SUBSETS:
                    rows.append({
                        "celltype": ct, "subset": subset,
                        "expvar": _gs_val(row, _gs_probe_col("global", subset, mode)),
                        "std": _gs_val(row, _gs_probe_col("global", subset, mode, suffix="std")),
                        "baseline": baseline,
                    })
            plot_df = pd.DataFrame(rows)

            good_ct = [c for c in celltypes
                       if not plot_df.loc[plot_df["celltype"] == c, "expvar"].isna().all()]
            plot_df = plot_df[plot_df["celltype"].isin(good_ct)]
            if plot_df.empty:
                continue
            subset_only = plot_df[plot_df["subset"].isin(
                ["panel_genes_only", "non_panel_genes_only"])]
            if subset_only["expvar"].isna().all():
                logging.info(
                    f"plot_expvar_gene_subset_breakdown_by_celltype [{mode}/{disp}]: "
                    "only all_genes present — skipping"
                )
                continue

            n_ct = len(good_ct)
            x = np.arange(n_ct)
            width = 0.8 / len(_GENE_SUBSETS)

            fig, ax = plt.subplots(figsize=(max(12, n_ct * 1.15 + 3), 7))
            for si, subset in enumerate(_GENE_SUBSETS):
                sub = (plot_df[plot_df["subset"] == subset]
                       .set_index("celltype").reindex(good_ct))
                offs = x + (si - (len(_GENE_SUBSETS) - 1) / 2) * width
                ax.bar(offs, sub["expvar"].to_numpy(dtype=float), width=width,
                       yerr=np.nan_to_num(sub["std"].to_numpy(dtype=float), nan=0.0),
                       capsize=2, color=_GENE_SUBSET_COLOR[subset], edgecolor="#333333",
                       linewidth=1.2, label=_GENE_SUBSET_LABEL[subset])

            base_by_ct = (plot_df.groupby("celltype")["baseline"].first().reindex(good_ct))
            for xi, b in zip(x, base_by_ct.to_numpy(dtype=float)):
                if not np.isnan(b):
                    ax.hlines(b, xi - 0.42, xi + 0.42, colors="red", linestyles="--",
                              linewidth=1.8, alpha=0.8,
                              label="full-NMF baseline (all genes)" if xi == 0 else None)

            ax.set_xticks(x)
            ax.set_xticklabels(
                [c if len(c) <= 22 else c[:21] + "…" for c in good_ct],
                rotation=35, ha="right", fontsize=9,
            )
            ax.set_xlim(-0.6, n_ct - 0.4)
            ax.set_ylabel(f"Explained variance ({mode})")
            ax.set_ylim(0, 1)
            ax.set_title(
                f"Explained variance by gene subset, per cell type — {mode}{title_suffix}\n"
                f"{disp}",
                fontsize=14,
            )
            ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.22),
                      ncol=len(_GENE_SUBSETS) + 1, fontsize=10, framealpha=0.9)
            ax.grid(axis="y", alpha=0.3)

            panel_safe = re.sub(r"[^\w.-]", "_", disp)[:60]
            out_path = os.path.join(
                plots_dir,
                f"expvar_gene_subset_by_celltype_{mode}__{panel_safe}{safe_suffix}.png",
            )
            fig.savefig(out_path, dpi=PNG_DPI, bbox_inches="tight")
            plt.close(fig)
            any_drawn = True
            logging.info(
                f"Created per-celltype gene-subset expvar breakdown [{mode}/{disp}]: {out_path}"
            )

    if not any_drawn:
        logging.warning(
            "plot_expvar_gene_subset_breakdown_by_celltype: no per-celltype panel/non-panel "
            "expvar columns — re-run run_evaluation.py (its --gene_subsets default emits them)"
        )
    return None
