"""NMF variability metrics plotting utilities.

This module contains plotting functions for visualizing NMF evaluation
metrics and variability across cell types and methods.

Includes:
- Aggregated celltype metrics (weighted vs macro comparison)
- Individual celltype evaluation results
- Combined plots with comprehensive method comparisons
"""

from __future__ import annotations

import logging
import os
import re
from typing import Any, Callable, Optional

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.lines import Line2D

from _clustering_plots import extract_factor_number_from_dataset_name
from _constants import (
    COL_EXPVAR_TEST_PROBE,
    COL_MACRO_EXPVAR,
    COL_MACRO_MSE,
    COL_MSE_TEST_PROBE,
    COL_N_CELLS,
    COL_RMSE_TEST_PROBE,
    COL_SKIPPED,
    COL_WEIGHTED_EXPVAR,
    COL_WEIGHTED_MSE,
    DEFAULT_PNG_DPI,
)

logger = logging.getLogger(__name__)

# Presentation-friendly defaults for all plots generated by this module.
plt.rcParams.update(
    {
        "font.size": 16,
        "axes.titlesize": 20,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 14,
        "figure.titlesize": 22,
    }
)

__all__ = [
    "is_factor_range_mode",
    "get_factor_specific_colors",
    "extract_display_name_for_factor_range",
    "generate_category_9_label",
    "extract_strategy_and_display_name",
    "get_category_colors",
    "plot_aggregated_celltype_metrics",
    "plot_celltype_evaluation_results",
    "create_combined_plot_with_info",
    "plot_standardized_comparison",
]

def is_factor_range_mode(evaluation_results):
    """
    Detect if evaluation results are from a factor-range analysis.
    Factor-range mode is identified by dataset names containing the pattern _Nfactors_
    
    Parameters:
    -----------
    evaluation_results : dict
        Dictionary containing evaluation results
        
    Returns:
    --------
    bool
        True if factor-range pattern is detected in any dataset name
    """
    if not evaluation_results:
        return False
    
    factor_pattern = re.compile(r'_(\d+)factors_')
    for probeset_name in evaluation_results.keys():
        if factor_pattern.search(probeset_name):
            return True
    return False


def get_factor_specific_colors():
    """
    Get factor-specific color palette for factor-range plots (factors 2-15).
    Returns the same 14-color gradient used in baseline plotting module.
    
    Returns:
    --------
    dict
        Dictionary mapping factor numbers (int) to color codes (str)
    """
    return {
        2: '#FF0000',      # Red
        3: '#FF8C00',      # Orange
        4: '#FFD700',      # Golden yellow
        5: '#9ACD32',      # Yellow-green
        6: '#00FF00',      # Green
        7: '#00FFFF',      # Cyan
        8: '#0000FF',      # Blue
        9: '#4169E1',      # Medium blue
        10: '#8B008B',     # Dark magenta
        11: '#800080',     # Purple
        12: '#FFC0CB',     # Pink
        13: '#FF1493',     # Deep pink
        14: '#8B4513',     # Saddle brown
        15: '#696969'      # Dim gray
    }


def extract_display_name_for_factor_range(probeset_name):
    """
    Extract display name for factor-range plots.
    Returns "N-factors" format when factor number is found, otherwise returns full strategy name.
    
    Parameters:
    -----------
    probeset_name : str
        Full probeset name
        
    Returns:
    --------
    str
        Display name ("N-factors" for factor-range, or strategy name)
    """
    # Try to extract factor number
    factor_num = extract_factor_number_from_dataset_name(probeset_name)
    if factor_num is not None:
        return f"{factor_num}-factors"
    
    # Fallback: use regular strategy extraction
    _, display_name = extract_strategy_and_display_name(probeset_name)
    return display_name


def generate_category_9_label(probeset_name):
    """
    Generate Category 9 specific label that includes filter setting + strategy.
    
    Format: {Filter}_{Strategy}
    - Filter: Scanpy-All-Genes, Scanpy-HVG, Xenium-All-Genes, Xenium-HVG
    - Strategy: dt_nmf_75%, dt_pca_75%
    
    Examples:
        'Scanpy-Filter_All-Genes_dt_nmf_DT0.25_Dimred0.75_...' → 'Scanpy-All-Genes_dt_nmf_75%'
        'Xenium-Filter_HVG-Subset_dt_pca_DT0.25_Dimred0.75_...' → 'Xenium-HVG_dt_pca_75%'
    
    Parameters:
    -----------
    probeset_name : str
        Full probeset name
        
    Returns:
    --------
    str
        Category 9 formatted label
    """
    import re
    
    # Determine filter prefix
    filter_label = None
    if probeset_name.startswith('Scanpy-Filter_All-Genes'):
        filter_label = 'Scanpy-All-Genes'
    elif probeset_name.startswith('Scanpy-Filter_HVG-Subset'):
        filter_label = 'Scanpy-HVG'
    elif probeset_name.startswith('Xenium-Filter_All-Genes'):
        filter_label = 'Xenium-All-Genes'
    elif probeset_name.startswith('Xenium-Filter_HVG-Subset'):
        filter_label = 'Xenium-HVG'
    
    # Extract dimred type and ratio
    dimred_type = None
    dimred_ratio = None
    
    # Pattern: dt_{dimred}_DT{dt_ratio}_Dimred{dimred_ratio}_
    pattern = r'dt_(pca|nmf)_DT([\d.]+)_Dimred([\d.]+)'
    match = re.search(pattern, probeset_name)
    if match:
        dimred_type = match.group(1)
        dimred_ratio_float = float(match.group(3))
        dimred_percentage = int(dimred_ratio_float * 100)
        dimred_ratio = f"{dimred_percentage}%"
    
    # Construct label
    if filter_label and dimred_type and dimred_ratio:
        return f"{filter_label}_dt_{dimred_type}_{dimred_ratio}"
    
    # Fallback
    return probeset_name


def extract_strategy_and_display_name(probeset_name, include_size=False):
    """
    Extract strategy category and display name from probeset name.
    
    Handles various naming patterns including fill-up strategies:
    - Simple external panels: Spapros, mMulti_v1, 5k (return simplified identifier)
    - Complex external panels: Any non-pipeline pattern (return full name)
    - Baselines: Random, HVG
    - Simple strategies: deg_only, dt_simple, dt_deg
    - Dimred-only: pca_global_method_a, nmf_per_celltype_method_b
    - Hybrid: dt_pca_DT0.5_Dimred0.5_global_method_a
    - Fill-up variants: ..._DEG-based-filling, ..._cell-type-specific-filling, ..._global-gene-filling
    
    This function uses a generic approach to detect external panels:
    - Known panels (Spapros, 5k, mMulti) return simplified names
    - Unknown external panels (anything not matching pipeline patterns) return full names
    
    Parameters:
    -----------
    probeset_name : str
        Full probeset name (e.g., "Scanpy-Filter_All-Genes_dt_pca_DT0.5_Dimred0.5_global_method_a_100_5k-addon")
    include_size : bool, optional (default=False)
        If True, append panel size (e.g., " (100)") to display name
    
    Returns:
    --------
    tuple : (category, display_name)
        category: Strategy identifier for color mapping
        display_name: Human-readable display name for plots (includes filling suffix and size if requested)
    """
    import re
    
    # Helper function to add panel size to display name
    def add_panel_size(display_name, probeset_name):
        if include_size:
            panel_size_match = re.search(r'_(\d+)(?:_|$)', probeset_name)
            if panel_size_match:
                panel_size = panel_size_match.group(1)
                return f"{display_name} ({panel_size})"
        return display_name
    
    # Check for fill-up strategy suffix first
    filling_suffix = None
    filling_abbrev = {
        'DEG-based-filling': 'DEG-fill',
        'cell-type-specific-filling': 'CT-fill',
        'global-gene-filling': 'Global-fill'
    }
    
    # Store original probeset name for size extraction
    original_probeset_name = probeset_name
    
    for full_suffix, abbrev in filling_abbrev.items():
        if probeset_name.endswith(f"_{full_suffix}") or f"_{full_suffix}_" in probeset_name:
            filling_suffix = abbrev
            # Strip suffix for strategy detection
            probeset_name = probeset_name.replace(f"_{full_suffix}", "")
            break
    
    # === CATEGORY A: Simple standalone external panels (exact match) ===
    if probeset_name == '5k':
        return '5k', add_panel_size('5k', original_probeset_name)
    if probeset_name == 'mMulti_v1' or probeset_name == 'mMulti':
        return 'mMulti_v1', add_panel_size('mMulti_v1', original_probeset_name)
    if probeset_name == 'Spapros' or probeset_name == 'spapros':
        return 'Spapros', add_panel_size('Spapros', original_probeset_name)
    
    # === CATEGORY A: Known panels in compound names (simplified identifier) ===
    # Check for Spapros - only if it's the strategy, not part of addon
    if ('Spapros' in probeset_name or 'spapros' in probeset_name) and not probeset_name.endswith('Spapros-addon') and not probeset_name.endswith('spapros-addon'):
        # Check if Spapros is in the strategy position (index 2 when split by '_')
        parts_check = probeset_name.split('_')
        if len(parts_check) > 2 and ('Spapros' in parts_check[1:3] or 'spapros' in parts_check[1:3]):
            return 'Spapros', add_panel_size('Spapros', original_probeset_name)
    
    # Don't match '5k-addon' or 'mMulti-addon' suffixes as strategies
    # Only match if they appear in the middle of the name
    if '_5k_' in probeset_name and not probeset_name.endswith('5k-addon'):
        return '5k', add_panel_size('5k', original_probeset_name)
    
    # Check for baselines (both uppercase and lowercase)
    if '_Random_' in probeset_name or probeset_name.startswith('Random') or '_random_' in probeset_name:
        return 'Random', add_panel_size('Random', original_probeset_name)
    if '_HVG_' in probeset_name or '_hvg_' in probeset_name or probeset_name.startswith('hvg_'):
        return 'HVG', add_panel_size('HVG', original_probeset_name)
    
    # Check for simple strategies
    if '_deg_only_' in probeset_name:
        display_name = 'DEG Only'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'deg_only', add_panel_size(display_name, original_probeset_name)
    if '_dt_simple_' in probeset_name:
        display_name = 'DT Simple'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'dt_simple', add_panel_size(display_name, original_probeset_name)
    if '_dt_deg_' in probeset_name:
        display_name = 'DT+DEG'
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return 'dt_deg', add_panel_size(display_name, original_probeset_name)
    
    # Check for dimred-only strategies
    dimred_only_pattern = r'_(pca|nmf)_(global|per_celltype)_method_([ab])_'
    dimred_only_match = re.search(dimred_only_pattern, probeset_name)
    if dimred_only_match:
        dimred_type, analysis_type, method = dimred_only_match.groups()
        # Use same abbreviations as baseline module
        method_label = 'abs' if method == 'a' else 'norm'
        selection_label = 'global' if analysis_type == 'global' else 'CT'
        category = f"{dimred_type}_{analysis_type}_method_{method}"
        display_name = f"{dimred_type}_{selection_label}_{method_label}"
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return category, add_panel_size(display_name, original_probeset_name)
    
    # Check for hybrid strategies (dt_pca/dt_nmf)
    hybrid_pattern = r'_dt_(pca|nmf)_DT([\d.]+)_Dimred([\d.]+)_(global|per_celltype)_method_([ab])_'
    hybrid_match = re.search(hybrid_pattern, probeset_name)
    if hybrid_match:
        dimred_type, dt_ratio, dimred_ratio, analysis_type, method = hybrid_match.groups()
        dimred_ratio_float = float(dimred_ratio)
        percentage = int(dimred_ratio_float * 100)
        
        # Create category for color mapping that matches the color dictionary keys
        # Format: dt_{dimred_type}_{percentage}_{analysis_type}_{method}
        # E.g., 'dt_nmf_25_global_a', 'dt_nmf_75_per_celltype_b'
        category = f"dt_{dimred_type}_{percentage}_{analysis_type}_{method}"
        
        # Create display name matching baseline module format: "dt_nmf_75%_CT_abs"
        # Use same abbreviations as baseline module
        method_label = 'abs' if method == 'a' else 'norm'
        selection_label = 'global' if analysis_type == 'global' else 'CT'
        display_name = f"dt_{dimred_type}_{percentage}%_{selection_label}_{method_label}"
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        
        return category, add_panel_size(display_name, original_probeset_name)
    
    # === CATEGORY B: Generic external panel detection ===
    # If we reached here, check if this is an unknown external panel
    # External panels are anything that:
    # 1. Does NOT match any pipeline patterns
    # 2. Has multiple components (contains underscores)
    # 3. Is NOT an addon suffix
    
    pipeline_patterns = [
        'dt_pca_DT', 'dt_nmf_DT',  # Hybrid strategies (checked above but included for clarity)
        'pca_global_', 'pca_per_celltype_',  # PCA-only (checked above)
        'nmf_global_', 'nmf_per_celltype_',  # NMF-only (checked above)
    ]
    
    is_pipeline_pattern = any(pattern in probeset_name for pattern in pipeline_patterns)
    is_addon_suffix = probeset_name.endswith('-addon')
    has_multiple_parts = len(probeset_name.split('_')) >= 3
    
    # If it's not a pipeline pattern, not an addon, and has structure, it's likely an external panel
    if not is_pipeline_pattern and not is_addon_suffix and has_multiple_parts:
        # Check if probeset name contains any known external panel names
        # Extract the panel name as category for proper color mapping
        known_external_panels = ['NSForest', 'scMER', 'Spapros', 'mMulti_v1', '5k']
        
        for panel_name in known_external_panels:
            if f'_{panel_name}_' in probeset_name or probeset_name.endswith(f'_{panel_name}'):
                # Found a known external panel - use just the panel name for both category and display
                # This shows "NSForest" or "scMER" instead of the full filename
                display_name = panel_name
                if filling_suffix:
                    display_name = f"{display_name} ({filling_suffix})"
                return panel_name, add_panel_size(display_name, original_probeset_name)
        
        # If no known external panel found, return full probeset name as both category and display name
        # This preserves all information (filter, size, etc.) for unknown external panels
        # Examples: "Scanpy-Filter_HVG_UnknownTool_200", "No-Filter_All-Genes_CustomTool_100"
        display_name = probeset_name
        if filling_suffix:
            display_name = f"{display_name} ({filling_suffix})"
        return probeset_name, add_panel_size(display_name, original_probeset_name)
    
    # Fallback for anything else
    display_name = probeset_name
    if filling_suffix:
        display_name = f"{display_name} ({filling_suffix})"
    
    return 'Other', add_panel_size(display_name, original_probeset_name)


def get_category_colors(external_names=None):
    """
    Get color mapping for different probe panel categories.
    Uses the same comprehensive color scheme as the baseline plotting module.
    UPDATED: Matches the new systematic color encoding from 20251009_Plotting-module_Clustering-knn-ct-class_HH.py
    
    Parameters:
    -----------
    external_names : list, optional
        List of external panel names (e.g., ['Spapros', 'mMulti_v1', '5k'])
        These will be assigned custom colors
    
    Returns:
    --------
    dict
        Dictionary mapping category names to color codes
    """
    # Initialize external_names if not provided
    if external_names is None:
        external_names = []
    
    # Base category colors - aligned with Clustering plotting module
    category_colors = {
        # Baseline/control strategies (both uppercase and lowercase)
        'Random': '#808080',         # Gray
        'random': '#808080',         # Gray (lowercase variant)
        'HVG': '#f0dd0d',            # Yellow
        'hvg': '#f0dd0d',            # Yellow (lowercase variant)
        
        # Simple strategies
        'deg_only': "#fa9c4a",       # Orange
        'dt_simple': "#d56a0d",      # Dark orange
        'dt_deg': "#875223",         # Brown
        
        # === DIMRED-ONLY STRATEGIES ===
        # NMF-only: Pink/Magenta family - CLEARLY DIFFERENT from dt_nmf blues
        'nmf_global_method_a': '#ff99ff',      # Light magenta - global, abs
        'nmf_global_method_b': '#cc3399',      # Dark magenta - global, norm
        'nmf_per_celltype_method_a': '#cc0066',  # Dark pink - CT, abs
        'nmf_per_celltype_method_b': '#800040',  # Very dark magenta - CT, norm
        
        # PCA-only: Green family - CLEARLY DIFFERENT from dt_pca cyans
        'pca_global_method_a': '#99ff99',      # Light green - global, abs
        'pca_global_method_b': '#339933',      # Dark green - global, norm
        'pca_per_celltype_method_a': '#006600',  # Dark forest green - CT, abs
        'pca_per_celltype_method_b': '#003300',  # Very dark forest green - CT, norm
        
        # === DT_NMF HYBRID STRATEGIES ===
        # HIGHLY DISTINCT COLORS - different color families for each combination
        # Global + Method A (abs): BRIGHT BLUE family
        'dt_nmf_10_global_a': '#80C0FF',   # Very light sky blue
        'dt_nmf_25_global_a': '#4DA6FF',   # Bright sky blue
        'dt_nmf_50_global_a': '#0080FF',   # Vivid blue
        'dt_nmf_75_global_a': '#0052CC',   # Strong blue
        'dt_nmf_90_global_a': '#003D99',   # Very deep blue
        # Global + Method B (norm): ORANGE-RED family
        'dt_nmf_10_global_b': '#FFBB99',   # Very light orange
        'dt_nmf_25_global_b': '#FF9966',   # Light orange
        'dt_nmf_50_global_b': '#FF6633',   # Bright orange
        'dt_nmf_75_global_b': '#FF3300',   # Red-orange
        'dt_nmf_90_global_b': '#CC1A00',   # Very deep red-orange
        # Per-celltype + Method A (abs): PURPLE family
        'dt_nmf_10_per_celltype_a': '#DDAAFF',  # Very light purple
        'dt_nmf_25_per_celltype_a': '#BB88FF',  # Light purple
        'dt_nmf_50_per_celltype_a': '#9933FF',  # Vivid purple
        'dt_nmf_75_per_celltype_a': '#7700CC',  # Deep purple
        'dt_nmf_90_per_celltype_a': '#550099',  # Very deep purple
        # Per-celltype + Method B (norm): BURGUNDY-BROWN family
        'dt_nmf_10_per_celltype_b': '#EE88BB',  # Very light rosy brown
        'dt_nmf_25_per_celltype_b': '#CC6699',  # Rosy brown
        'dt_nmf_50_per_celltype_b': '#993366',  # Wine red
        'dt_nmf_75_per_celltype_b': '#661133',  # Dark burgundy
        'dt_nmf_90_per_celltype_b': '#440022',  # Very dark burgundy
        
        # === DT_PCA HYBRID STRATEGIES ===
        # HIGHLY DISTINCT COLORS - different from dt_nmf
        # Global + Method A (abs): CYAN-TURQUOISE family
        'dt_pca_10_global_a': '#99FFDD',   # Very light turquoise
        'dt_pca_25_global_a': '#66FFCC',   # Light turquoise
        'dt_pca_50_global_a': '#00FFAA',   # Bright cyan-green
        'dt_pca_75_global_a': '#00CC88',   # Deep turquoise
        'dt_pca_90_global_a': '#009966',   # Very deep turquoise
        # Global + Method B (norm): YELLOW-AMBER family
        'dt_pca_10_global_b': '#FFEE99',   # Very light yellow
        'dt_pca_25_global_b': '#FFD966',   # Light yellow
        'dt_pca_50_global_b': '#FFBB33',   # Golden yellow
        'dt_pca_75_global_b': '#FF9900',   # Amber
        'dt_pca_90_global_b': '#CC7700',   # Very deep amber
        # Per-celltype + Method A (abs): LIME-GREEN family
        'dt_pca_10_per_celltype_a': '#CCFF88',  # Very light lime
        'dt_pca_25_per_celltype_a': '#AAFF55',  # Light lime
        'dt_pca_50_per_celltype_a': '#77DD22',  # Vivid lime
        'dt_pca_75_per_celltype_a': '#55AA00',  # Deep lime green
        'dt_pca_90_per_celltype_a': '#338800',  # Very deep lime green
        # Per-celltype + Method B (norm): TEAL-FOREST family
        'dt_pca_10_per_celltype_b': '#88CCAA',  # Very light teal
        'dt_pca_25_per_celltype_b': '#66AA88',  # Light teal
        'dt_pca_50_per_celltype_b': '#338866',  # Teal green
        'dt_pca_75_per_celltype_b': '#002626',  # Almost black green
        'dt_pca_90_per_celltype_b': '#001515',  # Very dark forest green
        
        'Other': '#7f7f7f'    # Gray
    }
    
    # Default colors for known external panels - aligned with Clustering plotting module
    default_external_colors = {
        'Spapros': "#957d06",
        'spapros': "#957d06",
        '10x_mMulti_v1': '#000000',  # Black - distinct from all other colors
        '10x_5k': '#000000',  # Black - distinct from all other colors
        'mMulti_v1': '#000000',      # Black - distinct from all other colors
        'mMulti': '#000000',
        '5k': '#000000',  # Black - distinct from all other colors
    }
    
    # Gradient for additional external panels - aligned with Clustering plotting module
    external_gradient = [
        "#76EFED",
        "#55AFAE",
        "#3E7C7B",
        "#203F3E",
        "#4C8098",
        "#1C4F66",
    ]
    
    # First, add all default external panel colors to category_colors
    # These are always available regardless of external_names parameter
    category_colors.update(default_external_colors)
    
    # Then, add colors for any additional external panels specified in external_names
    # that are not already in default_external_colors
    if external_names:
        logging.info(f"get_category_colors: external_names={external_names}")
        for idx, ext_name in enumerate(external_names):
            if ext_name not in category_colors:  # Only add if not already defined
                # Assign from gradient
                color = external_gradient[idx % len(external_gradient)]
                category_colors[ext_name] = color
                logging.info(f"  Added external color: {ext_name} → {color} (gradient index {idx})")
            else:
                logging.info(f"  Skipped {ext_name} (already in dict with color {category_colors[ext_name]})")
    
    logging.info(f"get_category_colors: returning {len(category_colors)} colors")
    logging.info(f"  External panel colors in result: {[(k, v) for k, v in category_colors.items() if k in (external_names or [])]}")
    
    return category_colors


def plot_aggregated_celltype_metrics(evaluation_results, plots_dir, title_suffix="", PNG_DPI=300, external_names=None, group_name=None):
    """
    Create plots showing weighted and macro aggregated evaluation metrics across all cell types.
    
    Plots the weighted and unweighted (macro) averages for MSE and explained variance
    across different probeset methods with baseline reference lines.
    
    Creates two plots per method:
    - Weighted and Macro MSE comparison
    - Weighted and Macro Explained Variance comparison
    
    FACTOR-RANGE MODE: When dataset names contain _Nfactors_, plots individual factors
    with factor-specific colors instead of aggregating by strategy.
    
    MULTI-SIZE MODE: When multiple panel sizes are detected (100, 200, 500), includes
    panel sizes in labels to plot them separately (e.g., "dt_nmf_75%_CT_abs (100)").
    
    Parameters:
    -----------
    evaluation_results: dict
        Dictionary containing evaluation results with summary statistics
    plots_dir: str
        Directory to save plots
    title_suffix: str, optional (default="")
        Suffix to add to plot title
    DEFAULT_PNG_DPI: int, optional (default=300)
        DPI resolution for saved plots
    external_names: list, optional
        List of external panel names for custom coloring
    group_name: str, optional
        Plot group name (e.g., 'category-2') for special formatting
        
    Returns:
    --------
    plot_df: pandas.DataFrame or None
        DataFrame containing the aggregated data used for plotting, or None if no data available
    """
    if not evaluation_results:
        logging.warning("No evaluation results to plot")
        return None
    
    # Check if any results contain summary statistics
    has_summary_data = False
    for probeset_name, results in evaluation_results.items():
        if any(key.endswith('_summary') for key in results.keys()):
            has_summary_data = True
            break
    
    if not has_summary_data:
        logging.warning("No summary statistics found in evaluation data")
        return None
    
    # Detect factor-range mode
    factor_range_mode = is_factor_range_mode(evaluation_results)
    if factor_range_mode:
        logging.info("FACTOR-RANGE MODE DETECTED: Will plot individual factors with factor-specific colors")
    
    # Detect multiple panel sizes - if found, include size in labels to distinguish them
    panel_sizes_detected = set()
    size_pattern = re.compile(r'_(\d+)(?:_|$)')
    for probeset_name in evaluation_results.keys():
        size_match = size_pattern.search(probeset_name)
        if size_match:
            panel_sizes_detected.add(int(size_match.group(1)))
    include_size_in_labels = len(panel_sizes_detected) > 1
    if include_size_in_labels:
        logging.info(f"Multiple panel sizes detected: {sorted(panel_sizes_detected)} - including size in labels for separate plotting")
    
    # Extract summary statistics for plotting
    aggregated_data = []
    
    # DEBUG: Log what we're processing
    logging.info(f"Processing {len(evaluation_results)} probeset(s) for aggregated plots")
    
    for probeset_name, results in evaluation_results.items():
        # DEBUG: Log keys available for this probeset
        logging.debug(f"  {probeset_name}: keys = {list(results.keys())}")
        
        # Extract display name based on mode
        if factor_range_mode:
            display_name = extract_display_name_for_factor_range(probeset_name)
            # Extract factor number for color mapping
            factor_num = extract_factor_number_from_dataset_name(probeset_name)
            category = f"factor_{factor_num}" if factor_num else "unknown"
        else:
            # Use helper function to extract strategy and display name
            # Check for Category 9 first to apply special labeling
            if group_name and 'category-9' in group_name.lower():
                display_name = generate_category_9_label(probeset_name)
                category, _ = extract_strategy_and_display_name(probeset_name)
            else:
                category, display_name = extract_strategy_and_display_name(probeset_name, include_size=include_size_in_labels)
        
        # Log the category assignment for debugging
        logging.info(f"  Probeset '{probeset_name}' → category='{category}', display='{display_name}'")
        
        # NMF summary results (both celltype and global)
        if 'nmf_celltype_summary' in results or 'nmf_global_summary' in results:
            # Check which summary type is available
            summary_key = 'nmf_celltype_summary' if 'nmf_celltype_summary' in results else 'nmf_global_summary'
            summary = results[summary_key]
            logging.debug(f"    Found {summary_key}, type={type(summary)}, keys={list(summary.keys()) if isinstance(summary, dict) else 'N/A'}")
            if isinstance(summary, dict):
                # Check if we have the required keys
                has_weighted_mse = COL_WEIGHTED_MSE in summary
                has_macro_mse = COL_MACRO_MSE in summary
                logging.debug(f"    Summary has weighted_mse: {has_weighted_mse}, macro_mse: {has_macro_mse}")
                if has_weighted_mse:
                    logging.debug(f"    weighted_mse_test_probe = {summary.get(COL_WEIGHTED_MSE)}")
                
                # Store factor number if in factor-range mode
                factor_num = extract_factor_number_from_dataset_name(probeset_name) if factor_range_mode else None
                
                aggregated_data.append({
                    'probeset': probeset_name,
                    'probeset_display': display_name,
                    'category': category,
                    'method': 'nmf',
                    'aggregation': 'weighted',
                    'mse': summary.get(COL_WEIGHTED_MSE, np.nan),
                    'mse_std': summary.get(f'{COL_WEIGHTED_MSE}_std', np.nan),
                    'expvar': summary.get(COL_WEIGHTED_EXPVAR, np.nan),
                    'expvar_std': summary.get(f'{COL_WEIGHTED_EXPVAR}_std', np.nan),
                    'mse_baseline': summary.get('weighted_mse_test_baseline', np.nan),
                    'expvar_baseline': summary.get('weighted_expvar_test_baseline', np.nan),
                    'factor_num': factor_num  # Add factor number for factor-range mode
                })
                aggregated_data.append({
                    'probeset': probeset_name,
                    'probeset_display': display_name,
                    'category': category,
                    'method': 'nmf',
                    'aggregation': 'macro',
                    'mse': summary.get(COL_MACRO_MSE, np.nan),
                    'mse_std': summary.get(f'{COL_MACRO_MSE}_std', np.nan),
                    'expvar': summary.get(COL_MACRO_EXPVAR, np.nan),
                    'expvar_std': summary.get(f'{COL_MACRO_EXPVAR}_std', np.nan),
                    'mse_baseline': summary.get('macro_mse_test_baseline', np.nan),
                    'expvar_baseline': summary.get('macro_expvar_test_baseline', np.nan),
                    'factor_num': factor_num  # Add factor number for factor-range mode
                })
        else:
            logging.debug(f"    No NMF summary found (has {list(results.keys())})")
        
        # Mapping summary results (both celltype and global)
        if 'mapping_celltype_summary' in results or 'mapping_global_summary' in results:
            # Check which summary type is available
            summary_key = 'mapping_celltype_summary' if 'mapping_celltype_summary' in results else 'mapping_global_summary'
            summary = results[summary_key]
            if isinstance(summary, dict):
                # Store factor number if in factor-range mode
                factor_num = extract_factor_number_from_dataset_name(probeset_name) if factor_range_mode else None
                
                aggregated_data.append({
                    'probeset': probeset_name,
                    'probeset_display': display_name,
                    'category': category,
                    'method': 'mapping',
                    'aggregation': 'weighted',
                    'mse': summary.get(COL_WEIGHTED_MSE, np.nan),
                    'mse_std': summary.get(f'{COL_WEIGHTED_MSE}_std', np.nan),
                    'expvar': summary.get(COL_WEIGHTED_EXPVAR, np.nan),
                    'expvar_std': summary.get(f'{COL_WEIGHTED_EXPVAR}_std', np.nan),
                    'mse_baseline': summary.get('weighted_mse_test_baseline', np.nan),
                    'expvar_baseline': summary.get('weighted_expvar_test_baseline', np.nan),
                    'factor_num': factor_num  # Add factor number for factor-range mode
                })
                aggregated_data.append({
                    'probeset': probeset_name,
                    'probeset_display': display_name,
                    'category': category,
                    'method': 'mapping',
                    'aggregation': 'macro',
                    'mse': summary.get(COL_MACRO_MSE, np.nan),
                    'mse_std': summary.get(f'{COL_MACRO_MSE}_std', np.nan),
                    'expvar': summary.get(COL_MACRO_EXPVAR, np.nan),
                    'expvar_std': summary.get(f'{COL_MACRO_EXPVAR}_std', np.nan),
                    'mse_baseline': summary.get('macro_mse_test_baseline', np.nan),
                    'expvar_baseline': summary.get('macro_expvar_test_baseline', np.nan),
                    'factor_num': factor_num  # Add factor number for factor-range mode
                })
    
    if not aggregated_data:
        logging.warning("No valid summary data found for plotting")
        return None
    
    # Convert to DataFrame
    plot_df = pd.DataFrame(aggregated_data)
    
    # DEBUG: Log what data we have
    logging.info(f"Aggregated data shape: {plot_df.shape}")
    logging.info(f"Methods: {plot_df['method'].unique()}")
    logging.info(f"Aggregation types: {plot_df['aggregation'].unique()}")
    logging.info(f"MSE values - NaN count: {plot_df['mse'].isna().sum()} / {len(plot_df)}")
    logging.info(f"ExpVar values - NaN count: {plot_df['expvar'].isna().sum()} / {len(plot_df)}")
    if not plot_df['mse'].isna().all():
        logging.info(f"MSE range: {plot_df['mse'].min():.2e} to {plot_df['mse'].max():.2e}")
    if not plot_df['expvar'].isna().all():
        logging.info(f"ExpVar range: {plot_df['expvar'].min():.4f} to {plot_df['expvar'].max():.4f}")
    
    # Get colors based on mode
    if factor_range_mode:
        logging.info("Using factor-specific colors for plotting")
        category_colors = get_factor_specific_colors()
        # Map factor_num to colors
        def get_color_for_row(row):
            if pd.notna(row['factor_num']):
                return category_colors.get(int(row['factor_num']), '#7f7f7f')
            return '#7f7f7f'
    else:
        logging.info(f"Calling get_category_colors with external_names={external_names}")
        category_colors = get_category_colors(external_names)
        logging.info(f"Received {len(category_colors)} category colors")
        logging.info(f"  Sample external colors: NSForest={category_colors.get('NSForest', 'NOT FOUND')}, scMER={category_colors.get('scMER', 'NOT FOUND')}")
        # Map category to colors
        def get_color_for_row(row):
            return category_colors.get(row['category'], '#7f7f7f')
    
    # Create combined plots for each method (nmf and mapping)
    for method in ['nmf', 'mapping']:
        method_data = plot_df[plot_df['method'] == method].copy()
        
        if method_data.empty:
            continue
        
        # Create MSE plot - comparing weighted vs macro
        if not method_data['mse'].isna().all():
            logging.info(f"  Creating aggregated MSE plot for {method} ({len(method_data)} rows)")
            fig, axes = plt.subplots(1, 2, figsize=(20, max(8, len(method_data['probeset_display'].unique()) * 0.5)))
            
            for idx, aggregation_type in enumerate(['weighted', 'macro']):
                ax = axes[idx]
                agg_data = method_data[method_data['aggregation'] == aggregation_type].copy()
                
                if agg_data.empty:
                    continue
                
                # Sort by MSE (lower is better)
                agg_data = agg_data.sort_values('mse', ascending=True)

                y_pos = np.arange(len(agg_data))
                mse_vals = agg_data['mse'].to_numpy(dtype=float)
                mse_std = np.nan_to_num(agg_data.get('mse_std', np.nan).to_numpy(dtype=float), nan=0.0)
                ax.barh(
                    y=y_pos,
                    width=mse_vals,
                    xerr=mse_std,
                    color='lightblue',
                    edgecolor='#00008B',
                    linewidth=2,
                    ecolor='#1f2a44',
                    capsize=3,
                )
                ax.set_yticks(y_pos)
                ax.set_yticklabels(agg_data['probeset_display'].tolist())
                ax.invert_yaxis()
                
                # Add baseline reference line
                baseline_mse = agg_data['mse_baseline'].dropna().iloc[0] if not agg_data['mse_baseline'].dropna().empty else None
                if baseline_mse is not None and not np.isnan(baseline_mse):
                    ax.axvline(x=baseline_mse, color='red', linestyle='--',
                              label=f'Full NMF Baseline ({baseline_mse:.2e})', alpha=0.7)
                ax.legend(loc='lower right', fontsize=14)

                # Set title and labels
                ax.set_title(f'{method.title()} MSE - {aggregation_type.title()} Average (lower is better)')
                ax.set_xlabel('MSE (lower is better)')
                ax.set_ylabel('Geneset')
            
            plt.suptitle(f'{method.title()} MSE - Weighted vs Macro Comparison{title_suffix}', fontsize=20, y=1.00)
            plt.tight_layout()
            
            # Save MSE plot
            plot_filename = f"aggregated_{method}_mse_weighted_macro_comparison{title_suffix.replace(' ', '_').replace('/', '_')}.png"
            plot_path = os.path.join(plots_dir, plot_filename)
            plt.savefig(plot_path, dpi=DEFAULT_PNG_DPI, bbox_inches='tight')
            plt.close()
            
            logging.info(f"Created aggregated MSE plot: {plot_filename}")
        else:
            logging.warning(f"  Skipping aggregated MSE plot for {method}: all MSE values are NaN")
        
        # Create Explained Variance plot - comparing weighted vs macro
        if not method_data['expvar'].isna().all():
            logging.info(f"  Creating aggregated ExpVar plot for {method} ({len(method_data)} rows)")
            fig, axes = plt.subplots(1, 2, figsize=(20, max(8, len(method_data['probeset_display'].unique()) * 0.5)))
            
            for idx, aggregation_type in enumerate(['weighted', 'macro']):
                ax = axes[idx]
                agg_data = method_data[method_data['aggregation'] == aggregation_type].copy()
                
                if agg_data.empty:
                    continue
                
                # Sort by explained variance (higher is better)
                agg_data = agg_data.sort_values('expvar', ascending=False)

                y_pos = np.arange(len(agg_data))
                exp_vals = agg_data['expvar'].to_numpy(dtype=float)
                exp_std = np.nan_to_num(agg_data.get('expvar_std', np.nan).to_numpy(dtype=float), nan=0.0)
                ax.barh(
                    y=y_pos,
                    width=exp_vals,
                    xerr=exp_std,
                    color='lightblue',
                    edgecolor='#00008B',
                    linewidth=2,
                    ecolor='#1f2a44',
                    capsize=3,
                )
                ax.set_yticks(y_pos)
                ax.set_yticklabels(agg_data['probeset_display'].tolist())
                ax.invert_yaxis()
                
                # Add baseline reference line
                baseline_expvar = agg_data['expvar_baseline'].dropna().iloc[0] if not agg_data['expvar_baseline'].dropna().empty else None
                if baseline_expvar is not None and not np.isnan(baseline_expvar):
                    ax.axvline(x=baseline_expvar, color='red', linestyle='--',
                              label=f'Full NMF Baseline ({baseline_expvar:.3f})', alpha=0.7)
                ax.legend(loc='lower right', fontsize=14)

                # Set title and labels
                ax.set_title(f'{method.title()} Explained Variance - {aggregation_type.title()} Average (higher is better)')
                ax.set_xlabel('Explained Variance (higher is better)')
                ax.set_ylabel('Geneset')
            
            plt.suptitle(f'{method.title()} Explained Variance - Weighted vs Macro Comparison{title_suffix}', fontsize=20, y=1.00)
            plt.tight_layout()
            
            # Save Explained Variance plot
            plot_filename = f"aggregated_{method}_expvar_weighted_macro_comparison{title_suffix.replace(' ', '_').replace('/', '_')}.png"
            plot_path = os.path.join(plots_dir, plot_filename)
            plt.savefig(plot_path, dpi=DEFAULT_PNG_DPI, bbox_inches='tight')
            plt.close()
            
            logging.info(f"Created aggregated Explained Variance plot: {plot_filename}")
        else:
            logging.warning(f"  Skipping aggregated ExpVar plot for {method}: all ExpVar values are NaN")
    
    return plot_df


def plot_celltype_evaluation_results(evaluation_results, plots_dir, title_suffix="", PNG_DPI=300, external_names=None, group_name=None, plot_celltype=True):
    """
    Create combined plots showing celltype-specific evaluation results with all NMF:DEG ratios 
    and baseline methods in single plots with reference lines.
    
    Creates exactly one plot for MSE and one for explained variance per celltype per method.
    
    FACTOR-RANGE MODE: When dataset names contain _Nfactors_, plots individual factors
    with factor-specific colors instead of aggregating by strategy.
    
    MULTI-SIZE MODE: When multiple panel sizes are detected (100, 200, 500), includes
    panel sizes in labels to plot them separately (e.g., "dt_nmf_75%_CT_abs (100)").
    
    Parameters:
    -----------
    evaluation_results: dict
        Dictionary containing evaluation results with celltype data
    plots_dir: str
        Directory to save plots
    title_suffix: str, optional (default="")
        Suffix to add to plot title
    DEFAULT_PNG_DPI: int, optional (default=300)
        DPI resolution for saved plots
    external_names: list, optional
        List of external panel names for custom coloring
    group_name: str, optional
        Plot group name (e.g., 'category-2') for special formatting
    plot_celltype: bool, optional (default=True)
        If False, skip creating individual celltype plots
        
    Returns:
    --------
    plot_df: pandas.DataFrame or None
        DataFrame containing the celltype data used for plotting, or None if no data available
    """
    if not evaluation_results:
        logging.warning("No evaluation results to plot")
        return None
    
    # Skip celltype plots if requested
    if not plot_celltype:
        logging.info("Skipping celltype-specific plots (plot_celltype=False)")
        return None
    
    # Check if any results contain celltype data
    has_celltype_data = False
    for probeset_name, results in evaluation_results.items():
        if any(key.startswith('nmf_celltype_celltype_results') or
               key.startswith('mapping_celltype_celltype_results') for key in results.keys()):
            has_celltype_data = True
            break
    
    if not has_celltype_data:
        logging.warning("No celltype-specific results found in evaluation data")
        return None
    
    # Detect factor-range mode
    factor_range_mode = is_factor_range_mode(evaluation_results)
    if factor_range_mode:
        logging.info("FACTOR-RANGE MODE DETECTED: Will plot individual factors with factor-specific colors")
    
    # Detect multiple panel sizes - if found, include size in labels to distinguish them
    panel_sizes_detected = set()
    size_pattern = re.compile(r'_(\d+)(?:_|$)')
    for probeset_name in evaluation_results.keys():
        size_match = size_pattern.search(probeset_name)
        if size_match:
            panel_sizes_detected.add(int(size_match.group(1)))
    include_size_in_labels = len(panel_sizes_detected) > 1
    if include_size_in_labels:
        logging.info(f"Multiple panel sizes detected (celltype): {sorted(panel_sizes_detected)} - including size in labels for separate plotting")
    
    # Extract celltype results for plotting
    celltype_data = []
    
    for probeset_name, results in evaluation_results.items():
        # Extract display name based on mode
        if factor_range_mode:
            display_name = extract_display_name_for_factor_range(probeset_name)
            # Extract factor number for color mapping
            factor_num = extract_factor_number_from_dataset_name(probeset_name)
            category = f"factor_{factor_num}" if factor_num else "unknown"
        else:
            # Use helper function to extract strategy and display name
            # Check for Category 9 first to apply special labeling
            if group_name and 'category-9' in group_name.lower():
                display_name = generate_category_9_label(probeset_name)
                category, _ = extract_strategy_and_display_name(probeset_name)
            else:
                category, display_name = extract_strategy_and_display_name(probeset_name, include_size=include_size_in_labels)
        
        # NMF celltype results
        if 'nmf_celltype_celltype_results' in results:
            celltype_results = results['nmf_celltype_celltype_results']
            if isinstance(celltype_results, dict):
                for celltype, celltype_metrics in celltype_results.items():
                    if not celltype_metrics.get(COL_SKIPPED, False):
                        # Store factor number if in factor-range mode
                        factor_num = extract_factor_number_from_dataset_name(probeset_name) if factor_range_mode else None

                        celltype_data.append({
                            'probeset': probeset_name,
                            'probeset_display': display_name,
                            'category': category,
                            'celltype': celltype,
                            'method': 'nmf',
                            # Use absolute values 
                            'mse': celltype_metrics.get(COL_MSE_TEST_PROBE, np.nan),
                            'expvar': celltype_metrics.get(COL_EXPVAR_TEST_PROBE, np.nan),
                            'mse_baseline': celltype_metrics.get('mse_test_baseline', np.nan),
                            'expvar_baseline': celltype_metrics.get('expvar_test_baseline', np.nan),
                            COL_N_CELLS: celltype_metrics.get(COL_N_CELLS, 0),
                            'factor_num': factor_num  # Add factor number for factor-range mode
                        })
        
        # Mapping celltype results
        if 'mapping_celltype_celltype_results' in results:
            celltype_results = results['mapping_celltype_celltype_results']
            if isinstance(celltype_results, dict):
                for celltype, celltype_metrics in celltype_results.items():
                    if not celltype_metrics.get(COL_SKIPPED, False):
                        # Store factor number if in factor-range mode
                        factor_num = extract_factor_number_from_dataset_name(probeset_name) if factor_range_mode else None
                        
                        celltype_data.append({
                            'probeset': probeset_name,
                            'probeset_display': display_name,
                            'category': category,
                            'celltype': celltype,
                            'method': 'mapping',
                            # Use absolute values
                            'mse': celltype_metrics.get(COL_MSE_TEST_PROBE, np.nan),
                            'expvar': celltype_metrics.get(COL_EXPVAR_TEST_PROBE, np.nan),
                            'mse_baseline': celltype_metrics.get('mse_test_baseline', np.nan),
                            'expvar_baseline': celltype_metrics.get('expvar_test_baseline', np.nan),
                            COL_N_CELLS: celltype_metrics.get(COL_N_CELLS, 0),
                            'factor_num': factor_num  # Add factor number for factor-range mode
                        })
    
    if not celltype_data:
        logging.warning("No valid celltype data found for plotting")
        return None
    
    # Convert to DataFrame
    plot_df = pd.DataFrame(celltype_data)
    
    # Get colors based on mode
    if factor_range_mode:
        logging.info("Using factor-specific colors for celltype plotting")
        category_colors = get_factor_specific_colors()
        # Map factor_num to colors
        def get_color_for_row(row):
            if pd.notna(row['factor_num']):
                return category_colors.get(int(row['factor_num']), '#7f7f7f')
            return '#7f7f7f'
    else:
        category_colors = get_category_colors(external_names)
        # Map category to colors
        def get_color_for_row(row):
            return category_colors.get(row['category'], '#7f7f7f')
    
    # Create combined plots for each method and celltype combination (2 plots total per celltype per method)
    for method in ['nmf', 'mapping']:
        method_data = plot_df[plot_df['method'] == method].copy()
        
        if method_data.empty:
            continue
        
        # Get unique celltypes
        celltypes = sorted(method_data['celltype'].unique())
        
        # Create plots for each celltype - MSE and Explained Variance combined
        for celltype in celltypes:
            celltype_data = method_data[method_data['celltype'] == celltype].copy()
            
            if celltype_data.empty:
                continue
            
            # Get baseline values (should be the same across all methods for this celltype)
            baseline_mse = celltype_data['mse_baseline'].dropna().iloc[0] if not celltype_data['mse_baseline'].dropna().empty else None
            baseline_expvar = celltype_data['expvar_baseline'].dropna().iloc[0] if not celltype_data['expvar_baseline'].dropna().empty else None
            
            # Create MSE plot
            if not celltype_data['mse'].isna().all():
                # Include factor_num column if in factor-range mode
                cols_to_select = ['probeset_display', 'category', 'mse']
                if factor_range_mode and 'factor_num' in celltype_data.columns:
                    cols_to_select.append('factor_num')
                mse_data = celltype_data[cols_to_select].copy()
                mse_data = mse_data.sort_values('mse', ascending=True)  # Lower is better for MSE
                
                plt.figure(figsize=(12, max(6, len(mse_data) * 0.4)))
                
                # Create barplot with lightblue fill and dark blue outline
                ax = sns.barplot(x='mse', y='probeset_display', data=mse_data, 
                                color='lightblue', edgecolor='#00008B', linewidth=2, dodge=False)

                
                # Add baseline reference line
                if baseline_mse is not None and not np.isnan(baseline_mse):
                    plt.axvline(x=baseline_mse, color='red', linestyle='--', 
                               label=f'Full NMF Baseline ({baseline_mse:.2e})', alpha=0.7)
                
                # Set title and labels
                ax.set_title(f'{method.title()} MSE - {celltype} (lower is better){title_suffix}')
                ax.set_xlabel('MSE (lower is better)')
                ax.set_ylabel('Geneset')
                
                plt.tight_layout()
                
                # Save MSE plot
                safe_celltype = celltype.replace('/', '_').replace(' ', '_')
                plot_filename = f"celltype_{method}_mse_{safe_celltype}_combined{title_suffix.replace(' ', '_').replace('/', '_')}.png"
                plot_path = os.path.join(plots_dir, plot_filename)
                plt.savefig(plot_path, dpi=DEFAULT_PNG_DPI, bbox_inches='tight')
                plt.close()
                
                logging.info(f"Created combined celltype MSE plot: {plot_filename}")
            
            # Create Explained Variance plot
            if not celltype_data['expvar'].isna().all():
                # Include factor_num column if in factor-range mode
                cols_to_select = ['probeset_display', 'category', 'expvar']
                if factor_range_mode and 'factor_num' in celltype_data.columns:
                    cols_to_select.append('factor_num')
                expvar_data = celltype_data[cols_to_select].copy()
                expvar_data = expvar_data.sort_values('expvar', ascending=False)  # Higher is better for explained variance
                
                plt.figure(figsize=(12, max(6, len(expvar_data) * 0.4)))
                
                # Create barplot with lightblue fill and dark blue outline
                ax = sns.barplot(x='expvar', y='probeset_display', data=expvar_data, 
                                color='lightblue', edgecolor='#00008B', linewidth=2, dodge=False)

                
                # Add baseline reference line
                if baseline_expvar is not None and not np.isnan(baseline_expvar):
                    plt.axvline(x=baseline_expvar, color='red', linestyle='--', 
                               label=f'Full NMF Baseline ({baseline_expvar:.3f})', alpha=0.7)
                
                # Set title and labels
                ax.set_title(f'{method.title()} Explained Variance - {celltype} (higher is better){title_suffix}')
                ax.set_xlabel('Explained Variance (higher is better)')
                ax.set_ylabel('Geneset')
                
                plt.tight_layout()
                
                # Save Explained Variance plot
                safe_celltype = celltype.replace('/', '_').replace(' ', '_')
                plot_filename = f"celltype_{method}_expvar_{safe_celltype}_combined{title_suffix.replace(' ', '_').replace('/', '_')}.png"
                plot_path = os.path.join(plots_dir, plot_filename)
                plt.savefig(plot_path, dpi=DEFAULT_PNG_DPI, bbox_inches='tight')
                plt.close()
                
                logging.info(f"Created combined celltype Explained Variance plot: {plot_filename}")
    
    return plot_df


def create_combined_plot_with_info(classifier_type, gene_count, metric, results, output_dir, 
                                   filter_type, gene_sel, PNG_DPI=300, external_names=None, group_name=None):
    """
    Create a plot for a specific metric that includes all methods (HVG, Random, Spapros, and all NMF/DEG ratios).
    Plots are saved with evaluation method prefix to prevent overwriting between NMF and mapping strategies.
    
    MULTI-SIZE MODE: When multiple panel sizes are detected (100, 200, 500), includes
    panel sizes in labels to plot them separately (e.g., "dt_nmf_75%_CT_abs (100)").
    
    Parameters:
    -----------
    classifier_type: str
        The classifier type (Basic-DT-classifier; XGBoost-classifier currently disabled)
    gene_count: int
        The gene count (100, 200, or 500)
    metric: str
        The metric to plot (nmf_mse, nmf_expvar, mapping_mse, mapping_expvar,
        nmf_mse_ratio, nmf_expvar_ratio, mapping_mse_ratio_test, mapping_generalization_gap)
    results: dict
        Dictionary with metric data for different methods
    output_dir: str
        Directory to save the plot
    filter_type: str
        The filter type (With-Xenium-Filter or No-Xenium-Filter)
    gene_sel: str
        The gene selection method (all-genes or hvg)
    DEFAULT_PNG_DPI: int, optional (default=300)
        DPI resolution for saved plots
    external_names: list, optional
        List of external panel names for custom coloring
    group_name: str, optional
        Plot group name (e.g., 'category-2') for special formatting
        
    Note:
    -----
    Filename format: EvaluationMethod_metric_classifier_genecount_filter_geneselection_ratio.png
    Example: NMF_nmf_mse_ratio_Decision-tree_100genes_NoFilter_allgenes_25-NMF_75-DEG.png
    """
    # Skip if no data for this metric
    if not results or metric not in results or not results[metric]:
        logging.warning(f"No data for metric {metric} in {classifier_type} for gene count {gene_count}")
        return
    
    # Extract baseline values from the first available result (same for all probesets)
    baseline_value = None
    for method_data in results.values():
        if isinstance(method_data, dict):
            # Search for baseline values in any method's results
            for method_name, method_result in method_data.items():
                if isinstance(method_result, dict):
                    if metric == "nmf_mse" and "nmf_mse_test_baseline" in method_result:
                        baseline_value = method_result["nmf_mse_test_baseline"]
                        break
                    elif metric == "nmf_expvar" and "nmf_expvar_test_baseline" in method_result:
                        baseline_value = method_result["nmf_expvar_test_baseline"]
                        break
                    elif metric == "mapping_mse" and "mapping_mse_test_baseline" in method_result:
                        baseline_value = method_result["mapping_mse_test_baseline"]
                        break
                    elif metric == "mapping_expvar" and "mapping_expvar_test_baseline" in method_result:
                        baseline_value = method_result["mapping_expvar_test_baseline"]
                        break
            if baseline_value is not None:
                break
    
    # Prepare data for plotting
    plot_data = []
    
    # Detect factor-range mode by checking if any method name contains _Nfactors_
    factor_range_mode = any(re.search(r'_(\d+)factors_', method) for method in results[metric].keys())
    if factor_range_mode:
        logging.info("FACTOR-RANGE MODE DETECTED in global plots: Will plot individual factors")
    
    # Detect multiple panel sizes - if found, include size in labels to distinguish them
    panel_sizes_detected = set()
    size_pattern = re.compile(r'_(\d+)(?:_|$)')
    for method in results[metric].keys():
        size_match = size_pattern.search(method)
        if size_match:
            panel_sizes_detected.add(int(size_match.group(1)))
    include_size_in_labels = len(panel_sizes_detected) > 1
    if include_size_in_labels:
        logging.info(f"Multiple panel sizes detected (global): {sorted(panel_sizes_detected)} - including size in labels for separate plotting")
    
    for method, value in results[metric].items():
        # Extract display name based on mode
        if factor_range_mode:
            display_name = extract_display_name_for_factor_range(method)
            # Extract factor number for sorting
            factor_num = extract_factor_number_from_dataset_name(method)
            category = f"factor_{factor_num}" if factor_num else "unknown"
        else:
            # Use helper function to extract strategy and display name
            # Check for Category 9 first to apply special labeling
            if group_name and 'category-9' in group_name.lower():
                display_name = generate_category_9_label(method)
                category, _ = extract_strategy_and_display_name(method)
            else:
                category, display_name = extract_strategy_and_display_name(method, include_size=include_size_in_labels)
        
        plot_data.append({
            'Method': method,
            'DisplayName': display_name,
            'Category': category,
            'Value': value,
            'FactorNum': extract_factor_number_from_dataset_name(method) if factor_range_mode else None
        })
    
    # Convert to DataFrame
    plot_df = pd.DataFrame(plot_data)
    
    # Skip if DataFrame is empty
    if plot_df.empty:
        logging.warning(f"No data to plot for {metric} in {classifier_type} for gene count {gene_count}")
        return
    
    # For MSE metrics, lower is better, so sort ascending
    # For explained variance metrics, higher is better, so sort descending
    # In factor-range mode, sort by factor number instead
    if factor_range_mode:
        plot_df = plot_df.sort_values('FactorNum', ascending=True)
    elif metric in ["mse", "nmf_mse", "mapping_mse", "representation_ratio_mse", "nmf_mse_ratio", "mapping_mse_ratio_test", "mapping_generalization_gap"]:
        plot_df = plot_df.sort_values('Value', ascending=True)
    else:
        plot_df = plot_df.sort_values('Value', ascending=False)
    
    # Create barplot
    plt.figure(figsize=(12, max(6, len(plot_df) * 0.5)))
    
    # Create barplot with white fill and dark blue outline (no colored bars)
    ax = sns.barplot(x='Value', y='DisplayName', data=plot_df, 
                    color='lightblue', edgecolor='#00008B', linewidth=2, dodge=False)

    
    # Set title and labels based on metric type
    if metric == "nmf_mse":
        title = f"NMF MSE - {gene_count} genes"
        xlabel = "MSE (lower is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--',
                       label=f'Full NMF Baseline ({baseline_value:.2e})', alpha=0.7)
    elif metric == "nmf_expvar":
        title = f"NMF Explained Variance - {gene_count} genes"
        xlabel = "Explained Variance (higher is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--',
                       label=f'Full NMF Baseline ({baseline_value:.3f})', alpha=0.7)
    elif metric == "mapping_mse":
        title = f"Mapping MSE - {gene_count} genes"
        xlabel = "MSE (lower is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--', 
                       label=f'Full NMF Baseline ({baseline_value:.2e})', alpha=0.7)
    elif metric == "mapping_expvar":
        title = f"Mapping Explained Variance - {gene_count} genes"
        xlabel = "Explained Variance (higher is better)"
        # Add baseline reference line
        if baseline_value is not None:
            plt.axvline(x=baseline_value, color='red', linestyle='--', 
                       label=f'Full NMF Baseline ({baseline_value:.3f})', alpha=0.7)
    # Legacy metrics
    elif metric == "mse":
        title = f"Mean Squared Error - {gene_count} genes"
        xlabel = "MSE (lower is better)"
    elif metric == "explained_variance":
        title = f"Explained Variance - {gene_count} genes"
        xlabel = "Explained Variance (higher is better)"
    elif metric == "representation_ratio_mse":
        title = f"MSE Ratio (Probeset/Full) - {gene_count} genes"
        xlabel = "MSE Ratio (lower is better)"
        # Add a line at x=1.0 to show the baseline (full NMF)
        plt.axvline(x=1.0, color='red', linestyle='--', label='Full NMF Baseline')
    elif metric == "representation_ratio_var":
        title = f"Explained Variance Ratio (Probeset/Full) - {gene_count} genes"
        xlabel = "Explained Variance Ratio (higher is better)"
        # Add a line at x=1.0 to show the baseline (full NMF)
        plt.axvline(x=1.0, color='red', linestyle='--', label='Full NMF Baseline')
    # Legacy ratio metrics
    elif metric == "nmf_mse_ratio":
        title = f"NMF MSE Ratio (Probe/Baseline) - {gene_count} genes"
        xlabel = "MSE Ratio (lower is better)"
        # Add a line at x=1.0 to show the baseline
        plt.axvline(x=1.0, color='red', linestyle='--', label='Baseline')
    elif metric == "nmf_expvar_ratio":
        title = f"NMF Explained Variance Ratio - {gene_count} genes"
        xlabel = "ExpVar Ratio (higher is better)"
        # Add a line at x=1.0 to show the baseline
        plt.axvline(x=1.0, color='red', linestyle='--', label='Baseline')
    elif metric == "mapping_mse_ratio_test":
        title = f"Mapping MSE Ratio (Test) - {gene_count} genes"
        xlabel = "MSE Ratio (lower is better)"
        # Add a line at x=1.0 to show the baseline
        plt.axvline(x=1.0, color='red', linestyle='--', label='Baseline')
    elif metric == "mapping_generalization_gap":
        title = f"Mapping Generalization Gap - {gene_count} genes"
        xlabel = "Generalization Gap (lower is better)"
        # Add a line at x=0.0 to show the ideal
        plt.axvline(x=0.0, color='red', linestyle='--', label='Ideal (No Gap)')
    else:
        title = f"{metric} - {gene_count} genes"
        xlabel = metric
    
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Geneset")
    plt.tight_layout()
    
    # Only show legend if baseline reference line exists (not for category colors)
    # For bar plots, we don't want to show category color legends - only the baseline reference line
    handles, labels = ax.get_legend_handles_labels()
    
    # Filter to only keep the baseline reference line in legend (if it exists)
    # Baseline lines have labels like 'Full NMF Baseline', 'Baseline', 'Ideal (No Gap)'
    baseline_labels = ['Full NMF Baseline', 'Baseline', 'Ideal (No Gap)']
    baseline_handles = []
    baseline_label_texts = []
    
    for handle, label in zip(handles, labels):
        # Check if this is a baseline line (contains these keywords)
        if any(bl in label for bl in baseline_labels):
            baseline_handles.append(handle)
            baseline_label_texts.append(label)
    
    # Only add legend if we have baseline reference lines
    if baseline_handles:
        plt.legend(handles=baseline_handles, labels=baseline_label_texts)
    
    # Create descriptive filename with all parameters
    # Format: evaluationmethod_metric_classifier_genecount_filter_geneselection.png
    classifier_name = "Decision-tree" if classifier_type == "Basic-DT-classifier" else "Unknown"
    filter_short = "WithFilter" if "With" in filter_type else "NoFilter"
    gene_sel_short = gene_sel.replace("-", "")
    
    # Determine evaluation method from metric name to avoid overwriting plots
    if metric.startswith("nmf_"):
        eval_method_prefix = "NMF"
        metric_short = metric.replace("nmf_", "")  # Remove prefix to avoid duplication
    elif metric.startswith("mapping_"):
        eval_method_prefix = "Mapping"
        metric_short = metric.replace("mapping_", "")  # Remove prefix to avoid duplication
    else:
        eval_method_prefix = "Unknown"
        metric_short = metric
    
    # Create combined plot filename
    filename = f"{eval_method_prefix}_{metric_short}_{classifier_name}_{gene_count}genes_{filter_short}_{gene_sel_short}.png"
    plt.savefig(os.path.join(output_dir, filename), dpi=DEFAULT_PNG_DPI)
    plt.close()
    
    logging.info(f"Created combined plot for {metric} with {gene_count} genes (all NMF:DEG ratios) in {output_dir}/{filename}")


def plot_standardized_comparison(
    summary_df: pd.DataFrame,
    group_col: str,
    output_path: str,
    title: str = "Standardized Performance Comparison",
    colors: list[str] | None = None,
) -> None:
    """Bar chart comparing standardized scores across groups.

    Args:
        summary_df: DataFrame with standardized_score_mean and _std columns.
        group_col: Column name for grouping (e.g., 'method', 'scenario').
        output_path: Path to save the plot.
        title: Plot title.
        colors: Optional list of colors for bars. Defaults to matplotlib color cycle.

    Note:
        Expects summary_df to have columns: {group_col}, standardized_score_mean,
        and standardized_score_std. The standardized_score_mean represents the
        average performance across iterations/folds, with error bars showing ±1 std.
    """
    fig, ax = plt.subplots(figsize=(8, 6))

    groups = summary_df[group_col]
    scores = summary_df["standardized_score_mean"]
    stds = summary_df["standardized_score_std"]

    if colors is None:
        colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']

    ax.bar(
        groups, scores, yerr=stds, capsize=5, alpha=0.7,
        color=colors[:len(groups)]
    )
    ax.axhline(y=0, color='gray', linestyle='--', linewidth=0.8, alpha=0.5)
    ax.set_xlabel(group_col.replace('_', ' ').title(), fontsize=12)
    ax.set_ylabel("Standardized Score", fontsize=12)
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.grid(axis='y', alpha=0.3, linestyle=':', linewidth=0.8)

    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.savefig(output_path, dpi=DEFAULT_PNG_DPI, bbox_inches='tight')
    plt.close()
